import {
  AGENT_OPS_OUTPUT_SECTIONS,
  type AgentOpsWorkflowDefinition,
  type AgentOpsWorkflowDefinitionInput,
  type AgentOpsWorkflowId,
  agentOpsWorkflowSchema,
} from './workflow-types'
import { getReviewSpecialistsForMode } from './review-army'
import {
  DESIGN_OPS_CHECKLIST,
  DOCUMENT_RELEASE_CHECKLIST,
} from './operating-loop'
import { AGENT_OPS_FAILURE_OWNERSHIP_KINDS } from './failure-ownership'
import { buildDesignOpsRuntimeContext, serializeDesignOpsForRuntime } from './design-ops'
import { buildAgentOpsBenchmarkMatrix } from './evals'
import {
  buildReleaseQualityRuntimeContext,
  getReleaseQualityChecksForWorkflow,
} from './release-quality-gates'

const standardOutputSections = [...AGENT_OPS_OUTPUT_SECTIONS]
const failureOwnershipMetadata = Object.freeze({
  failure_ownership: Object.freeze({
    required: true,
    categories: Object.freeze([...AGENT_OPS_FAILURE_OWNERSHIP_KINDS]),
  }),
})
const browserOperatorCapabilities = [
  'advanced:agent-ops',
  'advanced:browser-qa',
  'manage:orchestration',
  'tool:browser',
]
const browserOperatorEvidenceTypes = [
  'screenshot',
  'console_log',
  'network_log',
  'perf_metric',
  'test_result',
] as const

function browserOperatorMetadata(mode: string, vertical: string): Record<string, unknown> {
  return {
    browser_operator: {
      mode,
      vertical,
      capability: 'browser-operator',
      legacyCapability: 'browser-qa',
    },
  }
}

function designOpsMetadata(mode: string, vertical: string): Record<string, unknown> {
  return {
    design_ops: {
      mode,
      vertical,
      capability: 'design-ops',
      runtime_context: serializeDesignOpsForRuntime(buildDesignOpsRuntimeContext()),
      checklist: DESIGN_OPS_CHECKLIST.map((item) => item.id),
    },
    operating_loop: {
      checklist: DESIGN_OPS_CHECKLIST.map((item) => item.id),
    },
  }
}

function releaseQualityMetadata(
  workflowId: AgentOpsWorkflowId,
  mode: string,
  gateTargets: string[] = ['ship', 'deploy', 'promotion'],
): Record<string, unknown> {
  const checks = getReleaseQualityChecksForWorkflow(workflowId)
  return {
    release_quality: {
      mode,
      capability: 'release-quality-gates',
      runtime_context: buildReleaseQualityRuntimeContext({ workflowId }),
      checks: checks.map((check) => check.id),
      required_checks: checks.filter((check) => check.required).map((check) => check.id),
      gate_targets: gateTargets,
    },
    operating_loop: {
      checklist: checks.map((check) => check.id),
    },
  }
}

function defineWorkflow(definition: AgentOpsWorkflowDefinitionInput): AgentOpsWorkflowDefinition {
  const parsed = agentOpsWorkflowSchema.parse(definition)
  return Object.freeze({
    ...parsed,
    triggerPhrases: Object.freeze([...parsed.triggerPhrases]),
    requiredCapabilities: Object.freeze([...parsed.requiredCapabilities]),
    compatibleRuntimeModes: Object.freeze([...parsed.compatibleRuntimeModes]),
    capabilityFallbacks: Object.freeze(Object.fromEntries(
      Object.entries(parsed.capabilityFallbacks).map(([capability, fallbacks]) => [
        capability,
        Object.freeze([...fallbacks]),
      ]),
    )),
    inputFields: Object.freeze(parsed.inputFields.map((field) => Object.freeze({ ...field }))),
    outputSections: Object.freeze([...parsed.outputSections]),
    evidenceTypes: Object.freeze([...parsed.evidenceTypes]),
    approvalGates: Object.freeze(parsed.approvalGates.map((gate) => Object.freeze({ ...gate }))),
    evalPack: Object.freeze(parsed.evalPack.map((scenario) => Object.freeze({ ...scenario }))),
    steps: Object.freeze(parsed.steps.map((step) => Object.freeze({
      ...step,
      dependsOn: Object.freeze([...step.dependsOn]),
      payload: step.payload ? Object.freeze({ ...step.payload }) : undefined,
    }))),
    metadata: Object.freeze({ ...parsed.metadata }),
  }) as AgentOpsWorkflowDefinition
}

function field(
  key: string,
  label: string,
  type: AgentOpsWorkflowDefinition['inputFields'][number]['type'],
  required = true,
  description?: string,
): AgentOpsWorkflowDefinition['inputFields'][number] {
  return { key, label, type, required, description }
}

function agentRunStep(
  id: string,
  title: string,
  dependsOn: string[] = [],
  routeClass: 'fast' | 'strong' | 'external' = 'strong',
): AgentOpsWorkflowDefinition['steps'][number] {
  return {
    id,
    title,
    kind: 'execute',
    stepType: 'scheduled',
    dependsOn,
    routeClass,
    payload: { agent_ops_step: id },
  }
}

function approvalStep(
  id: string,
  title: string,
  dependsOn: string[] = [],
): AgentOpsWorkflowDefinition['steps'][number] {
  return {
    id,
    title,
    kind: 'approval',
    stepType: 'approval',
    dependsOn,
    routeClass: 'strong',
    payload: { agent_ops_step: id },
  }
}

function summarizeStep(
  id: string,
  title: string,
  dependsOn: string[],
): AgentOpsWorkflowDefinition['steps'][number] {
  return {
    id,
    title,
    kind: 'summarize',
    stepType: 'scheduled',
    dependsOn,
    routeClass: 'strong',
    payload: { agent_ops_step: id, output_sections: standardOutputSections },
  }
}

export const AGENT_OPS_WORKFLOWS = Object.freeze([
  defineWorkflow({
    id: 'investigate',
    slug: 'investigate',
    version: '1.0.0',
    name: 'Investigate',
    description: 'Triage a question, incident, log, channel thread, or runtime symptom and return evidence-backed next steps.',
    promise: 'Understand what is happening and what to do next.',
    triggerPhrases: ['investigate this', 'debug this', 'what happened'],
    defaultAgentRole: 'investigator',
    executionMode: 'single_run',
    safetyMode: 'read_only',
    requiredCapabilities: ['core:replay', 'standard:system', 'advanced:agent-ops'],
    inputFields: [field('target', 'Target', 'text', true, 'Question, URL, log excerpt, run id, or incident description.')],
    outputSections: standardOutputSections,
    evidenceTypes: ['log_excerpt', 'trace', 'transcript'],
    approvalGates: [],
    evalPack: [
      { id: 'evidence-backed', label: 'Evidence backed', assertion: 'Findings cite concrete evidence instead of speculation.', required: true },
    ],
    steps: [],
    metadata: {},
  }),
  defineWorkflow({
    id: 'office-hours',
    slug: 'office-hours',
    version: '1.0.0',
    name: 'Office Hours',
    description: 'Answer project questions with context, links, and recommended follow-up work.',
    promise: 'Get a clear answer without starting a heavy workflow.',
    triggerPhrases: ['office hours', 'answer this', 'explain this'],
    defaultAgentRole: 'project guide',
    executionMode: 'single_run',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'memory:project'],
    inputFields: [field('question', 'Question', 'text')],
    outputSections: standardOutputSections,
    evidenceTypes: ['memory_hit', 'transcript'],
    approvalGates: [],
    evalPack: [],
    steps: [],
    metadata: {},
  }),
  defineWorkflow({
    id: 'autoplan',
    slug: 'autoplan',
    version: '1.0.0',
    name: 'Autoplan',
    description: 'Turn an ambiguous goal into an implementation plan, risks, review gates, and a ship path.',
    promise: 'Create a plan that is ready for engineering review.',
    triggerPhrases: ['make a plan', 'autoplan', 'plan this'],
    defaultAgentRole: 'planning lead',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'manage:orchestration', 'memory:project'],
    inputFields: [field('goal', 'Goal', 'text')],
    outputSections: standardOutputSections,
    evidenceTypes: ['transcript', 'memory_hit'],
    approvalGates: [],
    evalPack: [
      { id: 'clear-phases', label: 'Clear phases', assertion: 'Plan separates sequencing, risks, verification, and rollback.', required: true },
    ],
    steps: [
      agentRunStep('scope', 'Clarify goal and constraints', [], 'fast'),
      agentRunStep('design', 'Draft implementation strategy', ['scope']),
      agentRunStep('review', 'Review plan for risks and missing dependencies', ['design']),
      summarizeStep('summary', 'Produce final plan', ['review']),
    ],
    metadata: {},
  }),
  defineWorkflow({
    id: 'plan-ceo-review',
    slug: 'plan-ceo-review',
    version: '1.0.0',
    name: 'CEO Plan Review',
    description: 'Review a plan for strategy, sequencing, customer impact, and business risk.',
    promise: 'Make the plan sharper from an executive/product lens.',
    triggerPhrases: ['ceo review', 'strategy review'],
    defaultAgentRole: 'executive reviewer',
    executionMode: 'single_run',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops'],
    inputFields: [field('plan', 'Plan', 'text')],
    outputSections: standardOutputSections,
    evidenceTypes: ['transcript'],
    approvalGates: [],
    evalPack: [],
    steps: [],
    metadata: {},
  }),
  defineWorkflow({
    id: 'plan-eng-review',
    slug: 'plan-eng-review',
    version: '1.0.0',
    name: 'Engineering Plan Review',
    description: 'Review a plan for architecture, operability, scalability, security, and rollback risk.',
    promise: 'Make the plan implementable without hidden engineering debt.',
    triggerPhrases: ['engineering review', 'architecture review'],
    defaultAgentRole: 'engineering reviewer',
    executionMode: 'single_run',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops'],
    inputFields: [field('plan', 'Plan', 'text')],
    outputSections: standardOutputSections,
    evidenceTypes: ['transcript'],
    approvalGates: [],
    evalPack: [],
    steps: [],
    metadata: {},
  }),
  defineWorkflow({
    id: 'plan-design-review',
    slug: 'plan-design-review',
    version: '1.0.0',
    name: 'Design Plan Review',
    description: 'Review a plan for UX clarity, product hierarchy, accessibility, and user confidence.',
    promise: 'Make the plan easier and better for users.',
    triggerPhrases: ['design review', 'ux review'],
    defaultAgentRole: 'design reviewer',
    executionMode: 'single_run',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops'],
    inputFields: [field('plan', 'Plan', 'text')],
    outputSections: standardOutputSections,
    evidenceTypes: ['transcript', 'screenshot'],
    approvalGates: [],
    evalPack: [],
    steps: [],
    metadata: {},
  }),
  defineWorkflow({
    id: 'plan-devex-review',
    slug: 'plan-devex-review',
    version: '1.0.0',
    name: 'DevEx Plan Review',
    description: 'Review a plan for code organization, naming, onboarding clarity, and maintainability.',
    promise: 'Make the implementation easier to understand and extend.',
    triggerPhrases: ['devex review', 'dx review'],
    defaultAgentRole: 'developer experience reviewer',
    executionMode: 'single_run',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops'],
    inputFields: [field('plan', 'Plan', 'text')],
    outputSections: standardOutputSections,
    evidenceTypes: ['transcript'],
    approvalGates: [],
    evalPack: [],
    steps: [],
    metadata: {},
  }),
  defineWorkflow({
    id: 'design-consultation',
    slug: 'design-consultation',
    version: '1.0.0',
    name: 'Design Consultation',
    description: 'Turn a product, brand, campaign, or UX question into a clear design direction with evidence and tradeoffs.',
    promise: 'Clarify the design direction before making assets or code.',
    triggerPhrases: ['design consultation', 'design direction', 'creative brief'],
    defaultAgentRole: 'design strategist',
    executionMode: 'single_run',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'design:taste-profile', 'memory:project'],
    inputFields: [
      field('goal', 'Goal', 'text', true, 'Product, marketing, sales, brand, or UX direction to explore.'),
      field('audience', 'Audience', 'text', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['transcript', 'design_rationale', 'memory_hit'],
    approvalGates: [],
    evalPack: [
      { id: 'non-dev-clarity', label: 'Non-developer clarity', assertion: 'Recommendation is understandable by non-engineering operators.', required: true },
      { id: 'taste-transparent', label: 'Taste transparent', assertion: 'Design rationale names assumed preferences and uncertainty.', required: true },
    ],
    steps: [],
    metadata: designOpsMetadata('consult', 'cross_functional'),
  }),
  defineWorkflow({
    id: 'design-variants',
    slug: 'design-variants',
    version: '1.0.0',
    name: 'Design Variants',
    description: 'Generate and compare multiple design directions for a page, asset, campaign, or product surface.',
    promise: 'Explore options before converging on one direction.',
    triggerPhrases: ['design variants', 'make variants', 'explore designs'],
    defaultAgentRole: 'design exploration lead',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'manage:orchestration', 'design:taste-profile'],
    inputFields: [
      field('brief', 'Brief', 'text', true),
      field('constraints', 'Constraints', 'text', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['variant_board', 'mockup', 'design_rationale', 'screenshot'],
    approvalGates: [],
    evalPack: [
      { id: 'distinct-directions', label: 'Distinct directions', assertion: 'Variants are meaningfully different rather than cosmetic duplicates.', required: true },
      { id: 'comparison-board', label: 'Comparison board', assertion: 'Output includes a clear comparison board with rationale and risks.', required: true },
    ],
    steps: [
      agentRunStep('brief', 'Clarify audience, promise, and constraints', [], 'fast'),
      agentRunStep('variants', 'Generate distinct design directions', ['brief']),
      agentRunStep('compare', 'Compare variants against taste and constraints', ['variants']),
      summarizeStep('variant-board', 'Produce variant board', ['compare']),
    ],
    metadata: designOpsMetadata('variants', 'cross_functional'),
  }),
  defineWorkflow({
    id: 'review',
    slug: 'review',
    version: '1.0.0',
    name: 'Review',
    description: 'Review a PR, diff, branch, or patch with specialist passes and deduplicated findings.',
    promise: 'Find the issues that matter before they reach users.',
    triggerPhrases: ['review this pr', 'review this diff', 'code review'],
    defaultAgentRole: 'code reviewer',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'manage:orchestration', 'tool:repo.read'],
    inputFields: [
      field('target', 'PR, branch, or diff', 'pull_request'),
      field('focus', 'Review focus', 'text', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['diff', 'review_finding', 'test_result', 'log_excerpt'],
    approvalGates: [],
    evalPack: [
      { id: 'actionable-findings', label: 'Actionable findings', assertion: 'Every finding has severity, evidence, and concrete remediation.', required: true },
    ],
    steps: [
      agentRunStep('scope', 'Load and scope the change', [], 'fast'),
      agentRunStep('correctness', 'Review correctness and regressions', ['scope']),
      agentRunStep('security', 'Review trust boundaries and data handling', ['scope']),
      agentRunStep('tests', 'Review tests and verification gaps', ['scope']),
      summarizeStep('dedupe', 'Dedupe findings and produce review', ['correctness', 'security', 'tests']),
    ],
    metadata: {
      review_army: {
        mode: 'pre_merge',
        specialists: getReviewSpecialistsForMode('pre_merge').map((specialist) => specialist.slug),
      },
    },
  }),
  defineWorkflow({
    id: 'qa',
    slug: 'qa',
    version: '1.0.0',
    name: 'QA',
    description: 'Exercise a URL, route, app flow, or release candidate and capture browser-grade evidence.',
    promise: 'Tell the team if the product actually works.',
    triggerPhrases: ['qa this url', 'test this flow', 'smoke test'],
    defaultAgentRole: 'qa analyst',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'advanced:browser-qa', 'manage:orchestration', 'tool:browser', 'design:taste-profile'],
    inputFields: [
      field('target', 'URL or flow', 'url'),
      field('scenario', 'Scenario', 'text', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['screenshot', 'console_log', 'network_log', 'perf_metric', 'test_result'],
    approvalGates: [],
    evalPack: [
      { id: 'visual-evidence', label: 'Visual evidence', assertion: 'QA output includes screenshots or browser evidence when available.', required: true },
    ],
    steps: [
      agentRunStep('prepare', 'Prepare QA scenario', [], 'fast'),
      agentRunStep('explore', 'Explore target flow in browser', ['prepare']),
      agentRunStep('verify', 'Verify behavior and collect evidence', ['explore']),
      summarizeStep('report', 'Produce QA report', ['verify']),
    ],
    metadata: failureOwnershipMetadata,
  }),
  defineWorkflow({
    id: 'check-page',
    slug: 'check-page',
    version: '1.0.0',
    name: 'Check Page',
    description: 'Check a public page or landing page for obvious issues, broken requests, visual evidence, and next actions.',
    promise: 'Tell the team whether this page is healthy and what needs attention.',
    triggerPhrases: ['check this page', 'check landing page', 'audit landing page'],
    defaultAgentRole: 'page quality analyst',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: browserOperatorCapabilities,
    inputFields: [
      field('target', 'Page URL', 'url'),
      field('goal', 'What good looks like', 'text', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: [...browserOperatorEvidenceTypes],
    approvalGates: [],
    evalPack: [
      { id: 'page-evidence', label: 'Page evidence', assertion: 'Output includes browser evidence, visible issues, and concrete next actions.', required: true },
    ],
    steps: [
      agentRunStep('open', 'Open page and capture initial evidence', [], 'fast'),
      agentRunStep('inspect', 'Inspect visible, console, network, and performance signals', ['open']),
      summarizeStep('report', 'Produce page check report', ['inspect']),
    ],
    metadata: browserOperatorMetadata('observe', 'cross_functional'),
  }),
  defineWorkflow({
    id: 'test-funnel',
    slug: 'test-funnel',
    version: '1.0.0',
    name: 'Test Funnel',
    description: 'Walk through a signup, checkout, booking, lead, or onboarding funnel and report where users get stuck.',
    promise: 'Show whether the funnel works from a user point of view.',
    triggerPhrases: ['test this funnel', 'test signup flow', 'test checkout flow'],
    defaultAgentRole: 'funnel tester',
    executionMode: 'dag',
    safetyMode: 'approval_gated',
    requiredCapabilities: [...browserOperatorCapabilities, 'core:approvals'],
    inputFields: [
      field('target', 'Starting URL', 'url'),
      field('scenario', 'Funnel scenario', 'text', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: [...browserOperatorEvidenceTypes],
    approvalGates: [
      { id: 'submit-approval', label: 'Submit approval', reason: 'Funnel tests may reach irreversible submit, purchase, booking, or message actions.', requiredFor: ['submit', 'purchase', 'book', 'message'] },
    ],
    evalPack: [
      { id: 'funnel-path', label: 'Funnel path', assertion: 'Report identifies the tested path, blockers, evidence, and where human approval stopped action.', required: true },
    ],
    steps: [
      agentRunStep('scenario', 'Prepare funnel scenario and safety boundaries', [], 'fast'),
      agentRunStep('walkthrough', 'Walk through the funnel until a safe stop or approval gate', ['scenario']),
      summarizeStep('report', 'Produce funnel report', ['walkthrough']),
    ],
    metadata: browserOperatorMetadata('test', 'marketing_sales_product'),
  }),
  defineWorkflow({
    id: 'buy-stuff',
    slug: 'buy-stuff',
    version: '0.1.0',
    name: 'Buy Stuff',
    description: 'Prepare a governed web purchase with Browser Operator evidence, Agent Commerce policy checks, approval gates, and receipt requirements.',
    promise: 'Build the cart safely, prove the policy decision, and only buy when checkout is verified and approved.',
    triggerPhrases: ['buy stuff', 'buy groceries', 'purchase this', 'shop for me'],
    defaultAgentRole: 'commerce operator',
    executionMode: 'dag',
    safetyMode: 'approval_gated',
    requiredCapabilities: [...browserOperatorCapabilities, 'core:approvals'],
    inputFields: [
      field('request', 'What to buy', 'text', true, 'Items, quantities, preferences, and the outcome the user wants.'),
      field('merchant', 'Preferred merchant', 'text', false, 'Optional store, marketplace, Shopify shop, Carrefour, Amazon, or merchant URL.'),
      field('budget', 'Budget or max total', 'text', false, 'Optional hard budget, delivery-fee tolerance, and substitution ceiling.'),
      field('policy', 'Purchase policy', 'text', false, 'Optional standing rules such as allowed categories, substitutions, delivery windows, and when to ask.'),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['screenshot', 'transcript', 'approval', 'test_result'],
    approvalGates: [
      {
        id: 'cart-approval',
        label: 'Cart approval',
        reason: 'Buying can spend money, create deliveries, or commit a user to merchant terms.',
        requiredFor: ['purchase', 'checkout', 'payment', 'submit-order'],
      },
      {
        id: 'policy-exception-approval',
        label: 'Policy exception approval',
        reason: 'Budget, merchant, substitution, delivery, or account-session drift must be approved before continuing.',
        requiredFor: ['budget-exception', 'merchant-exception', 'substitution-exception', 'profile-reconnect'],
      },
    ],
    evalPack: [
      { id: 'checkout-fail-closed', label: 'Checkout fail closed', assertion: 'The workflow blocks checkout unless merchant adapter reliability, account profile, policy, approval, idempotency, and receipt capture are all valid.', required: true },
      { id: 'cart-proof', label: 'Cart proof', assertion: 'The report includes cart items, merchant, total, delivery constraints, risks, and evidence before any purchase decision.', required: true },
      { id: 'receipt-proof', label: 'Receipt proof', assertion: 'A completed purchase includes receipt/order evidence, or the run remains blocked/assisted rather than marked complete.', required: true },
    ],
    steps: [
      agentRunStep('scope', 'Scope purchase request, merchant, budget, and standing policy', [], 'fast'),
      agentRunStep('merchant-readiness', 'Check merchant adapter tier, connected profile, provider affinity, and risk posture', ['scope']),
      agentRunStep('cart-dry-run', 'Build or verify the cart up to a safe pre-submit boundary', ['merchant-readiness']),
      approvalStep('approve-cart', 'Request approval for cart, total, delivery slot, substitutions, and checkout authority', ['cart-dry-run']),
      agentRunStep('checkout-or-block', 'Execute only live-supported approved checkout or fail closed with a handoff', ['approve-cart']),
      agentRunStep('receipt-capture', 'Capture receipt, order id, timestamp, and proof bundle when checkout completes', ['checkout-or-block']),
      summarizeStep('report', 'Produce purchase report, risks, receipt state, and next actions', ['receipt-capture']),
    ],
    metadata: {
      ...browserOperatorMetadata('buy', 'consumer_commerce_ops'),
      agent_commerce: {
        capability: 'agent-commerce',
        requires_policy: true,
        requires_approval: true,
        requires_idempotency: true,
        requires_receipt: true,
        checkout_mode: 'fail_closed',
      },
      browser_checkout: {
        adapter_contract: '@lucid/browser-checkout-adapter',
        staging_gate: 'browser-checkout:staging-gate',
        default_mode: 'dry_run_until_live_supported',
        live_supported_families: ['sandbox'],
        assisted_families: ['shopify', 'carrefour', 'amazon'],
        research_only_families: ['instacart', 'walmart'],
        no_silent_fallback_for: ['authenticated_account', 'cart', 'checkout', 'payment'],
        promotion_requirements: [
          'fixture_pack',
          'secure_takeover_smoke',
          'profile_reuse_smoke',
          'checkout_dry_run',
          'approval_gate',
          'idempotency_guard',
          'receipt_parser',
          'live_sandbox_or_verified_merchant_smoke',
        ],
      },
      trust_shield: {
        risk_level: 'high',
        high_risk_actions: ['purchase', 'payment', 'submit-order'],
        medium_risk_actions: ['add-to-cart', 'fill-address', 'choose-delivery-slot'],
      },
    },
  }),
  defineWorkflow({
    id: 'research-site',
    slug: 'research-site',
    version: '1.0.0',
    name: 'Research Website',
    description: 'Research a website, competitor page, docs page, or market surface and extract evidence-backed insights.',
    promise: 'Turn a website into useful research with links and evidence.',
    triggerPhrases: ['research this website', 'research competitor site', 'market research'],
    defaultAgentRole: 'web research analyst',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: browserOperatorCapabilities,
    inputFields: [
      field('target', 'Website URL', 'url'),
      field('question', 'Research question', 'text', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['screenshot', 'transcript', 'log_excerpt', 'test_result'],
    approvalGates: [],
    evalPack: [
      { id: 'cited-research', label: 'Cited research', assertion: 'Research claims cite observed page evidence and avoid unsupported conclusions.', required: true },
    ],
    steps: [
      agentRunStep('scope', 'Scope research question', [], 'fast'),
      agentRunStep('observe', 'Observe and extract relevant site evidence', ['scope']),
      summarizeStep('report', 'Produce research brief', ['observe']),
    ],
    metadata: browserOperatorMetadata('observe', 'marketing_sales_strategy'),
  }),
  defineWorkflow({
    id: 'extract-data',
    slug: 'extract-data',
    version: '1.0.0',
    name: 'Extract Data',
    description: 'Extract structured public-page data such as pricing, plan tables, feature lists, contacts, or listings with source evidence.',
    promise: 'Return structured data with provenance instead of a vague summary.',
    triggerPhrases: ['extract data', 'extract pricing', 'scrape this page'],
    defaultAgentRole: 'data extraction analyst',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: browserOperatorCapabilities,
    inputFields: [
      field('target', 'Source URL', 'url'),
      field('schema', 'Desired fields', 'text', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['screenshot', 'transcript', 'test_result'],
    approvalGates: [],
    evalPack: [
      { id: 'structured-provenance', label: 'Structured provenance', assertion: 'Extracted data is structured and tied back to source evidence.', required: true },
    ],
    steps: [
      agentRunStep('schema', 'Infer or confirm extraction schema', [], 'fast'),
      agentRunStep('extract', 'Extract structured data with source evidence', ['schema']),
      summarizeStep('report', 'Produce extraction report', ['extract']),
    ],
    metadata: browserOperatorMetadata('extract', 'marketing_sales_ops'),
  }),
  defineWorkflow({
    id: 'monitor-page',
    slug: 'monitor-page',
    version: '1.0.0',
    name: 'Monitor Page',
    description: 'Check a page repeatedly for availability, visual or content changes, console/network failures, and alert-worthy drift.',
    promise: 'Turn an important page into a recurring monitored workflow.',
    triggerPhrases: ['monitor this page', 'watch this page', 'track competitor changes'],
    defaultAgentRole: 'page monitor',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: browserOperatorCapabilities,
    inputFields: [
      field('target', 'Page URL', 'url'),
      field('cadence', 'Cadence or trigger', 'text', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: [...browserOperatorEvidenceTypes],
    approvalGates: [],
    evalPack: [
      { id: 'monitor-signal', label: 'Monitor signal', assertion: 'Report identifies baseline evidence, monitored signals, and alert thresholds.', required: true },
    ],
    steps: [
      agentRunStep('baseline', 'Capture baseline browser evidence', [], 'fast'),
      agentRunStep('compare', 'Compare monitored signals and detect drift', ['baseline']),
      summarizeStep('report', 'Produce monitoring report', ['compare']),
    ],
    metadata: browserOperatorMetadata('monitor', 'marketing_ops_product'),
  }),
  defineWorkflow({
    id: 'update-portal',
    slug: 'update-portal',
    version: '1.0.0',
    name: 'Update Portal',
    description: 'Prepare or perform a controlled browser operation in an authenticated portal with approval gates and audit evidence.',
    promise: 'Make browser-based operations auditable and approval-safe.',
    triggerPhrases: ['update portal', 'fill portal form', 'operate portal'],
    defaultAgentRole: 'browser operations specialist',
    executionMode: 'dag',
    safetyMode: 'approval_gated',
    requiredCapabilities: [...browserOperatorCapabilities, 'core:approvals'],
    inputFields: [
      field('target', 'Portal URL', 'url'),
      field('task', 'Task to perform', 'text'),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['screenshot', 'transcript', 'approval', 'test_result'],
    approvalGates: [
      { id: 'operation-approval', label: 'Operation approval', reason: 'Portal operations can change external systems or send irreversible submissions.', requiredFor: ['submit', 'save', 'delete', 'purchase', 'message'] },
    ],
    evalPack: [
      { id: 'approval-safe-operation', label: 'Approval-safe operation', assertion: 'The workflow stops before irreversible actions unless approval is granted and audited.', required: true },
    ],
    steps: [
      agentRunStep('prepare', 'Prepare portal task and risk boundaries', [], 'fast'),
      agentRunStep('stage', 'Stage browser operation up to an approval-safe point', ['prepare']),
      approvalStep('approve', 'Request approval before irreversible action', ['stage']),
      summarizeStep('report', 'Produce portal operation report', ['approve']),
    ],
    metadata: browserOperatorMetadata('operate', 'operations_sales_support'),
  }),
  defineWorkflow({
    id: 'support-repro',
    slug: 'support-repro',
    version: '1.0.0',
    name: 'Reproduce Issue',
    description: 'Reproduce a customer-reported issue in the browser and collect evidence for support, product, or engineering.',
    promise: 'Turn a report into evidence the team can act on.',
    triggerPhrases: ['reproduce issue', 'repro customer issue', 'check customer bug'],
    defaultAgentRole: 'support reproduction analyst',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: browserOperatorCapabilities,
    inputFields: [
      field('target', 'Page or app URL', 'url'),
      field('steps', 'Reported steps', 'text', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: [...browserOperatorEvidenceTypes],
    approvalGates: [],
    evalPack: [
      { id: 'repro-evidence', label: 'Repro evidence', assertion: 'Report states whether the issue reproduced and includes evidence or a clear non-repro path.', required: true },
    ],
    steps: [
      agentRunStep('steps', 'Translate report into reproduction steps', [], 'fast'),
      agentRunStep('reproduce', 'Attempt reproduction with browser evidence', ['steps']),
      summarizeStep('report', 'Produce support reproduction report', ['reproduce']),
    ],
    metadata: browserOperatorMetadata('test', 'support_product'),
  }),
  defineWorkflow({
    id: 'ship',
    slug: 'ship',
    version: '1.0.0',
    name: 'Ship',
    description: 'Run checks, confirm gates, summarize risk, and prepare a release handoff.',
    promise: 'Make shipping deliberate, auditable, and reversible.',
    triggerPhrases: ['ship this', 'prepare release', 'release gate'],
    defaultAgentRole: 'release lead',
    executionMode: 'dag',
    safetyMode: 'approval_gated',
    requiredCapabilities: ['advanced:agent-ops', 'advanced:release-gates', 'manage:orchestration', 'core:approvals'],
    inputFields: [
      field('target', 'Release target', 'branch'),
      field('deployUrl', 'Deploy URL', 'deploy', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['test_result', 'deploy_url', 'diff', 'approval', 'log_excerpt'],
    approvalGates: [
      { id: 'release-approval', label: 'Release approval', reason: 'Shipping can affect production users.', requiredFor: ['deploy', 'prod_write'] },
    ],
    evalPack: [
      { id: 'release-gates', label: 'Release gates', assertion: 'Ship workflow records checks, risks, approval state, and rollback guidance.', required: true },
    ],
    steps: [
      agentRunStep('checks', 'Run release checks', [], 'strong'),
      agentRunStep('risk', 'Summarize release risk and rollback', ['checks']),
      approvalStep('approval', 'Request release approval', ['risk']),
      summarizeStep('handoff', 'Create ship handoff', ['approval']),
    ],
    metadata: failureOwnershipMetadata,
  }),
  defineWorkflow({
    id: 'canary',
    slug: 'canary',
    version: '1.0.0',
    name: 'Canary',
    description: 'Monitor a deploy URL or release candidate for regressions, runtime errors, and perf anomalies.',
    promise: 'Catch release problems while the blast radius is still small.',
    triggerPhrases: ['canary this', 'monitor deploy', 'post-deploy check'],
    defaultAgentRole: 'canary monitor',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'advanced:browser-qa', 'advanced:release-gates', 'manage:orchestration', 'tool:browser'],
    inputFields: [field('deployUrl', 'Deploy URL', 'deploy')],
    outputSections: standardOutputSections,
    evidenceTypes: ['deploy_url', 'screenshot', 'console_log', 'network_log', 'perf_metric', 'trace'],
    approvalGates: [],
    evalPack: [
      { id: 'canary-signal', label: 'Canary signal', assertion: 'Canary workflow reports health, anomalies, evidence, and concrete rollback criteria.', required: true },
    ],
    steps: [
      agentRunStep('baseline', 'Capture baseline health', [], 'fast'),
      agentRunStep('probe', 'Probe user-critical paths', ['baseline']),
      agentRunStep('analyze', 'Analyze anomalies', ['probe']),
      summarizeStep('canary-report', 'Produce canary report', ['analyze']),
    ],
    metadata: failureOwnershipMetadata,
  }),
  defineWorkflow({
    id: 'retro',
    slug: 'retro',
    version: '1.0.0',
    name: 'Retro',
    description: 'Summarize what happened, what was learned, and what should become future memory or process.',
    promise: 'Turn a run, incident, or release into reusable learning.',
    triggerPhrases: ['run retro', 'retrospective', 'what did we learn'],
    defaultAgentRole: 'retrospective facilitator',
    executionMode: 'single_run',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'advanced:project-learnings', 'memory:project'],
    inputFields: [field('target', 'Run, release, or incident', 'text')],
    outputSections: standardOutputSections,
    evidenceTypes: ['transcript', 'memory_hit', 'log_excerpt'],
    approvalGates: [],
    evalPack: [
      { id: 'learning-capture', label: 'Learning capture', assertion: 'Retro output proposes project learnings with evidence and avoids unsafe instruction-like memory writes.', required: true },
    ],
    steps: [],
    metadata: failureOwnershipMetadata,
  }),
  defineWorkflow({
    id: 'cso',
    slug: 'cso',
    version: '1.0.0',
    name: 'CSO Review',
    description: 'Review a plan, release, or system for security posture, trust boundaries, and governance risk.',
    promise: 'Expose strategic security risks before the team commits.',
    triggerPhrases: ['cso review', 'security posture review'],
    defaultAgentRole: 'security officer',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'advanced:security-posture', 'manage:orchestration'],
    inputFields: [field('target', 'Target', 'text')],
    outputSections: standardOutputSections,
    evidenceTypes: ['review_finding', 'diff', 'log_excerpt', 'trace'],
    approvalGates: [],
    evalPack: [
      { id: 'no-vague-risk', label: 'No vague risk', assertion: 'Security posture review identifies concrete risks, controls, and owners instead of vague concerns.', required: true },
    ],
    steps: [
      agentRunStep('inventory', 'Inventory trust boundaries', [], 'fast'),
      agentRunStep('threats', 'Threat model critical paths', ['inventory']),
      agentRunStep('controls', 'Review controls and missing gates', ['threats']),
      summarizeStep('security-posture', 'Produce CSO review', ['controls']),
    ],
    metadata: {
      review_army: {
        mode: 'red_team',
        specialists: getReviewSpecialistsForMode('red_team').map((specialist) => specialist.slug),
      },
    },
  }),
  defineWorkflow({
    id: 'security-audit',
    slug: 'security-audit',
    version: '1.0.0',
    name: 'Security Audit',
    description: 'Audit code, configuration, dependencies, and AI trust boundaries for concrete security findings.',
    promise: 'Find exploitable risk with evidence and remediation.',
    triggerPhrases: ['security audit', 'audit this', 'threat model this'],
    defaultAgentRole: 'security auditor',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'advanced:security-posture', 'manage:orchestration', 'tool:repo.read'],
    inputFields: [field('target', 'Codebase, PR, or system', 'text')],
    outputSections: standardOutputSections,
    evidenceTypes: ['review_finding', 'diff', 'log_excerpt', 'trace', 'test_result'],
    approvalGates: [],
    evalPack: [
      { id: 'no-vague-risk', label: 'No vague risk', assertion: 'Security findings describe exploitability and remediation.', required: true },
    ],
    steps: [
      agentRunStep('surface', 'Map attack surface', [], 'fast'),
      agentRunStep('dependencies', 'Review dependencies and config', ['surface']),
      agentRunStep('trust', 'Review AI/runtime trust boundaries', ['surface']),
      summarizeStep('audit-report', 'Produce security audit', ['dependencies', 'trust']),
    ],
    metadata: {
      review_army: {
        mode: 'red_team',
        specialists: getReviewSpecialistsForMode('red_team').map((specialist) => specialist.slug),
      },
    },
  }),
  defineWorkflow({
    id: 'design-review',
    slug: 'design-review',
    version: '1.0.0',
    name: 'Design Review',
    description: 'Review a screen, flow, or design proposal for clarity, accessibility, polish, and product hierarchy.',
    promise: 'Make the UI feel intentional, usable, and shippable.',
    triggerPhrases: ['design review', 'review this ui', 'ux audit'],
    defaultAgentRole: 'design reviewer',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'advanced:browser-qa', 'manage:orchestration', 'tool:browser'],
    inputFields: [field('target', 'URL, screenshot, or design brief', 'text')],
    outputSections: standardOutputSections,
    evidenceTypes: ['screenshot', 'review_finding', 'perf_metric', 'design_rationale'],
    approvalGates: [],
    evalPack: [
      { id: 'visual-diff', label: 'Visual diff', assertion: 'Design review compares before/after evidence or clearly explains why visual diff was unavailable.', required: true },
      { id: 'accessibility-pass', label: 'Accessibility pass', assertion: 'Design review covers accessibility, hierarchy, responsive behavior, and copy clarity.', required: true },
    ],
    steps: [
      agentRunStep('capture', 'Capture current experience', [], 'fast'),
      agentRunStep('critique', 'Review UX and accessibility', ['capture']),
      summarizeStep('design-report', 'Produce design review', ['critique']),
    ],
    metadata: designOpsMetadata('review', 'product_ui'),
  }),
  defineWorkflow({
    id: 'design-to-code',
    slug: 'design-to-code',
    version: '1.0.0',
    name: 'Design To Code',
    description: 'Translate an approved visual direction into implementation guidance, acceptance checks, and code-ready constraints.',
    promise: 'Move from design intent to buildable instructions without losing the product feel.',
    triggerPhrases: ['design to code', 'implement design', 'turn this design into code'],
    defaultAgentRole: 'design implementation lead',
    executionMode: 'dag',
    safetyMode: 'approval_gated',
    requiredCapabilities: ['advanced:agent-ops', 'manage:orchestration', 'design:taste-profile', 'tool:repo.read', 'core:approvals'],
    inputFields: [
      field('target', 'Approved design or URL', 'text'),
      field('implementation_context', 'Implementation context', 'text', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['mockup', 'design_rationale', 'diff', 'screenshot', 'test_result'],
    approvalGates: [
      { id: 'implementation-approval', label: 'Implementation approval', reason: 'Design-to-code can change product surfaces and should preserve approved intent.', requiredFor: ['implementation'] },
    ],
    evalPack: [
      { id: 'intent-preserved', label: 'Intent preserved', assertion: 'Implementation guidance preserves hierarchy, interaction, accessibility, and brand intent.', required: true },
      { id: 'acceptance-checks', label: 'Acceptance checks', assertion: 'Output includes concrete visual QA checks and rollback risks.', required: true },
    ],
    steps: [
      agentRunStep('extract-intent', 'Extract design intent and constraints', [], 'fast'),
      agentRunStep('implementation-plan', 'Map design intent to implementation plan', ['extract-intent']),
      approvalStep('approve-implementation', 'Request design implementation approval', ['implementation-plan']),
      summarizeStep('handoff', 'Produce code-ready design handoff', ['approve-implementation']),
    ],
    metadata: designOpsMetadata('design_to_code', 'product_ui'),
  }),
  defineWorkflow({
    id: 'devex-audit',
    slug: 'devex-audit',
    version: '1.0.0',
    name: 'DevEx Audit',
    description: 'Audit onboarding, docs, commands, naming, local setup, and time-to-hello-world for a project or workflow.',
    promise: 'Make a system easier for humans and agents to understand and operate.',
    triggerPhrases: ['devex audit', 'dx audit', 'onboarding audit'],
    defaultAgentRole: 'developer experience auditor',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'manage:orchestration', 'tool:repo.read'],
    inputFields: [field('target', 'Project, repo, workflow, or docs surface', 'text')],
    outputSections: standardOutputSections,
    evidenceTypes: ['transcript', 'log_excerpt', 'review_finding', 'design_rationale'],
    approvalGates: [],
    evalPack: [
      { id: 'time-to-hello-world', label: 'Time to hello world', assertion: 'Audit identifies the fastest path to first successful use and what blocks it.', required: true },
      { id: 'agent-readable', label: 'Agent readable', assertion: 'Recommendations improve codebase and workflow clarity for human and agent operators.', required: true },
    ],
    steps: [
      agentRunStep('map-entrypoints', 'Map entrypoints and setup path', [], 'fast'),
      agentRunStep('audit-friction', 'Audit naming, docs, commands, and handoff friction', ['map-entrypoints']),
      summarizeStep('devex-report', 'Produce DevEx audit', ['audit-friction']),
    ],
    metadata: {
      devex: {
        checklist: ['time-to-hello-world', 'setup-clarity', 'naming', 'agent-readable-docs'],
      },
    },
  }),
  defineWorkflow({
    id: 'devex-review',
    slug: 'devex-review',
    version: '1.0.0',
    name: 'DevEx Review',
    description: 'Review a release, workflow, or docs change for onboarding clarity, command discoverability, naming, and agent-readable handoff quality.',
    promise: 'Catch confusing operator and developer experience before the change ships.',
    triggerPhrases: ['devex review', 'dx review', 'review devex'],
    defaultAgentRole: 'developer experience reviewer',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'manage:orchestration', 'advanced:product-quality', 'tool:repo.read'],
    inputFields: [
      field('target', 'Release, PR, workflow, or docs target', 'text'),
      field('audience', 'Audience', 'text', false, 'Developers, operators, marketers, sellers, customers, or agents.'),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['transcript', 'review_finding', 'screenshot', 'diff'],
    approvalGates: [],
    evalPack: [
      { id: 'operator-clarity', label: 'Operator clarity', assertion: 'Review explains what a human should click, run, or trust next.', required: true },
      { id: 'agent-readable-handoff', label: 'Agent-readable handoff', assertion: 'Findings improve future agent/runtime understanding without adding internal jargon.', required: true },
    ],
    steps: [
      agentRunStep('map-audience', 'Map audience and entrypoints', [], 'fast'),
      agentRunStep('review-friction', 'Review DevEx friction and operator copy', ['map-audience']),
      summarizeStep('devex-review', 'Produce DevEx review', ['review-friction']),
    ],
    metadata: {
      devex: {
        checklist: ['operator-clarity', 'command-discoverability', 'agent-readable-handoff'],
      },
      ...releaseQualityMetadata('devex-review', 'devex_review', ['ship', 'deploy']),
    },
  }),
  defineWorkflow({
    id: 'document-release',
    slug: 'document-release',
    version: '1.0.0',
    name: 'Document Release',
    description: 'Prepare release notes, docs, or handoff artifacts with evidence and publication checks.',
    promise: 'Make the release understandable and easy to hand off.',
    triggerPhrases: ['document release', 'write release notes', 'prepare docs'],
    defaultAgentRole: 'release writer',
    executionMode: 'dag',
    safetyMode: 'approval_gated',
    requiredCapabilities: ['advanced:agent-ops', 'manage:orchestration', 'advanced:release-gates', 'advanced:product-quality', 'core:approvals'],
    inputFields: [field('target', 'Release target', 'text')],
    outputSections: standardOutputSections,
    evidenceTypes: ['diff', 'deploy_url', 'transcript'],
    approvalGates: [
      { id: 'publish-approval', label: 'Publish approval', reason: 'External-facing release docs need review.', requiredFor: ['publish'] },
    ],
    evalPack: [
      { id: 'copy-paste-safe', label: 'Copy/paste safe', assertion: 'Release docs can be copied into the target surface without missing context or unsafe hidden assumptions.', required: true },
      { id: 'publication-gated', label: 'Publication gated', assertion: 'External-facing docs require publish approval before handoff.', required: true },
    ],
    steps: [
      agentRunStep('collect', 'Collect release context', [], 'fast'),
      agentRunStep('draft', 'Draft docs and release notes', ['collect']),
      approvalStep('approve', 'Request publish approval', ['draft']),
      summarizeStep('publish-handoff', 'Produce publication handoff', ['approve']),
    ],
    metadata: {
      ...releaseQualityMetadata('document-release', 'document_release', ['ship', 'deploy', 'promotion']),
      operating_loop: {
        checklist: [
          ...DOCUMENT_RELEASE_CHECKLIST.map((item) => item.id),
          ...getReleaseQualityChecksForWorkflow('document-release').map((check) => check.id),
        ],
      },
    },
  }),
  defineWorkflow({
    id: 'release-check',
    slug: 'release-check',
    version: '1.0.0',
    name: 'Release Check',
    description: 'Run the release-quality gate pack across docs, tests, screenshots, release notes, version metadata, PR title, and deploy readiness.',
    promise: 'Know whether a release is actually ready to ship.',
    triggerPhrases: ['release check', 'release readiness', 'pre ship check'],
    defaultAgentRole: 'release quality lead',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'manage:orchestration', 'advanced:release-gates', 'advanced:product-quality', 'tool:repo.read'],
    inputFields: [
      field('target', 'Release target', 'text'),
      field('deploy_url', 'Deploy or preview URL', 'url', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['diff', 'test_result', 'screenshot', 'deploy_url', 'transcript', 'review_finding'],
    approvalGates: [],
    evalPack: [
      { id: 'quality-gates-complete', label: 'Quality gates complete', assertion: 'Output reports every required release-quality gate with evidence or an explicit non-applicable reason.', required: true },
      { id: 'ship-risk-clear', label: 'Ship risk clear', assertion: 'Output separates blockers, warnings, and safe-to-ship notes.', required: true },
    ],
    steps: [
      agentRunStep('collect-release-scope', 'Collect diff, docs, test, deploy, and release-note scope', [], 'fast'),
      agentRunStep('run-quality-gates', 'Run release-quality gate pack', ['collect-release-scope']),
      agentRunStep('assess-ship-risk', 'Assess ship/deploy/promotion risk', ['run-quality-gates']),
      summarizeStep('release-readiness', 'Produce release readiness report', ['assess-ship-risk']),
    ],
    metadata: releaseQualityMetadata('release-check', 'release_check', ['ship', 'deploy', 'promotion']),
  }),
  defineWorkflow({
    id: 'version-gate',
    slug: 'version-gate',
    version: '1.0.0',
    name: 'Version Gate',
    description: 'Check package/version/changelog/migration consistency before deploy or promotion.',
    promise: 'Prevent version and changelog drift from reaching production.',
    triggerPhrases: ['version gate', 'check version', 'version check'],
    defaultAgentRole: 'release version reviewer',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'manage:orchestration', 'advanced:release-gates', 'advanced:product-quality', 'tool:repo.read'],
    inputFields: [field('target', 'Release branch, PR, or package', 'text')],
    outputSections: standardOutputSections,
    evidenceTypes: ['diff', 'test_result', 'review_finding', 'transcript'],
    approvalGates: [],
    evalPack: [
      { id: 'version-consistency', label: 'Version consistency', assertion: 'Version, changelog, release note, and migration state agree.', required: true },
    ],
    steps: [
      agentRunStep('read-version-state', 'Read version, package, changelog, and migration state', [], 'fast'),
      agentRunStep('compare-release-scope', 'Compare version state to release scope', ['read-version-state']),
      summarizeStep('version-report', 'Produce version gate report', ['compare-release-scope']),
    ],
    metadata: releaseQualityMetadata('version-gate', 'version_gate', ['deploy', 'promotion']),
  }),
  defineWorkflow({
    id: 'pr-title-sync',
    slug: 'pr-title-sync',
    version: '1.0.0',
    name: 'PR Title Sync',
    description: 'Compare PR title, summary, release notes, and diff scope, then propose or approval-gate a synchronized title.',
    promise: 'Make PR and release wording describe the actual shipped change.',
    triggerPhrases: ['pr title sync', 'sync pr title', 'title check'],
    defaultAgentRole: 'release copy reviewer',
    executionMode: 'dag',
    safetyMode: 'approval_gated',
    requiredCapabilities: ['advanced:agent-ops', 'manage:orchestration', 'advanced:product-quality', 'core:approvals', 'tool:repo.read'],
    inputFields: [field('target', 'Pull request or release note', 'pull_request')],
    outputSections: standardOutputSections,
    evidenceTypes: ['diff', 'transcript', 'approval'],
    approvalGates: [
      { id: 'title-sync-approval', label: 'Title sync approval', reason: 'Changing public PR/release wording should be approved.', requiredFor: ['update-title'] },
    ],
    evalPack: [
      { id: 'title-matches-scope', label: 'Title matches scope', assertion: 'Recommended title accurately reflects diff, risks, and user-visible scope.', required: true },
    ],
    steps: [
      agentRunStep('compare-title-scope', 'Compare title, summary, release notes, and diff', [], 'fast'),
      agentRunStep('propose-title', 'Propose synchronized wording', ['compare-title-scope']),
      approvalStep('approve-title-sync', 'Request title sync approval', ['propose-title']),
      summarizeStep('title-sync-report', 'Produce title sync report', ['approve-title-sync']),
    ],
    metadata: releaseQualityMetadata('pr-title-sync', 'pr_title_sync', ['ship']),
  }),
  defineWorkflow({
    id: 'product-quality-lint',
    slug: 'product-quality-lint',
    version: '1.0.0',
    name: 'Product Quality Lint',
    description: 'Scan docs, release notes, UI copy, screenshots, and handoff text for jargon, AI slop, missing visual evidence, and unclear promises.',
    promise: 'Make product-facing output clear, specific, and evidence-backed.',
    triggerPhrases: ['product quality lint', 'quality lint', 'slop scan', 'jargon scan'],
    defaultAgentRole: 'product quality reviewer',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'manage:orchestration', 'advanced:product-quality'],
    inputFields: [
      field('target', 'Copy, page, PR, release note, or artifact', 'text'),
      field('audience', 'Audience', 'text', false),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['transcript', 'review_finding', 'screenshot'],
    approvalGates: [],
    evalPack: [
      { id: 'plain-language', label: 'Plain language', assertion: 'Findings identify vague, generic, or jargon-heavy copy and propose clearer alternatives.', required: true },
      { id: 'evidence-backed-quality', label: 'Evidence-backed quality', assertion: 'Quality claims cite concrete text, screenshot, or artifact evidence.', required: true },
    ],
    steps: [
      agentRunStep('collect-copy', 'Collect product-facing text and evidence', [], 'fast'),
      agentRunStep('lint-quality', 'Run jargon, AI slop, screenshot, and promise checks', ['collect-copy']),
      summarizeStep('quality-report', 'Produce product quality report', ['lint-quality']),
    ],
    metadata: releaseQualityMetadata('product-quality-lint', 'product_quality_lint', ['ship', 'deploy']),
  }),
  defineWorkflow({
    id: 'model-benchmark',
    slug: 'model-benchmark',
    version: '1.0.0',
    name: 'Model Benchmark',
    description: 'Compare one or more model/provider choices against the same Agent Ops scenario pack.',
    promise: 'Pick the best model, runtime, channel, memory mode, or Browser Procedure path with evidence, not folklore.',
    triggerPhrases: ['benchmark model', 'compare models', 'model eval', 'benchmark runtime', 'benchmark browser procedure'],
    defaultAgentRole: 'eval lead',
    executionMode: 'dag',
    safetyMode: 'read_only',
    requiredCapabilities: ['advanced:agent-ops', 'advanced:eval-center', 'manage:orchestration'],
    inputFields: [
      field('scenario', 'Scenario', 'text'),
      field('models', 'Models to compare', 'text'),
      field('runtime_profiles', 'Runtime profiles', 'text', false, 'Comma-separated runtime profiles such as shared, c1_managed, c2a_autonomous.'),
      field('channels', 'Channels', 'text', false, 'Comma-separated channel surfaces such as web, Slack, Discord, Telegram.'),
      field('memory_modes', 'Memory modes', 'text', false, 'Comma-separated modes: off, recent, semantic, project.'),
      field('browser_modes', 'Browser modes', 'text', false, 'generic_browser_operator, browser_procedure, or both.'),
    ],
    outputSections: standardOutputSections,
    evidenceTypes: ['model_benchmark', 'transcript', 'perf_metric'],
    approvalGates: [],
    evalPack: [
      { id: 'instruction-following', label: 'Instruction following', assertion: 'Model follows workflow instructions without inventing unsupported capabilities.', required: true },
      { id: 'structured-output', label: 'Structured output', assertion: 'Model returns the standard Agent Ops output sections in a parseable shape.', required: true },
      { id: 'latency-cost-fit', label: 'Latency/cost fit', assertion: 'Model recommendation includes quality, latency, token, and cost tradeoffs.', required: true },
      { id: 'evidence-completeness', label: 'Evidence completeness', assertion: 'Benchmark output tracks evidence completeness, failure type, latency, cost, and token count for each candidate.', required: true },
      { id: 'procedure-quality-lift', label: 'Procedure quality lift', assertion: 'Browser Procedure candidates are compared against generic Browser Operator candidates when browser modes are supplied.', required: true },
    ],
    steps: [
      agentRunStep('prepare', 'Prepare benchmark scenario', [], 'fast'),
      agentRunStep('run-candidates', 'Run candidate models through the scenario', ['prepare']),
      agentRunStep('score', 'Score quality, cost, latency, and tool discipline', ['run-candidates']),
      summarizeStep('recommendation', 'Produce model recommendation', ['score']),
    ],
    metadata: {
      eval_center: {
        pack_kind: 'model_benchmark',
        target_kind: 'model_runtime_channel_memory_browser',
        benchmark_matrix: buildAgentOpsBenchmarkMatrix({
          workflowId: 'model-benchmark',
          scenario: 'default',
          models: ['default'],
          runtimeProfiles: ['shared', 'c1_managed', 'c2a_autonomous'],
          channels: ['web', 'slack', 'discord', 'telegram'],
          memoryModes: ['off', 'recent', 'semantic', 'project'],
          browserModes: ['generic_browser_operator', 'browser_procedure'],
        }),
      },
    },
  }),
] satisfies readonly AgentOpsWorkflowDefinition[])

const workflowById = new Map<AgentOpsWorkflowId, AgentOpsWorkflowDefinition>(
  AGENT_OPS_WORKFLOWS.map((workflow) => [workflow.id, workflow]),
)

const workflowBySlug = new Map<string, AgentOpsWorkflowDefinition>(
  AGENT_OPS_WORKFLOWS.map((workflow) => [workflow.slug, workflow]),
)

export function listAgentOpsWorkflows(): readonly AgentOpsWorkflowDefinition[] {
  return AGENT_OPS_WORKFLOWS
}

export function getAgentOpsWorkflow(id: AgentOpsWorkflowId): AgentOpsWorkflowDefinition {
  const workflow = workflowById.get(id)
  if (!workflow) {
    throw new Error(`Unknown Agent Ops workflow: ${id}`)
  }
  return workflow
}

export function findAgentOpsWorkflowBySlug(slug: string): AgentOpsWorkflowDefinition | null {
  return workflowBySlug.get(slug) ?? null
}

export function isDagBackedWorkflow(workflow: AgentOpsWorkflowDefinition): boolean {
  return workflow.executionMode === 'dag'
}
