import type { AuditArtifact, AuditCommandResult, AuditFinding, AuditRunReport, AuditScope } from './audit-types'
import { findingCounts, writeJson, writeMarkdown } from './audit-utils'

export async function writeAuditReport(root: string, params: {
  branch: string
  commit: string
  scope: AuditScope
  strict: boolean
  findings: AuditFinding[]
  artifacts: AuditArtifact[]
  commands: AuditCommandResult[]
  markdownPath: string
  jsonPath: string
}): Promise<AuditRunReport> {
  const report: AuditRunReport = {
    generatedAt: new Date().toISOString(),
    branch: params.branch,
    commit: params.commit,
    scope: params.scope,
    strict: params.strict,
    findings: params.findings,
    artifacts: params.artifacts,
    commands: params.commands,
    summary: {
      findingCounts: findingCounts(params.findings),
      artifactCount: params.artifacts.length,
      commandCount: params.commands.length,
      failedCommandCount: params.commands.filter((command) => !command.ok).length,
    },
  }

  await writeJson(root, params.jsonPath, report)
  await writeMarkdown(root, params.markdownPath, renderMarkdown(report))
  return report
}

function renderMarkdown(report: AuditRunReport): string {
  const lines: string[] = [
    '# Whole-Codebase Audit Report',
    '',
    `- Generated: ${report.generatedAt}`,
    `- Branch: \`${report.branch}\``,
    `- Commit: \`${report.commit}\``,
    `- Scope: \`${report.scope}\``,
    `- Strict: \`${String(report.strict)}\``,
    '',
    '## Summary',
    '',
    `- Findings: P0=${report.summary.findingCounts.P0}, P1=${report.summary.findingCounts.P1}, P2=${report.summary.findingCounts.P2}, P3=${report.summary.findingCounts.P3}`,
    `- Artifacts: ${report.summary.artifactCount}`,
    `- Commands: ${report.summary.commandCount}`,
    `- Failed commands: ${report.summary.failedCommandCount}`,
    '',
    '## Findings',
    '',
  ]

  if (report.findings.length === 0) {
    lines.push('No findings generated by this audit pass.', '')
  } else {
    for (const finding of report.findings.sort(sortFindings)) {
      const location = finding.file ? `${finding.file}${finding.line ? `:${finding.line}` : ''}` : 'n/a'
      lines.push(
        `### ${finding.severity} ${finding.title}`,
        '',
        `- ID: \`${finding.id}\``,
        `- Subsystem: \`${finding.subsystem}\``,
        `- Location: \`${location}\``,
        `- Status: \`${finding.status}\``,
        `- Risk: ${finding.risk}`,
        `- Recommendation: ${finding.recommendation}`,
        '',
      )
    }
  }

  lines.push('## Artifacts', '')
  for (const artifact of report.artifacts) {
    lines.push(`- \`${artifact.path}\` - ${artifact.summary}`)
  }

  lines.push('', '## Commands', '')
  for (const command of report.commands) {
    const state = command.skipped ? 'skipped' : command.ok ? 'passed' : 'failed'
    lines.push(`- \`${command.command}\` - ${state} (${command.durationMs}ms)${command.reason ? `: ${command.reason}` : ''}`)
  }

  return lines.join('\n')
}

function sortFindings(a: AuditFinding, b: AuditFinding): number {
  const order = { P0: 0, P1: 1, P2: 2, P3: 3 }
  return order[a.severity] - order[b.severity] || a.subsystem.localeCompare(b.subsystem) || a.title.localeCompare(b.title)
}
