/**
 * DAG Planner Foundation — End-to-End Test (Phase 4N-a, Task 33)
 *
 * Exercises the full plan_dag → planner → scheduler pipeline with a
 * 4-node linear template (research → draft → approval → deliver).
 *
 * What this test pins:
 *   1. `toolPlanDag` successfully loads a template by slug, instantiates
 *      the DAG, and fires `scheduler.onDagCreated` to promote roots.
 *   2. Each `scheduler.onNodeComplete` call walks the chain one step
 *      forward: it stamps the node complete, promotes the next child
 *      via the CTE RPC, and bumps the dag's completed counter.
 *   3. When the last node completes, the dag row transitions to
 *      `status = 'completed'`.
 *
 * The test uses a stateful mock Supabase harness that:
 *   - Serves the template-loader SELECT chain from a canned row
 *   - Captures planner INSERTs and remembers generated node UUIDs
 *      keyed by node_key (so the test can drive completions in order)
 *   - Scripts RPC responses (`dag_promote_roots`, `dag_complete_node`,
 *     `dag_bump_completed`) to walk the 4-node chain deterministically
 *   - Records UPDATE calls on `orchestration_dags` so we can assert the
 *     final `status = 'completed'` transition
 */

import { describe, it, expect, vi } from 'vitest'
import { toolPlanDag } from '../../../agent/runtime-tools/dag-plan.js'
import { IncrementalScheduler } from '../scheduler.js'
import { DagStepCreator } from '../dag-step-creator.js'
import type { DagSpec } from '../types.js'

const ORG_ID = '22222222-2222-4222-8222-222222222222'
const AGENT_ID = '11111111-1111-4111-8111-111111111111'
const TEMPLATE_ID = '33333333-3333-4333-8333-333333333333'

const FOUR_NODE_SPEC: DagSpec = {
  nodes: [
    { node_key: 'research', node_type: 'leaf', step_type: 'inbound' },
    { node_key: 'draft', node_type: 'leaf', step_type: 'outbound' },
    { node_key: 'approval', node_type: 'leaf', step_type: 'approval' },
    { node_key: 'deliver', node_type: 'leaf', step_type: 'outbound' },
  ],
  edges: [
    { parent: 'research', child: 'draft' },
    { parent: 'draft', child: 'approval' },
    { parent: 'approval', child: 'deliver' },
  ],
}

const TEMPLATE_ROW = {
  id: TEMPLATE_ID,
  org_id: ORG_ID,
  slug: 'content-pipeline',
  name: 'Content Pipeline',
  version: 1,
  spec: FOUR_NODE_SPEC,
  schema_version: 1,
  trigger_intents: null,
  mission_type: null,
  is_active: true,
}

interface Harness {
  supabase: any
  /** Map node_key → UUID generated by the planner (captured from INSERT). */
  nodeIdsByKey: Map<string, string>
  /** Capture of every `.update()` payload on orchestration_dags. */
  dagUpdates: Array<Record<string, unknown>>
  /** Capture of every `.update()` payload on orchestration_dag_nodes. */
  nodeStamps: Array<{ nodeId: string; payload: Record<string, unknown> }>
  /** Capture of every rpc() call so we can assert contract args. */
  rpcCalls: Array<{ name: string; args: Record<string, unknown> | undefined }>
}

/**
 * Builds a stateful mock Supabase client that supports:
 *   - Template loader SELECT chain → returns TEMPLATE_ROW
 *   - DagPlanner INSERTs (dag, nodes, edges) → capture node UUIDs
 *   - Scheduler SELECT loadDagHeader → returns captured dag header
 *   - Scheduler UPDATE orchestration_dags / orchestration_dag_nodes → capture
 *   - RPC dag_promote_roots / dag_complete_node / dag_bump_completed → scripted
 *
 * The scripted RPC responses walk the linear 4-node chain in order.
 */
function buildHarness(): Harness {
  const nodeIdsByKey = new Map<string, string>()
  const dagUpdates: Array<Record<string, unknown>> = []
  const nodeStamps: Array<{ nodeId: string; payload: Record<string, unknown> }> = []
  const rpcCalls: Array<{ name: string; args: Record<string, unknown> | undefined }> = []

  let capturedDagId: string | null = null
  let completedCount = 0
  // Tracks the dag's lifecycle so loadDagHeader reflects the current
  // state — once `bumpCompletedCounter` writes status='completed', the
  // header must say so or a stray onNodeComplete would advance again.
  let currentStatus: 'running' | 'completed' | 'failed' | 'cancelled' = 'running'
  const chain: string[] = ['research', 'draft', 'approval', 'deliver']

  const promotedRow = (key: string) => ({
    id: nodeIdsByKey.get(key),
    node_key: key,
    node_type: 'leaf',
    step_type: FOUR_NODE_SPEC.nodes.find((n) => n.node_key === key)!.step_type,
    runtime_target: null,
    route_class: null,
  })

  const dagHeader = () => ({
    id: capturedDagId,
    org_id: ORG_ID,
    agent_id: AGENT_ID,
    root_event_id: null,
    status: currentStatus,
    total_nodes: 4,
    completed_nodes: completedCount,
    failed_nodes: 0,
  })

  const from = vi.fn((table: string) => {
    if (table === 'orchestration_dag_templates') {
      // Template loader chain: select → eq → eq → or → order → limit → maybeSingle
      const maybeSingle = vi.fn(async () => ({ data: TEMPLATE_ROW, error: null }))
      const limit = vi.fn(() => ({ maybeSingle }))
      const order = vi.fn(() => ({ limit, maybeSingle }))
      const or = vi.fn(() => ({
        order,
        eq: vi.fn(() => ({ maybeSingle })),
      }))
      const eqIsActive = vi.fn(() => ({ or }))
      const eqSlug = vi.fn(() => ({ eq: eqIsActive }))
      const select = vi.fn(() => ({ eq: eqSlug }))
      return { select }
    }

    if (table === 'orchestration_dags') {
      return {
        insert: vi.fn(async (row: Record<string, unknown>) => {
          capturedDagId = row.id as string
          return { error: null }
        }),
        select: vi.fn(() => ({
          eq: vi.fn(() => ({
            maybeSingle: vi.fn(async () => ({ data: dagHeader(), error: null })),
          })),
        })),
        update: vi.fn((payload: Record<string, unknown>) => {
          dagUpdates.push(payload)
          // Mirror status transitions into the loadDagHeader source so
          // band-guard logic in the scheduler observes the real lifecycle.
          const nextStatus = payload.status as typeof currentStatus | undefined
          if (
            nextStatus === 'running' ||
            nextStatus === 'completed' ||
            nextStatus === 'failed' ||
            nextStatus === 'cancelled'
          ) {
            currentStatus = nextStatus
          }
          return {
            eq: vi.fn(async () => ({ error: null })),
          }
        }),
        delete: vi.fn(() => ({ eq: vi.fn(async () => ({ error: null })) })),
      }
    }

    if (table === 'orchestration_dag_nodes') {
      return {
        insert: vi.fn(async (rows: Record<string, unknown>[]) => {
          for (const row of rows) {
            nodeIdsByKey.set(row.node_key as string, row.id as string)
          }
          return { error: null }
        }),
        update: vi.fn((payload: Record<string, unknown>) => ({
          eq: vi.fn((_col: string, nodeId: string) => ({
            eq: vi.fn(() => {
              // Support both legacy `.update().eq().eq()` (awaitable) and
              // atomic claim `.update().eq().eq().neq().select()` used by
              // onNodeComplete's Blocker #1 idempotency gate.
              nodeStamps.push({ nodeId, payload })
              const leaf: any = Promise.resolve({ error: null })
              leaf.neq = vi.fn(() => ({
                select: vi.fn(async () => ({
                  data: [{ id: nodeId }],
                  error: null,
                })),
              }))
              return leaf
            }),
          })),
        })),
        delete: vi.fn(() => ({ eq: vi.fn(async () => ({ error: null })) })),
      }
    }

    if (table === 'orchestration_dag_edges') {
      return {
        insert: vi.fn(async () => ({ error: null })),
        delete: vi.fn(() => ({ eq: vi.fn(async () => ({ error: null })) })),
      }
    }

    throw new Error(`[e2e harness] unexpected table: ${table}`)
  })

  const rpc = vi.fn(async (name: string, args?: Record<string, unknown>) => {
    rpcCalls.push({ name, args })
    if (name === 'dag_promote_roots') {
      // Linear chain: only the first node (research) is a root
      return { data: [promotedRow('research')], error: null }
    }
    if (name === 'dag_complete_node') {
      // Walk the chain: after completing research → promote draft, etc.
      // `completedCount` is bumped by dag_bump_completed after this, so
      // we key off the current value to decide which child to promote.
      const nextIdx = completedCount + 1
      if (nextIdx < chain.length) {
        return { data: [promotedRow(chain[nextIdx])], error: null }
      }
      return { data: [], error: null }
    }
    if (name === 'dag_bump_completed') {
      completedCount += 1
      return {
        data: { completed_nodes: completedCount, total_nodes: 4 },
        error: null,
      }
    }
    return { data: null, error: null }
  })

  return {
    supabase: { from, rpc } as any,
    nodeIdsByKey,
    dagUpdates,
    nodeStamps,
    rpcCalls,
  }
}

describe('DAG Planner Foundation — E2E (4-node linear template)', () => {
  it('plan_dag + 4 onNodeComplete walks the chain and finalizes the DAG', async () => {
    const harness = buildHarness()
    const { supabase, nodeIdsByKey, dagUpdates, nodeStamps, rpcCalls } = harness

    const scheduler = new IncrementalScheduler(
      supabase,
      new DagStepCreator(supabase),
    )

    // Spy out enqueuePromoted's DagStepCreator.create so the test does
    // not hit the real orchestration_steps code path.
    const createSpy = vi
      .spyOn(DagStepCreator.prototype, 'create')
      .mockResolvedValue({ stepId: 'mock-step', isNew: true } as any)

    // ------------- 1. plan_dag -----------------------------------------
    const result = await toolPlanDag(
      { template_slug: 'content-pipeline' },
      { supabase, assistantId: AGENT_ID, orgId: ORG_ID, scheduler },
    )

    const envelope = JSON.parse(result) as {
      dag_id?: string
      total_nodes?: number
      root_node_ids?: string[]
      error?: string
    }
    expect(envelope.error).toBeUndefined()
    expect(envelope.total_nodes).toBe(4)
    expect(envelope.root_node_ids).toHaveLength(1)

    // scheduler.onDagCreated should have flipped the dag to 'running'
    const runningUpdate = dagUpdates.find((u) => u.status === 'running')
    expect(runningUpdate).toBeDefined()

    // The planner populated our nodeId map
    expect(nodeIdsByKey.get('research')).toBeDefined()
    expect(nodeIdsByKey.get('draft')).toBeDefined()
    expect(nodeIdsByKey.get('approval')).toBeDefined()
    expect(nodeIdsByKey.get('deliver')).toBeDefined()

    // Root (research) was enqueued as a leaf step
    expect(createSpy).toHaveBeenCalledTimes(1)

    const dagId = envelope.dag_id!

    // ------------- 2. Walk completions one at a time -------------------
    await scheduler.onNodeComplete(dagId, nodeIdsByKey.get('research')!)
    // research complete → draft promoted → 2 creates total
    expect(createSpy).toHaveBeenCalledTimes(2)

    await scheduler.onNodeComplete(dagId, nodeIdsByKey.get('draft')!)
    expect(createSpy).toHaveBeenCalledTimes(3)

    await scheduler.onNodeComplete(dagId, nodeIdsByKey.get('approval')!)
    expect(createSpy).toHaveBeenCalledTimes(4)

    await scheduler.onNodeComplete(dagId, nodeIdsByKey.get('deliver')!)
    // Final completion: dag_complete_node returns [] (no more children),
    // no new step is enqueued
    expect(createSpy).toHaveBeenCalledTimes(4)

    // ------------- 3. Final dag status = completed ---------------------
    const completedUpdate = dagUpdates.find((u) => u.status === 'completed')
    expect(completedUpdate).toBeDefined()

    // ------------- 4. RPC contract assertions --------------------------
    // dag_promote_roots called once with the captured dagId
    const promoteCalls = rpcCalls.filter((c) => c.name === 'dag_promote_roots')
    expect(promoteCalls).toHaveLength(1)
    expect(promoteCalls[0]!.args).toEqual({ p_dag_id: dagId })

    // dag_complete_node called 4× — once per node, with matching node ids
    const completeCalls = rpcCalls.filter((c) => c.name === 'dag_complete_node')
    expect(completeCalls).toHaveLength(4)
    expect(completeCalls.map((c) => c.args)).toEqual([
      { p_dag_id: dagId, p_node_id: nodeIdsByKey.get('research') },
      { p_dag_id: dagId, p_node_id: nodeIdsByKey.get('draft') },
      { p_dag_id: dagId, p_node_id: nodeIdsByKey.get('approval') },
      { p_dag_id: dagId, p_node_id: nodeIdsByKey.get('deliver') },
    ])

    // dag_bump_completed called 4× — once per completion, all with dagId
    const bumpCalls = rpcCalls.filter((c) => c.name === 'dag_bump_completed')
    expect(bumpCalls).toHaveLength(4)
    expect(bumpCalls.every((c) => c.args?.p_dag_id === dagId)).toBe(true)

    // ------------- 5. Node stamp assertions ----------------------------
    // Every node should have been stamped status='completed' exactly once,
    // in chain order, before its corresponding dag_complete_node RPC fired.
    // (The scheduler also stamps `confidence_observed` + `confidence_source`
    // on every admitted node via the Phase 4N-d confidence gate — filter
    // those out for this assertion.)
    const completionStamps = nodeStamps.filter(
      (s) => s.payload.status === 'completed',
    )
    expect(completionStamps).toHaveLength(4)
    expect(
      completionStamps.map((s) => ({
        nodeId: s.nodeId,
        status: s.payload.status,
      })),
    ).toEqual([
      { nodeId: nodeIdsByKey.get('research'), status: 'completed' },
      { nodeId: nodeIdsByKey.get('draft'), status: 'completed' },
      { nodeId: nodeIdsByKey.get('approval'), status: 'completed' },
      { nodeId: nodeIdsByKey.get('deliver'), status: 'completed' },
    ])
    // Each stamp also carries a completed_at timestamp
    for (const stamp of completionStamps) {
      expect(stamp.payload.completed_at).toEqual(expect.any(String))
    }

    createSpy.mockRestore()
  })

  it('returns structured error envelope when template slug is missing', async () => {
    const { supabase } = buildHarness()
    const scheduler = new IncrementalScheduler(supabase, new DagStepCreator(supabase))

    const result = await toolPlanDag(
      { template_slug: '' },
      { supabase, assistantId: AGENT_ID, orgId: ORG_ID, scheduler },
    )
    const envelope = JSON.parse(result)
    expect(envelope.error).toContain('template_slug is required')
  })
})
