/**
 * Built-in Skills — Platform-owned prompt guidance.
 *
 * Two categories:
 * 1. Internal skills — reference private tools, stay here permanently
 * 2. Generic skills — workflow/safety, will migrate to lucid-plugins/ eventually
 *
 * Tool awareness (when to use each tool) is NO LONGER HERE.
 * That's auto-generated by buildToolPrompt() from enriched CommandsAllowlist metadata.
 * Skills only contain workflow discipline and safety rules.
 */

import type { ActiveSkillRow } from './types.js'
import {
  buildInstalledIntegrationContent,
  type IntegrationPluginRef,
} from './integration-loader.js'

/** Minimal assistant config for conditional loading */
interface AssistantSkillConfig {
  wallet_enabled?: boolean
  trading_enabled?: boolean
  disable_builtin_skills?: boolean
  /**
   * Plugins activated on this assistant. Only entries with `kind: 'integration'`
   * are inspected — used to load only the integration patterns the agent can
   * actually act on, instead of every provider in the catalog.
   */
  plugins?: ReadonlyArray<IntegrationPluginRef>
}

// ── Internal skills (stay permanently — reference private tools) ─────

const swapDirectionSkill = {
  slug: 'lucid-swap-direction',
  name: 'Swap Direction Safety',
  description: 'Prevents agent from confusing input/output tokens in swaps',
  content: `# Swap Direction (CRITICAL — MUST FOLLOW)

## Input vs Output
When swapping token A to token B (e.g. "swap SOL to USDC"):
- inputToken = A (what you are SELLING — you need balance of THIS token)
- outputToken = B (what you are RECEIVING — you do NOT need balance of this token)
- Check balance of the INPUT token ONLY. Never check the output token balance.
- NEVER refuse a swap because the output token balance is zero or low. You are BUYING it, not spending it.

## Gas Fees — Chain-Specific
- Solana: gas is paid in SOL (typically < 0.001 SOL). NEVER say "insufficient USDC/stablecoin for gas" on Solana.
- Ethereum/EVM: gas is paid in the native token (ETH, MATIC, etc.), NOT in stablecoins.
- Gas fees are NEVER paid in USDC, USDT, or any stablecoin on any chain.

## Common Mistakes to Avoid
- Do NOT say "you need USDC to cover gas fees" — this is always wrong
- Do NOT say "low stablecoin runway" as a reason to block a swap
- Do NOT confuse "I have 0 USDC" with "I can't pay fees" — fees are paid in native tokens
- If the user has enough of the INPUT token and enough native token for gas, the swap can proceed`,
}

const crossChainFundingSkill = {
  slug: 'lucid-cross-chain-funding',
  name: 'Cross-Chain Funding & Bridging',
  description: 'Guides agent to use bridge, hl_deposit, and hl_withdraw for cross-chain fund movement',
  content: `# Cross-Chain Funding Guide

## When Funds Are on the Wrong Chain

Agents may have wallets on multiple chains (Solana + EVM). Some destinations require specific chains:
- **Hyperliquid**: Only accepts USDC on Arbitrum. Use hl_deposit after bridging.
- **Polymarket**: Only accepts USDC on Polygon. Funded via Polymarket Bridge API.
- **DEX swaps**: Each chain has its own DEX (Jupiter on Solana, 1inch on EVM).

## The bridge Tool (DeBridge)

Use \`bridge\` to move tokens between chains. It supports Solana ↔ EVM and EVM ↔ EVM.
- Requires **contract addresses** (not symbols). Common USDC addresses:
  - Solana: EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v
  - Arbitrum: 0xaf88d065e77c8cC2239327C5EDb3A432268e5831
  - Ethereum: 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
  - Polygon: 0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174
- Takes 1-5 minutes depending on chains
- Do NOT use bridge for same-chain transfers — use dex_swap instead

## Hyperliquid Funding

Hyperliquid is an Arbitrum-based perps exchange. Funds must be deposited before trading:

1. **Check HL balance**: hl_account_info — if $0, deposit needed
2. **Check Arbitrum wallet**: wallet_balance — if has USDC on Arbitrum, use hl_deposit directly
3. **Funds on Solana only**: bridge (Solana → Arbitrum) then hl_deposit
4. **Withdraw from HL**: hl_withdraw sends USDC back to Arbitrum wallet
5. **Return to Solana**: hl_withdraw then bridge (Arbitrum → Solana)

## CRITICAL RULES
- NEVER say "I can't trade on Hyperliquid because funds are on Solana" — use bridge + hl_deposit
- NEVER skip the deposit step — Hyperliquid cannot use Arbitrum wallet USDC directly, it must be deposited via hl_deposit
- NEVER attempt to deposit non-USDC tokens to Hyperliquid — swap to USDC first
- After bridging, ALWAYS verify arrival with wallet_balance before proceeding
- After depositing to HL, ALWAYS verify with hl_account_info before placing orders
- Minimum deposit/withdrawal: 5 USDC`,
}

const swapExecutionSkill = {
  slug: 'lucid-swap-execution',
  name: 'Swap Execution Workflow',
  description: 'Mandatory swap execution workflow — risk check then execute',
  content: `# Swap Execution Workflow (MANDATORY)

When the user asks to swap/trade/buy/sell tokens, follow this EXACT workflow:

## Step 0: Route to the Right Tool
- If the user mentions **Hyperliquid / HL** → use hl_place_order (NOT dex_swap). HL is a perps exchange, not a DEX. Check hl_account_info first — if balance is $0, deposit via hl_deposit (bridge from Solana first if needed).
- If the user mentions **Polymarket / predictions** → use polymarket_trade (NOT dex_swap).
- Otherwise → proceed with the DEX swap workflow below.

## DEX Swap Workflow
1. **Get balance** — call wallet_balance to check the INPUT token balance
2. **Calculate amount** — if user says "10% of SOL", compute 10% of the SOL balance
3. **Get quote** — call dex_get_quote with the computed amount
4. **Risk check** — call risk_check with inputToken, outputToken, amountUsd, chain
5. **Execute** — if risk_check returns level "low" or "medium" with recommendation "proceed":
   → IMMEDIATELY call dex_swap. Do NOT ask for confirmation. Do NOT add warnings. Just execute.
   → If recommendation is "review" (high risk): present the risks and ask the user to confirm
   → If recommendation is "abort" (critical): refuse and explain why

## CRITICAL RULES
- When risk_check says "proceed", you MUST call dex_swap. No exceptions.
- Do NOT add your own risk assessment on top of risk_check. The risk_check tool already evaluates everything.
- Do NOT refuse a swap because the amount is "small" or "not worth it" — the user decides that.
- Do NOT refuse because "stablecoin runway is low" — Solana gas is paid in SOL, not stablecoins.
- Do NOT tell the user to "use Jupiter directly" or "check a DEX" — YOU are the DEX interface.
- The trading policy guard (inside dex_swap) will block disallowed trades automatically. You don't need to pre-check.

## AFTER EXECUTION
- ALWAYS include the **transaction hash** from the dex_swap result in your response.
- ALWAYS include the amount received and the token pair (e.g. "Swapped 0.01 SOL → 0.857 USDC").
- Provide a block explorer link: \`https://solscan.io/tx/{txHash}\` for Solana, \`https://etherscan.io/tx/{txHash}\` for Ethereum.
- Keep it concise — no lengthy explanations after a successful swap.

## Trading Policy
When the user asks about trading limits, allowed chains, daily usage, or trading settings, use the get_trading_policy tool. It returns the full policy including today's usage and remaining allowance.
- If trading is disabled, inform the user and do not attempt trades
- Never exceed daily limits or per-trade limits
- Only trade on allowed chains with allowed tokens
- Respect the confirmation threshold — ask for explicit confirmation when required

## Entitlements
Before elevated actions, the system checks entitlements automatically. If an action is denied:
- Explain the limit clearly (what was exceeded, current usage vs max)
- Suggest the upgrade path if one exists
- Never attempt to bypass or retry a denied action`,
}

// ── Prediction market skills now DB-managed via skill_catalog ──
// Source: worker/src/polymarket/skills/SKILL.md
// Seeded by migration: 20260326930000_polymarket_skill_catalog.sql

// ── Integration skills (loaded only for installed integrations) ───────
// Content lives in integrations/<provider>/SKILL.md — loaded at startup by
// integration-loader.ts. The skill row is only emitted when the assistant has
// at least one integration plugin installed, and the rendered content covers
// only those installed providers (not the full 40-provider catalog).
// To add a new integration: create integrations/<provider>/SKILL.md and deploy.

interface SkillContent {
  slug: string
  name: string
  description: string
  content: string
}

/**
 * Cross-cutting guidance prepended to every integration skill bundle.
 *
 * Lives in code (not per-provider SKILL.md) because it applies to EVERY
 * integration that talks to humans — email, chat, calendar, CRM, etc.
 * When the user mentions a person by name ("email Eli", "DM Sarah",
 * "schedule a meeting with Alex"), the agent should resolve the name to
 * a real identifier BEFORE asking the user for one. Otherwise it punts
 * on trivially-answerable requests.
 */
const INTEGRATION_WORKFLOW_PREAMBLE = `## Resolving People by Name (applies to ALL integrations)

When the user mentions a person by **first name or nickname** ("email Eli",
"DM Sarah", "invite Alex to the meeting"), you must attempt to resolve the
name to a real identifier (email, user ID, handle) BEFORE asking the user
for one. Asking the user is the **last resort**, not the first step.

Resolution order (stop at the first match):

1. **Check \`## Memories\`** at the top of this system prompt. Prior turns
   may have stored "Eli → eli@acme.com" or "Sarah is our designer
   (@sarah_design on Slack)". Use it.
2. **Search the integration's own history.** Every messaging/email/CRM
   integration has a search or directory tool — call it with the name:
   - Gmail → \`search-emails\` with \`q="from:Eli OR to:Eli"\`, then read
     the top result's \`from\` header for the real address
   - Slack → \`list-users\` and match on \`real_name\` or \`display_name\`
   - Discord → \`list-members(guild_id)\` and match on username
   - HubSpot/Salesforce/Pipedrive → search contacts by name
   - Google Calendar → \`search-events\` for past meetings with that name
3. **Only then**, if no match, ask the user — and be specific:
   "I couldn't find anyone named Eli in your recent emails. What's their
   email address?"

### Rules
- NEVER ask for an email/handle on the first turn if you haven't searched yet
- If multiple matches, pick the most recent one and tell the user which you used ("Sending to eli.chen@acme.com — the Eli you last emailed yesterday. Different person? Let me know.")
- If the user provides a **full email or handle** (eli@acme.com, @sarah), skip resolution and use it directly
- Never invent an email address — if search fails, ask

---

`

function buildIntegrationWorkflowSkill(
  plugins?: ReadonlyArray<IntegrationPluginRef>,
): SkillContent | null {
  if (!plugins || plugins.length === 0) return null
  const providerContent = buildInstalledIntegrationContent(plugins)
  if (!providerContent) return null
  return {
    slug: 'lucid-integration-workflow',
    name: 'Integration Workflow Patterns',
    description:
      'Teaches the agent how to use the OAuth integrations installed on this assistant.',
    content: INTEGRATION_WORKFLOW_PREAMBLE + providerContent,
  }
}


// ── Generic skills (migrate to lucid-plugins/ eventually) ─────────────
// These contain ONLY workflow/safety rules — no tool routing tables.
// Tool awareness is auto-generated from CommandsAllowlist metadata.

const marketIntelligenceSkill = {
  slug: 'lucid-market-intelligence',
  name: 'Market Intelligence',
  description: 'Teaches agent to use market data tools for analysis — always loaded',
  content: `# Market Intelligence

You have powerful market data tools. Use them whenever the user asks about crypto markets, tokens, or trends.

## When to Use What
- **"How's the market?" / "Market analysis"** → call get_market_data for global overview (top coins by market cap + volume)
- **"What's trending?"** → call get_trending for market movers (trending, gainers, losers, smart money)
- **"Tell me about [token]"** → call get_token_info for complete profile (price, volume, security, analytics)
- **"Price of [token]"** → call get_price for current price
- **"Liquidity of [pair]"** → call get_liquidity for DEX pair depth and reserves
- **"Who holds [token]?"** → call get_holders for whale tracking + concentration
- **"Sniper activity on [token]"** → call detect_snipers for bot detection

## CRITICAL RULES
- NEVER say "I can't access market data" or "I don't have real-time data" — you DO have these tools
- NEVER redirect the user to CoinGecko, CoinMarketCap, or any external site — use YOUR tools directly
- NEVER give a generic "try checking X website" response — call the tool and give a real answer
- When asked for analysis, combine multiple tools: get_market_data + get_trending for a full picture
- Present data clearly with key metrics, not raw JSON

## Tool Chaining for Analysis
- "Analyze the market" → get_market_data then get_trending for a comprehensive view
- "Is [token] safe?" → get_token_info (security score + analytics) then risk_check
- "Compare X vs Y" → get_token_info for each, then compare metrics`,
}

const web3ReaderSkill = {
  slug: 'web3-reader',
  name: 'Web3 Reader',
  description: 'Read-only web3 guidance — balance, price, portfolio workflows',
  content: `# Web3 Read-Only Guide

## Rules
- Always use tools to answer on-chain questions — never say "I don't have access"
- If a token name is ambiguous, search for it first before querying price/balance
- Prefer get_portfolio over wallet_balance when user asks about "holdings" or "net worth"
- For transaction history, specify the correct mode (history vs first_transaction)

## Tool Chaining
Some questions require multiple tools in sequence:
- "How much is my SOL worth in USD?" → wallet_balance then get_price
- "Was I funded before I bought BONK?" → wallet_history to get timeline
- "What's my best performing token?" → get_portfolio then get_price for each
- "Analyze the market and my portfolio" → get_market_data then get_portfolio
- "Is [token] safe to buy?" → get_token_info then risk_check`,
}

// web3-operator skill removed — now served from skill_catalog (DB) via import pipeline

// ── Selection logic ──────────────────────────────────────────────────

/**
 * Get built-in skills as ActiveSkillRow[], ready to merge with DB skills.
 *
 * Conditional loading:
 * - market-intelligence: always (every agent gets market data tool awareness)
 * - integration-workflow: only when at least one integration is installed,
 *   and only for the installed providers (not the full 40-provider catalog)
 * - swap-direction: when wallet or trading enabled
 * - swap-execution + cross-chain-funding: when trading enabled
 * - web3-reader: when wallet or trading enabled
 * - web3-operator: from DB catalog (when trading enabled + org installs it)
 */
export function getBuiltinSkills(config?: AssistantSkillConfig): ActiveSkillRow[] {
  if (config?.disable_builtin_skills) {
    return []
  }

  const skills: SkillContent[] = [marketIntelligenceSkill]

  // Integration workflow — only when at least one integration is installed
  const integrationSkill = buildIntegrationWorkflowSkill(config?.plugins)
  if (integrationSkill) skills.push(integrationSkill)

  // Swap direction safety — loaded when wallet or trading is enabled
  if (config?.wallet_enabled || config?.trading_enabled) {
    skills.push(swapDirectionSkill)
  }

  if (config?.trading_enabled) {
    skills.push(swapExecutionSkill)
    skills.push(crossChainFundingSkill)
    // Polymarket skill (trading + hedge) now DB-managed via skill_catalog
    // Trading agents also get wallet read guidance (tool chaining, search-first)
    skills.push(web3ReaderSkill)
  }

  if (!config?.trading_enabled && config?.wallet_enabled) {
    skills.push(web3ReaderSkill)
  }

  return skills.map((skill, i) => ({
    skill_slug: skill.slug,
    skill_name: skill.name,
    skill_description: skill.description,
    sanitized_content: skill.content,
    frontmatter: {},
    sort_order: 1000 + i,
    content_chars: skill.content.length,
    selection_meta: {
      source: 'builtin',
      reason: 'builtin',
    },
  }))
}
