// ---------------------------
// This file was generated by Nango (v0.69.46)
// You can version this file
// ---------------------------

/**
 * ! ** DEPRECATION NOTICE **
 * ! This file will stop being generated in future versions of nango.
 * ! For access to function types, please export types directly from your code.
 * ! You can leverage `zod.infer` to generate types from your zod schemas.
 * ! See the official zod documentation: https://zod.dev/basics?id=inferring-types
 */

export interface ActionInput_twitter_v2_deletetweet {
  /**
   * The ID of the tweet to delete
   */
  tweet_id: string;
};

export interface ActionOutput_twitter_v2_deletetweet {
  deleted: boolean;
};

export interface ActionInput_twitter_v2_getuserinfo {
  /**
   * Twitter username (without @). If omitted, returns the authenticated user.
   */
  username?: string | undefined;
};

export interface ActionOutput_twitter_v2_getuserinfo {
  id: string;
  name: string;
  username: string;
  description?: string | undefined;
  profile_image_url?: string | undefined;
  verified?: boolean | undefined;
  followers_count?: number | undefined;
  following_count?: number | undefined;
  tweet_count?: number | undefined;
  created_at?: string | undefined;
};

export interface ActionInput_twitter_v2_getusertweets {
  /**
   * Twitter username (without @). If omitted, returns authenticated user tweets.
   */
  username?: string | undefined;
  /**
   * Number of tweets to return (5-100, default 10)
   */
  max_results?: number | undefined;
};

export interface ActionOutput_twitter_v2_getusertweets {
  tweets: ({  id: string;
  text: string;
  created_at?: string | undefined;
  like_count?: number | undefined;
  retweet_count?: number | undefined;
  reply_count?: number | undefined;})[];
  result_count: number;
};

export interface ActionInput_twitter_v2_posttweet {
  /**
   * The tweet text (max 280 characters)
   */
  text: string;
  /**
   * Tweet ID to reply to (optional)
   */
  reply_to_tweet_id?: string | undefined;
  /**
   * Tweet ID to quote (optional)
   */
  quote_tweet_id?: string | undefined;
};

export interface ActionOutput_twitter_v2_posttweet {
  id: string;
  text: string;
};

export interface ActionInput_twitter_v2_searchtweets {
  /**
   * Twitter search query (supports operators like from:, to:, has:, is:)
   */
  query: string;
  /**
   * Number of results (10-100, default 10)
   */
  max_results?: number | undefined;
};

export interface ActionOutput_twitter_v2_searchtweets {
  tweets: ({  id: string;
  text: string;
  author_id?: string | undefined;
  created_at?: string | undefined;
  like_count?: number | undefined;
  retweet_count?: number | undefined;
  reply_count?: number | undefined;})[];
  result_count: number;
  next_token?: string | undefined;
};

export interface ActionInput_slack_addreaction {
  /**
   * The channel ID where the message is located. Example: "C1234567890"
   */
  channel_id: string;
  /**
   * The timestamp of the message to react to. Example: "1234567890.123456"
   */
  timestamp: string;
  /**
   * The name of the emoji to use (without colons). Example: "thumbsup"
   */
  emoji_name: string;
};

export interface ActionOutput_slack_addreaction {
  ok: boolean;
};

export interface ActionInput_slack_createconversation {
  /**
   * Name of the channel to create. Must be lowercase, contain only letters, numbers, hyphens, and underscores, and be 80 characters or less.
   */
  name: string;
  /**
   * Whether the channel should be private. Defaults to false (public channel).
   */
  is_private?: boolean | undefined;
};

export interface ActionOutput_slack_createconversation {
  /**
   * The unique identifier of the channel.
   */
  id: string;
  /**
   * The normalized name of the channel.
   */
  name: string;
  /**
   * Whether the channel is private.
   */
  is_private: boolean;
  /**
   * Whether this is a channel.
   */
  is_channel: boolean;
  /**
   * Unix timestamp when the channel was created.
   */
  created: number;
  /**
   * User ID of the channel creator.
   */
  creator: string;
};

export interface ActionInput_slack_deletemessage {
  /**
   * Channel ID containing the message. Example: "C1234567890"
   */
  channel_id: string;
  /**
   * Timestamp of the message to delete. Example: "1405894322.002768"
   */
  message_ts: string;
};

export interface ActionOutput_slack_deletemessage {
  ok: boolean;
  channel: string;
  ts: string;
};

export interface ActionInput_slack_finduserbyemail {
  /**
   * Email address of the user to look up. Example: "user@example.com"
   */
  email: string;
};

export interface ActionOutput_slack_finduserbyemail {
  id: string;
  team_id: string;
  name: string;
  real_name?: string | undefined;
  email: string;
  is_admin: boolean;
  is_bot: boolean;
  is_restricted: boolean;
  is_ultra_restricted: boolean;
  is_deleted: boolean;
  profile: {  avatar_hash?: string | undefined;
  status_text?: string | undefined;
  status_emoji?: string | undefined;
  real_name?: string | undefined;
  display_name?: string | undefined;
  email?: string | undefined;
  image_24?: string | undefined;
  image_32?: string | undefined;
  image_48?: string | undefined;
  image_72?: string | undefined;
  image_192?: string | undefined;
  image_512?: string | undefined;};
};

export interface ActionInput_slack_getchannelinfo {
  /**
   * Slack channel ID to retrieve information about. Example: "C012AB3CD"
   */
  channel_id: string;
};

export interface ActionOutput_slack_getchannelinfo {
  /**
   * Channel ID
   */
  id: string;
  /**
   * Channel name
   */
  name?: string | undefined;
  /**
   * Channel topic information
   */
  topic?: {  value: string;
  creator: string;
  last_set: number;} | undefined;
  /**
   * Channel purpose information
   */
  purpose?: {  value: string;
  creator: string;
  last_set: number;} | undefined;
  /**
   * Whether this is a public channel
   */
  is_channel: boolean;
  /**
   * Whether this is a private channel
   */
  is_group: boolean;
  /**
   * Whether this is a direct message
   */
  is_im: boolean;
  /**
   * Whether this is a multi-person direct message
   */
  is_mpim: boolean;
  /**
   * Whether the conversation is private
   */
  is_private: boolean;
  /**
   * Whether the channel is archived
   */
  is_archived: boolean;
  /**
   * Whether this is the general channel
   */
  is_general?: boolean | undefined;
  /**
   * Unix timestamp when the channel was created
   */
  created: number;
  /**
   * User ID of the channel creator
   */
  creator?: string | undefined;
  /**
   * Number of members in the channel (if available)
   */
  num_members?: number | undefined;
  /**
   * Team ID for the conversation
   */
  context_team_id?: string | undefined;
};

export interface ActionInput_slack_getconversationhistory {
  /**
   * The conversation ID to fetch history for. Example: "C1234567890"
   */
  channel_id: string;
  /**
   * Pagination cursor from previous response. Omit for first page.
   */
  cursor?: string | undefined;
  /**
   * Only messages after this Unix timestamp will be included. Example: "1512085950.000216"
   */
  oldest?: string | undefined;
  /**
   * Only messages before this Unix timestamp will be included. Example: "1512104434.000490"
   */
  latest?: string | undefined;
  /**
   * Include messages with oldest or latest timestamps in results. Defaults to false.
   */
  inclusive?: boolean | undefined;
  /**
   * Maximum number of messages to return (max 999). Defaults to 100.
   */
  limit?: number | undefined;
};

export interface ActionOutput_slack_getconversationhistory {
  messages: ({  type: string;
  ts: string;
  user?: string | undefined;
  text?: string | undefined;
  thread_ts?: string | undefined;
  reply_count?: number | undefined;
  reactions?: ({  name: string;
  count: number;
  users: string[];})[] | undefined;
  attachments?: unknown[] | undefined;})[];
  has_more: boolean;
  next_cursor?: string | undefined;
  pin_count?: number | undefined;
};

export interface ActionInput_slack_getthreadreplies {
  /**
   * The ID of the channel/conversation containing the thread. Example: "C1234567890"
   */
  channel_id: string;
  /**
   * The timestamp of the parent message in the thread. Example: "1234567890.123456"
   */
  thread_ts: string;
  /**
   * Pagination cursor from previous response. Omit for first page.
   */
  cursor?: string | undefined;
  /**
   * Maximum number of messages to return per page. Default: 100.
   */
  limit?: number | undefined;
};

export interface ActionOutput_slack_getthreadreplies {
  /**
   * Array of messages in the thread, including parent and replies
   */
  messages: ({  type: string;
  user?: string | undefined;
  text: string;
  ts: string;
  thread_ts?: string | undefined;
  reply_count?: number | undefined;
  reply_users_count?: number | undefined;
  reply_users?: string[] | undefined;})[];
  /**
   * Pagination cursor for next page. Omitted if no more pages.
   */
  next_cursor?: string | undefined;
  /**
   * Whether there are more messages to fetch
   */
  has_more: boolean;
};

export interface ActionInput_slack_getuserinfo {
  /**
   * Slack user ID. Example: "U12345678"
   */
  user_id: string;
};

export interface ActionOutput_slack_getuserinfo {
  id: string;
  team_id: string;
  name: string;
  real_name?: string | undefined;
  display_name?: string | undefined;
  email?: string | undefined;
  avatar_url?: string | undefined;
  is_bot: boolean;
  is_admin?: boolean | undefined;
  is_owner?: boolean | undefined;
  is_primary_owner?: boolean | undefined;
  is_restricted?: boolean | undefined;
  is_ultra_restricted?: boolean | undefined;
  is_app_user?: boolean | undefined;
  updated?: number | undefined;
};

export interface ActionInput_slack_joinchannel {
  /**
   * ID of the channel to join. Example: C061EG9SL
   */
  channel_id: string;
};

export interface ActionOutput_slack_joinchannel {
  id: string;
  name?: string | undefined;
  is_channel?: boolean | undefined;
  is_group?: boolean | undefined;
  is_im?: boolean | undefined;
  is_private?: boolean | undefined;
  is_archived?: boolean | undefined;
  is_general?: boolean | undefined;
  created?: number | undefined;
  creator?: string | undefined;
  is_member?: boolean | undefined;
  num_members?: number | undefined;
  topic?: {  value: string;
  creator: string;
  last_set: number;} | undefined;
  purpose?: {  value: string;
  creator: string;
  last_set: number;} | undefined;
};

export interface ActionInput_slack_listchannels {
  /**
   * Max channels to return (1-200, default 100)
   */
  limit?: number | undefined;
  /**
   * Comma-separated channel types: public_channel, private_channel (default: public_channel)
   */
  types?: string | undefined;
};

export interface ActionOutput_slack_listchannels {
  channels: ({  id: string;
  name: string;
  topic?: string | undefined;
  purpose?: string | undefined;
  num_members?: number | undefined;
  is_private?: boolean | undefined;
  is_archived?: boolean | undefined;})[];
  total: number;
};

export interface ActionInput_slack_listconversations {
  /**
   * Comma-separated list of conversation types to filter by. Options: public_channel, private_channel, mpim, im. Default: public_channel.
   */
  types?: string | undefined;
  /**
   * Pagination cursor from previous response. Omit for first page.
   */
  cursor?: string | undefined;
  /**
   * Maximum number of conversations to return (1-200). Default: 100.
   */
  limit?: number | undefined;
};

export interface ActionOutput_slack_listconversations {
  conversations: ({  id: string;
  name: string;
  created: number;
  creator: string;
  is_archived: boolean;
  is_general: boolean;
  is_private: boolean;
  is_mpim: boolean;
  is_im: boolean;
  num_members?: number | undefined;})[];
  next_cursor?: string | undefined;
  total: number;
};

export interface ActionInput_slack_listpins {
  /**
   * The channel ID to list pinned items for. Example: "C1234567890"
   */
  channel_id: string;
};

export interface ActionOutput_slack_listpins {
  /**
   * List of pinned items in the channel
   */
  items: ({  type: 'message' | 'file' | 'file_comment';
  /**
   * Unix timestamp when the item was pinned
   */
  created: number;
  /**
   * User ID who pinned the item
   */
  created_by: string;
  /**
   * Channel ID where the item is pinned
   */
  channel: string;
  message?: {  type: string;
  user: string;
  text: string;
  ts: string;
  permalink: string;
  pinned_to?: string[] | undefined;};
  file?: {  id: string;
  created: number;
  timestamp: number;
  name?: string | undefined;
  title?: string | undefined;
  mimetype?: string | undefined;
  filetype?: string | undefined;
  user: string;
  permalink: string;};
  comment?: {  id: string;
  created: number;
  timestamp: number;
  user: string;
  comment: string;} | undefined;})[];
};

export interface ActionInput_slack_listusers {
  /**
   * Pagination cursor from previous response. Omit for first page.
   */
  cursor?: string | undefined;
};

export interface ActionOutput_slack_listusers {
  items: ({  id: string;
  team_id: string;
  name: string;
  deleted: boolean;
  real_name?: string | undefined;
  profile: {  real_name?: string | undefined;
  display_name?: string | undefined;
  email?: string | undefined;
  avatar_hash?: string | undefined;
  image_24?: string | undefined;
  image_32?: string | undefined;
  image_48?: string | undefined;
  image_72?: string | undefined;
  image_192?: string | undefined;
  image_512?: string | undefined;};
  is_admin: boolean;
  is_owner: boolean;
  is_bot: boolean;
  updated: number;})[];
  /**
   * Pagination cursor for the next page. Omitted if no more pages.
   */
  next_cursor?: string | undefined;
};

export interface ActionInput_slack_markasread {
  /**
   * The channel ID to mark as read. Example: "C02MB5ZABA7"
   */
  channel_id: string;
  /**
   * Timestamp of the message to mark as read. Example: "1234567890.123456"
   */
  message_ts: string;
};

export interface ActionOutput_slack_markasread {
  /**
   * Whether the operation succeeded
   */
  ok: boolean;
};

export interface ActionInput_slack_postmessage {
  /**
   * Channel, private group, or IM channel ID to send message to. Example: "C1234567890"
   */
  channel: string;
  /**
   * Text of the message to send
   */
  text: string;
  /**
   * Timestamp of parent message to reply in thread. Example: "1234567890.123456"
   */
  thread_ts?: string | undefined;
};

export interface ActionOutput_slack_postmessage {
  /**
   * Whether the API request succeeded
   */
  ok: boolean;
  /**
   * ID of the channel the message was sent to
   */
  channel: string;
  /**
   * Timestamp of the sent message
   */
  ts: string;
  /**
   * The message object that was sent
   */
  message: {  /**
   * Message type
   */
  type: string;
  /**
   * Message subtype
   */
  subtype?: string | undefined;
  /**
   * Text of the message
   */
  text: string;
  /**
   * Timestamp of the message
   */
  ts: string;
  /**
   * Username of the sender
   */
  username?: string | undefined;
  /**
   * ID of the bot if sent by bot
   */
  bot_id?: string | undefined;};
};

export interface ActionInput_slack_schedulemessage {
  /**
   * The channel to post to. Example: "C02MB5ZABA7"
   */
  channel_id: string;
  /**
   * The message text to schedule
   */
  text: string;
  /**
   * Unix timestamp for when to post. Example: 1735689600
   */
  post_at: number;
  /**
   * Optional thread timestamp to post in a thread. Example: "1234567890.123456"
   */
  thread_ts?: string | undefined;
};

export interface ActionOutput_slack_schedulemessage {
  scheduled_message_id: string;
  channel: string;
  post_at: number;
};

export interface ActionInput_slack_searchfiles {
  /**
   * Search query string. Example: "report"
   */
  query: string;
  /**
   * Number of items to return per page. Max 100. Default: 20
   */
  count?: number | undefined;
  /**
   * Page number of results to return. Default: 1
   */
  page?: number | undefined;
  /**
   * Sort by score or timestamp. Default: score
   */
  sort?: 'score' | 'timestamp' | undefined;
  /**
   * Sort direction: ascending or descending. Default: desc
   */
  sort_dir?: 'asc' | 'desc' | undefined;
  /**
   * Enable query highlight markers in results. Default: false
   */
  highlight?: boolean | undefined;
};

export interface ActionOutput_slack_searchfiles {
  files: ({  id: string;
  name: string;
  title?: string | undefined;
  filetype: string;
  mimetype: string;
  user: string;
  username: string;
  created: number;
  timestamp: number;
  size: number;
  mode: string;
  is_public: boolean;
  is_external: boolean;
  external_type: string;
  editable: boolean;
  display_as_bot: boolean;
  url_private?: string | undefined;
  url_private_download?: string | undefined;
  permalink?: string | undefined;
  permalink_public?: string | undefined;
  preview?: string | undefined;
  public_url_shared: boolean;
  channels: string[];
  groups: string[];
  ims: string[];
  comments_count: number;
  pretty_type: string;
  score?: string | undefined;})[];
  paging: {  count: number;
  page: number;
  pages: number;
  total: number;};
  total: number;
};

export interface ActionInput_slack_searchmessages {
  /**
   * Search query (supports Slack search operators like in:#channel, from:@user)
   */
  query: string;
  /**
   * Number of results (1-100, default 20)
   */
  count?: number | undefined;
  /**
   * Sort by relevance or recency (default: score)
   */
  sort?: 'score' | 'timestamp' | undefined;
};

export interface ActionOutput_slack_searchmessages {
  messages: ({  text: string;
  username?: string | undefined;
  channel_name?: string | undefined;
  channel_id?: string | undefined;
  ts?: string | undefined;
  permalink?: string | undefined;})[];
  total: number;
};

export interface ActionInput_slack_sendephemeralmessage {
  /**
   * Channel ID to send the ephemeral message to. Example: "C1234567890"
   */
  channel_id: string;
  /**
   * User ID to send the ephemeral message to. The user must be in the specified channel. Example: "U1234567890"
   */
  user_id: string;
  /**
   * Text of the message to send. Supports Slack formatting.
   */
  text: string;
  /**
   * Thread timestamp to reply to a specific thread. Example: "1234567890.123456"
   */
  thread_ts?: string | undefined;
};

export interface ActionOutput_slack_sendephemeralmessage {
  ok: boolean;
  message_ts: string;
  error?: string | undefined;
};

export interface ActionInput_slack_sendmessage {
  /**
   * Channel ID to send the message to. Example: "C1234567890"
   */
  channel_id: string;
  /**
   * Text content of the message to send. Example: "Hello world"
   */
  text: string;
};

export interface ActionOutput_slack_sendmessage {
  ok: boolean;
  channel: string;
  /**
   * Timestamp ID of the sent message
   */
  ts: string;
  message?: {  type: string;
  user: string;
  text: string;
  ts: string;
  team?: string | undefined;
  bot_id?: string | undefined;
  app_id?: string | undefined;};
};

export interface ActionInput_slack_setchannelpurpose {
  /**
   * Channel ID to set the purpose for. Example: "C1234567890"
   */
  channel_id: string;
  /**
   * The new purpose text for the channel.
   */
  purpose: string;
};

export interface ActionOutput_slack_setchannelpurpose {
  /**
   * Whether the purpose was successfully updated
   */
  success: boolean;
  /**
   * The ID of the channel that was updated
   */
  channel_id: string;
  /**
   * The new purpose that was set
   */
  purpose: string;
};

export interface ActionInput_slack_setchanneltopic {
  /**
   * The ID of the channel to set the topic for. Example: "C12345678"
   */
  channel_id: string;
  /**
   * The new topic string. Does not support formatting or linkification. Example: "Apply topically for best effects"
   */
  topic: string;
};

export interface ActionOutput_slack_setchanneltopic {
  ok: boolean;
  channel: {  [key: string]: any | undefined;};
  warning?: string | undefined;
  response_metadata?: {  [key: string]: any | undefined;};
};

export interface ActionInput_slack_updatemessage {
  /**
   * The ID of the channel containing the message to update. Example: "C1234567890"
   */
  channel_id: string;
  /**
   * The timestamp of the message to update. Example: "1401383885.000061"
   */
  message_ts: string;
  /**
   * The updated text of the message. Example: "Updated message text"
   */
  text: string;
  /**
   * Pass true to update the message as the authenticated user. Bot users in this context are considered authed users. Default: true
   */
  as_user?: boolean | undefined;
  /**
   * Find and link channel names and usernames. Defaults to false. To use this, you need parse set to "full".
   */
  link_names?: boolean | undefined;
  /**
   * Change how messages are treated. Defaults to "client" which attempts to discover links. Use "none" to treat text literally, "full" for full parsing with link_names.
   */
  parse?: 'none' | 'full' | 'client' | undefined;
  /**
   * Pass false to disable unfurling of links.
   */
  unfurl_links?: boolean | undefined;
  /**
   * Pass false to disable unfurling of media content.
   */
  unfurl_media?: boolean | undefined;
  /**
   * Used to reply to a thread only and not to the channel. Pass true to reply to the channel as well.
   */
  reply_broadcast?: boolean | undefined;
  /**
   * A JSON array of blocks to use as the message content. When blocks is provided, text becomes the fallback text for notifications.
   */
  blocks?: ({})[] | undefined;
  /**
   * A JSON array of legacy attachments. Not recommended for new apps, use blocks instead.
   */
  attachments?: ({})[] | undefined;
};

export interface ActionOutput_slack_updatemessage {
  /**
   * Whether the API call was successful
   */
  ok: boolean;
  /**
   * The ID of the channel where the message was updated
   */
  channel: string;
  /**
   * The timestamp of the updated message
   */
  ts: string;
  /**
   * The updated text of the message
   */
  text: string;
  /**
   * Full message object containing updated message details
   */
  message?: any | undefined;
};

export interface ActionInput_notion_appendblockchildren {
  /**
   * The ID of the block or page to append to. Example: "2b6ce298-3121-80ae-bfe1-f8984b993639"
   */
  block_id: string;
  /**
   * Array of block objects to append (max 100).
   */
  children: any[];
  /**
   * Block ID to insert after.
   */
  after?: string | undefined;
};

export interface ActionOutput_notion_appendblockchildren {
  object: string;
  results: any[];
};

export interface ActionInput_notion_archivepage {
  /**
   * The ID of the page to archive. Example: "2b6ce298-3121-80ae-bfe1-f8984b993639"
   */
  page_id: string;
};

export interface ActionOutput_notion_archivepage {
  id: string;
  object: string;
  archived: boolean;
};

export interface ActionInput_notion_createcomment {
  /**
   * Parent page for the comment.
   */
  parent: {  /**
   * Page ID to add comment to. Example: "2b6ce298-3121-80ae-bfe1-f8984b993639"
   */
  page_id: string;};
  /**
   * Comment content as rich text array.
   */
  rich_text: any[];
  /**
   * Discussion thread ID to reply to.
   */
  discussion_id?: string | undefined;
};

export interface ActionOutput_notion_createcomment {
  id: string;
  object: string;
  created_time: string;
  rich_text: any[];
};

export interface ActionInput_notion_createpage {
  /**
   * Parent page or database. Must include either page_id or database_id.
   */
  parent: {  /**
   * Parent page ID. Example: "2b6ce298-3121-80ae-bfe1-f8984b993639"
   */
  page_id?: string | undefined;
  /**
   * Parent database ID. Example: "2b6ce298-3121-8079-a497-d3eca16d875c"
   */
  database_id?: string | undefined;};
  /**
   * Page properties. For pages with page parent, use title property. For database parents, use database property schema.
   */
  properties: {  [key: string]: any | undefined;};
  /**
   * Array of block objects to add as page content.
   */
  children?: any[] | undefined;
  /**
   * Page icon as emoji or external URL.
   */
  icon?: {  type?: string | undefined;
  emoji?: string | undefined;
  external?: {  url: string;} | undefined;};
  /**
   * Page cover image as external URL.
   */
  cover?: {  type?: string | undefined;
  external?: {  url: string;} | undefined;};
};

export interface ActionOutput_notion_createpage {
  id: string;
  object: string;
  created_time: string;
  last_edited_time: string;
  created_by: {  object: string;
  id: string;};
  last_edited_by: {  object: string;
  id: string;};
  parent: {  type: string;
  page_id: string | null;
  database_id: string | null;};
  archived: boolean;
  in_trash: boolean;
  properties: {  [key: string]: any | undefined;};
  url: string;
  public_url: string | null;
};

export interface ActionInput_notion_listcomments {
  /**
   * The ID of the page or block. Example: "2b6ce298-3121-80ae-bfe1-f8984b993639"
   */
  block_id: string;
  /**
   * Number of results to return (max 100).
   */
  page_size?: number | undefined;
  /**
   * Pagination cursor from previous response.
   */
  cursor?: string | undefined;
};

export interface ActionOutput_notion_listcomments {
  object: string;
  results: any[];
  has_more: boolean;
  next_cursor: string | null;
};

export interface ActionInput_notion_listusers {
  /**
   * Number of results to return (max 100).
   */
  page_size?: number | undefined;
  /**
   * Pagination cursor from previous response.
   */
  cursor?: string | undefined;
};

export interface ActionOutput_notion_listusers {
  object: string;
  results: any[];
  has_more: boolean;
  next_cursor: string | null;
};

export interface ActionInput_notion_querydatabase {
  /**
   * The ID of the database to query. Example: "2b6ce298-3121-8079-a497-d3eca16d875c"
   */
  database_id: string;
  /**
   * Filter conditions for the query.
   */
  filter?: any | undefined;
  /**
   * Sort criteria for the results.
   */
  sorts?: any[] | undefined;
  /**
   * Number of results to return (max 100).
   */
  page_size?: number | undefined;
  /**
   * Pagination cursor from previous response.
   */
  cursor?: string | undefined;
};

export interface ActionOutput_notion_querydatabase {
  object: string;
  results: any[];
  has_more: boolean;
  next_cursor: string | null;
};

export interface ActionInput_notion_retrieveblockchildren {
  /**
   * The ID of the block or page. Example: "2b6ce298-3121-80ae-bfe1-f8984b993639"
   */
  block_id: string;
  /**
   * Number of results to return (max 100).
   */
  page_size?: number | undefined;
  /**
   * Pagination cursor from previous response.
   */
  cursor?: string | undefined;
};

export interface ActionOutput_notion_retrieveblockchildren {
  object: string;
  results: any[];
  has_more: boolean;
  next_cursor: string | null;
};

export interface ActionInput_notion_retrievedatabase {
  /**
   * The ID of the database to retrieve. Example: "2b6ce298-3121-8079-a497-d3eca16d875c"
   */
  database_id: string;
};

export interface ActionOutput_notion_retrievedatabase {
  id: string;
  object: string;
  created_time: string;
  last_edited_time: string;
  title: any[];
  properties: {  [key: string]: any | undefined;};
};

export interface ActionInput_notion_retrievepage {
  /**
   * The ID of the page to retrieve. Example: "2b6ce298-3121-80ae-bfe1-f8984b993639"
   */
  page_id: string;
};

export interface ActionOutput_notion_retrievepage {
  id: string;
  object: string;
  created_time: string;
  last_edited_time: string;
  created_by: {  object: string;
  id: string;};
  last_edited_by: {  object: string;
  id: string;};
  parent: {  type: string;
  page_id: string | null;
  database_id: string | null;
  workspace: boolean | null;};
  archived: boolean;
  in_trash: boolean;
  properties: {  [key: string]: any | undefined;};
  url: string;
  public_url: string | null;
};

export interface ActionInput_notion_searchpages {
  /**
   * Text to search for in page titles.
   */
  query?: string | undefined;
  /**
   * Number of results to return (max 100).
   */
  page_size?: number | undefined;
  /**
   * Pagination cursor from previous response.
   */
  cursor?: string | undefined;
};

export interface ActionOutput_notion_searchpages {
  object: string;
  results: any[];
  has_more: boolean;
  next_cursor: string | null;
};

export interface ActionInput_notion_updatepage {
  /**
   * The ID of the page to update. Example: "2b6ce298-3121-80ae-bfe1-f8984b993639"
   */
  page_id: string;
  /**
   * Page properties to update.
   */
  properties?: {  [key: string]: any | undefined;};
  /**
   * Page icon as emoji or external URL.
   */
  icon?: {  type?: string | undefined;
  emoji?: string | undefined;
  external?: {  url: string;} | undefined;};
  /**
   * Page cover image as external URL.
   */
  cover?: {  type?: string | undefined;
  external?: {  url: string;} | undefined;};
  /**
   * Set to true to archive the page.
   */
  archived?: boolean | undefined;
};

export interface ActionOutput_notion_updatepage {
  id: string;
  object: string;
  created_time: string;
  last_edited_time: string;
  created_by: {  object: string;
  id: string;};
  last_edited_by: {  object: string;
  id: string;};
  parent: {  type: string;
  page_id: string | null;
  database_id: string | null;
  workspace: boolean | null;};
  archived: boolean;
  in_trash: boolean;
  properties: {  [key: string]: any | undefined;};
  url: string;
  public_url: string | null;
};

export interface ActionInput_google_appendvaluestospreadsheet {
  /**
   * The ID of the spreadsheet to update. Example: "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms"
   */
  spreadsheetId: string;
  /**
   * The A1 notation of a range to search for a logical table of data. Example: "Sheet1!A1" or "Sheet1"
   */
  range: string;
  /**
   * The values to append to the spreadsheet. Each inner array represents a row of data.
   */
  values: any[];
  /**
   * How the input data should be interpreted. "RAW": The values will be parsed as if the user typed them into the UI. "USER_ENTERED": The values will be parsed as if the user typed them into the UI, but formulas will be calculated.
   */
  valueInputOption?: string | undefined;
  /**
   * How the input data should be inserted. "OVERWRITE": Overwrite existing data. "INSERT_ROWS": Insert new rows.
   */
  insertDataOption?: string | undefined;
  /**
   * The major dimension of the values. "ROWS": Values are organized by row. "COLUMNS": Values are organized by column.
   */
  majorDimension?: string | undefined;
};

export interface ActionOutput_google_appendvaluestospreadsheet {
  spreadsheetId: string;
  tableRange: string;
  updatedRange: string;
  updatedRows: number;
  updatedColumns: number;
  updatedCells: number;
};

export interface ActionInput_google_batchgetvalues {
  /**
   * The ID of the spreadsheet to retrieve data from. Example: "1abc123xyz"
   */
  spreadsheetId: string;
  /**
   * The A1 notation or R1C1 notation of the ranges to retrieve values from. Example: ["Sheet1!A1:D5", "Sheet2!B2:C4"]
   */
  ranges: string[];
  /**
   * The major dimension that results should use. Defaults to ROWS.
   */
  majorDimension?: 'ROWS' | 'COLUMNS' | undefined;
  /**
   * How values should be rendered in the output.
   */
  valueRenderOption?: 'FORMATTED_VALUE' | 'UNFORMATTED_VALUE' | 'FORMULA' | undefined;
  /**
   * How dates, times, and durations should be represented in the output.
   */
  dateTimeRenderOption?: 'SERIAL_NUMBER' | 'FORMATTED_STRING' | undefined;
};

export interface ActionOutput_google_batchgetvalues {
  /**
   * The ID of the spreadsheet the data was retrieved from.
   */
  spreadsheetId: string;
  /**
   * The values of the ranges requested.
   */
  valueRanges: ({  /**
   * The range the values cover, in A1 notation.
   */
  range: string;
  /**
   * The major dimension of the values.
   */
  majorDimension?: string | undefined;
  /**
   * The data that was read. Array of arrays representing rows/columns, with each cell value being a string, number, boolean, or null.
   */
  values?: any[] | undefined;})[];
};

export interface ActionInput_google_clearvalues {
  /**
   * The ID of the spreadsheet to update. Example: "1a2b3c4d5e6f7g8h9i0j"
   */
  spreadsheetId: string;
  /**
   * The A1 notation or R1C1 notation of the values to clear. Example: "Sheet1!A1:D10"
   */
  range: string;
};

export interface ActionOutput_google_clearvalues {
  spreadsheetId: string;
  clearedRange: string;
};

export interface ActionInput_google_createspreadsheetrow {
  /**
   * The ID of the spreadsheet. Example: "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms"
   */
  spreadsheetId: string;
  /**
   * The ID of the sheet (can be found via the API). Example: 687284948
   */
  sheetId: number;
  /**
   * The name of the sheet for A1 notation. Example: "Sheet1"
   */
  sheetName: string;
  /**
   * The index where to insert the row (0-based, where 0 is the first row). Example: 5
   */
  rowIndex: number;
  /**
   * Array of values to insert in the new row. Example: ["John", "Doe", "john@example.com"]
   */
  values: string[];
};

export interface ActionOutput_google_createspreadsheetrow {
  spreadsheetId: string;
  sheetId: number;
  rowIndex: number;
  values: string[];
  updatedRange: string;
};

export interface ActionInput_google_createspreadsheet {
  /**
   * Spreadsheet properties including title
   */
  properties: {  /**
   * Spreadsheet title. Example: "My New Spreadsheet"
   */
  title: string;
  /**
   * Spreadsheet locale. Example: "en_US"
   */
  locale?: string | undefined;
  /**
   * Spreadsheet time zone. Example: "America/New_York"
   */
  timeZone?: string | undefined;};
  /**
   * Array of sheets to create in the spreadsheet
   */
  sheets?: ({  properties?: {  /**
   * Sheet title. Example: "Sheet1"
   */
  title?: string | undefined;
  gridProperties?: {  rowCount?: number | undefined;
  columnCount?: number | undefined;};};})[];
};

export interface ActionOutput_google_createspreadsheet {
  /**
   * The unique ID of the created spreadsheet
   */
  spreadsheetId: string;
  /**
   * The URL to view the spreadsheet in Google Sheets
   */
  spreadsheetUrl: string;
  properties?: any | undefined;
};

export interface ActionInput_google_getvalues {
  /**
   * The ID of the spreadsheet to retrieve data from. Example: "1aBcD..."
   */
  spreadsheetId: string;
  /**
   * The A1 notation or R1C1 notation of the range to retrieve values from. Example: "Sheet1!A1:C10" or "Sheet1"
   */
  range: string;
};

export interface ActionOutput_google_getvalues {
  spreadsheetId: string;
  range: string;
  majorDimension: 'ROWS' | 'COLUMNS';
  /**
   * The data values in the range, as a 2D array where each inner array represents a row
   */
  values?: any | undefined;
};

export interface ActionInput_google_listspreadsheets {
  /**
   * Search query to filter spreadsheets by name
   */
  query?: string | undefined;
  /**
   * Max results (1-50, default 10)
   */
  page_size?: number | undefined;
};

export interface ActionOutput_google_listspreadsheets {
  spreadsheets: ({  id: string;
  name: string;
  url?: string | undefined;
  created_time?: string | undefined;
  modified_time?: string | undefined;})[];
  total: number;
};

export interface ActionInput_google_updatevalues {
  /**
   * The ID of the spreadsheet to update. Example: "1abc123def456ghi"
   */
  spreadsheetId: string;
  /**
   * The A1 notation of the values to update. Example: "Sheet1!A1:B2"
   */
  range: string;
  /**
   * The data to write, as an array of arrays. Each inner array represents a row. Example: [["A1", "B1"], ["A2", "B2"]]
   */
  values: any[];
  /**
   * How the input data should be interpreted. RAW = values as-is, USER_ENTERED = parsed as if typed into the UI. Default: USER_ENTERED
   */
  valueInputOption?: 'RAW' | 'USER_ENTERED' | undefined;
  /**
   * The major dimension of the values. ROWS = each inner array is a row, COLUMNS = each inner array is a column. Default: ROWS
   */
  majorDimension?: 'ROWS' | 'COLUMNS' | undefined;
  /**
   * If true, the response includes the updated cell values. Default: false
   */
  includeValuesInResponse?: boolean | undefined;
};

export interface ActionOutput_google_updatevalues {
  spreadsheetId: string;
  updatedRange: string;
  updatedRows: number;
  updatedColumns: number;
  updatedCells: number;
};

export interface ActionInput_google_upsertrow {
  /**
   * The ID of the spreadsheet to update. Example: "1aBcD..."
   */
  spreadsheetId: string;
  /**
   * The A1 notation of the range to search for existing data and append to. Example: "Sheet1!A1:E" or "Sheet1"
   */
  range: string;
  /**
   * The row values to upsert. Example: ["Name", "Email", "Phone"]
   */
  values: string[];
  /**
   * The column index (0-based) to use as the key for matching existing rows. If not provided, always appends.
   */
  keyColumn?: number | undefined;
  /**
   * The value to match in the key column for updating an existing row. Required if key_column is provided.
   */
  keyValue?: string | undefined;
};

export interface ActionOutput_google_upsertrow {
  success: boolean;
  operation: 'appended' | 'updated';
  spreadsheetId: string;
  updatedRange: string;
  updatedRows: number;
};

export interface ActionInput_google_addattendee {
  /**
   * Calendar ID. Use "primary" for the default calendar. Example: "primary"
   */
  calendarId: string;
  /**
   * Event ID to add attendee to. Example: "abc123xyz"
   */
  eventId: string;
  /**
   * Email address of the attendee to add. Example: "attendee@example.com"
   */
  attendeeEmail: string;
  /**
   * Display name of the attendee (optional). Example: "John Doe"
   */
  attendeeName?: string | undefined;
  /**
   * Whether the attendee is optional (optional). Default: false
   */
  optional?: boolean | undefined;
  /**
   * Response status of the attendee (optional). Default: "needsAction"
   */
  responseStatus?: 'needsAction' | 'declined' | 'tentative' | 'accepted' | undefined;
};

export interface ActionOutput_google_addattendee {
  id: string;
  summary?: string | undefined;
  attendees: ({  email: string;
  displayName?: string | undefined;
  optional?: boolean | undefined;
  responseStatus?: string | undefined;})[];
};

export interface ActionInput_google_createalldayevent {
  /**
   * Calendar identifier. Use "primary" for the primary calendar.
   */
  calendarId?: string | undefined;
  /**
   * Title of the event
   */
  summary: string;
  /**
   * Start date in yyyy-mm-dd format (inclusive)
   */
  startDate: string;
  /**
   * End date in yyyy-mm-dd format (exclusive)
   */
  endDate: string;
  /**
   * Description of the event
   */
  description?: string | undefined;
  /**
   * Location of the event
   */
  location?: string | undefined;
};

export interface ActionOutput_google_createalldayevent {
  id: string;
  summary: string;
  startDate: string;
  endDate: string;
  description?: string | undefined;
  location?: string | undefined;
  htmlLink: string;
};

export interface ActionInput_google_createevent {
  /**
   * Calendar ID to create the event in. Example: "primary" or a calendar ID string
   */
  calendarId: string;
  /**
   * Event title/summary. Example: "Team Meeting"
   */
  summary: string;
  /**
   * Event description
   */
  description?: string | undefined;
  /**
   * Event location
   */
  location?: string | undefined;
  start: {  /**
   * Start time in ISO 8601 format. Example: "2024-03-15T09:00:00-07:00"
   */
  dateTime: string;
  /**
   * Time zone for the start time. Example: "America/Los_Angeles"
   */
  timeZone?: string | undefined;};
  end: {  /**
   * End time in ISO 8601 format. Example: "2024-03-15T10:00:00-07:00"
   */
  dateTime: string;
  /**
   * Time zone for the end time. Example: "America/Los_Angeles"
   */
  timeZone?: string | undefined;};
  /**
   * List of attendees
   */
  attendees?: ({  /**
   * Email address of the attendee. Example: "attendee@example.com"
   */
  email: string;
  /**
   * Display name of the attendee
   */
  displayName?: string | undefined;
  /**
   * Response status
   */
  responseStatus?: 'needsAction' | 'declined' | 'tentative' | 'accepted' | undefined;})[];
  /**
   * Event reminders
   */
  reminders?: {  /**
   * Whether to use default reminders
   */
  useDefault?: boolean | undefined;
  /**
   * Custom reminder overrides
   */
  overrides?: ({  /**
   * Method of reminder
   */
  method: 'email' | 'popup';
  /**
   * Minutes before the event to trigger the reminder
   */
  minutes: number;})[] | undefined;};
  /**
   * Recurrence rules (RRULE, EXRULE, RDATE, EXDATE). Example: ["RRULE:FREQ=WEEKLY;BYDAY=MO"]
   */
  recurrence?: string[] | undefined;
};

export interface ActionOutput_google_createevent {
  /**
   * Event ID
   */
  id: string;
  /**
   * Link to the event in Google Calendar
   */
  htmlLink: string;
  /**
   * Event title/summary
   */
  summary: string;
  /**
   * Event description
   */
  description?: string | undefined;
  /**
   * Event location
   */
  location?: string | undefined;
  start: {  dateTime: string;
  timeZone?: string | undefined;};
  end: {  dateTime: string;
  timeZone?: string | undefined;};
  attendees?: ({  email: string;
  displayName?: string | undefined;
  responseStatus: string;})[];
  /**
   * Creation timestamp
   */
  created: string;
  /**
   * Last update timestamp
   */
  updated: string;
};

export interface ActionInput_google_createrecurringevent {
  /**
   * Calendar ID. Defaults to "primary". Example: "primary"
   */
  calendarId?: string | undefined;
  /**
   * Event title/summary. Example: "Weekly Team Meeting"
   */
  summary: string;
  /**
   * Event description. Example: "Discuss project progress"
   */
  description?: string | undefined;
  /**
   * Event location. Example: "Conference Room A"
   */
  location?: string | undefined;
  /**
   * Event start time in RFC3339 format. Example: "2024-03-15T09:00:00-07:00"
   */
  start: string;
  /**
   * Event end time in RFC3339 format. Example: "2024-03-15T10:00:00-07:00"
   */
  end: string;
  /**
   * iCalendar RRULE for recurrence. Example: "FREQ=WEEKLY;BYDAY=MO,WE,FR"
   */
  rrule: string;
  /**
   * Timezone for the event. Defaults to "UTC". Example: "America/Los_Angeles"
   */
  timezone?: string | undefined;
};

export interface ActionOutput_google_createrecurringevent {
  id: string;
  htmlLink: string;
  summary: string;
  start: string;
  end: string;
  recurrence?: string[] | undefined;
  status: string;
};

export interface ActionInput_google_deleteevent {
  /**
   * Calendar ID. Example: "primary" or "abc123@group.calendar.google.com"
   */
  calendarId: string;
  /**
   * Event ID to delete. Example: "tpv6jfth9cbnqhi1f570l45878"
   */
  eventId: string;
};

export interface ActionOutput_google_deleteevent {
  success: boolean;
  message: string;
};

export interface ActionInput_google_findfreeslots {
  /**
   * List of calendar IDs to check for free/busy information. Example: ["primary", "work@example.com"]
   */
  calendarIds: string[];
  /**
   * Start of the time range in RFC3339 format. Example: "2024-03-15T09:00:00Z"
   */
  timeMin: string;
  /**
   * End of the time range in RFC3339 format. Example: "2024-03-15T17:00:00Z"
   */
  timeMax: string;
  /**
   * Minimum duration in minutes for a free slot to be returned. Example: 30
   */
  durationMinutes: number;
};

export interface ActionOutput_google_findfreeslots {
  /**
   * List of free time slots meeting the minimum duration
   */
  freeSlots: ({  /**
   * Start time of the free slot in RFC3339 format
   */
  start: string;
  /**
   * End time of the free slot in RFC3339 format
   */
  end: string;
  /**
   * Duration of the free slot in minutes
   */
  durationMinutes: number;})[];
  /**
   * Number of calendars checked
   */
  calendarsChecked: number;
};

export interface ActionInput_google_getevent {
  /**
   * Calendar identifier. Use "primary" for the primary calendar of the currently logged in user.
   */
  calendarId: string;
  /**
   * Event identifier.
   */
  eventId: string;
};

export interface ActionOutput_google_getevent {
  id: string;
  summary?: string | undefined;
  description?: string | undefined;
  location?: string | undefined;
  status?: string | undefined;
  htmlLink?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  start?: {  date?: string | undefined;
  dateTime?: string | undefined;
  timeZone?: string | undefined;};
  end?: {  date?: string | undefined;
  dateTime?: string | undefined;
  timeZone?: string | undefined;};
  creator?: {  id?: string | undefined;
  email?: string | undefined;
  displayName?: string | undefined;
  self?: boolean | undefined;};
  organizer?: {  id?: string | undefined;
  email?: string | undefined;
  displayName?: string | undefined;
  self?: boolean | undefined;};
};

export interface ActionInput_google_listcalendarlist {
  /**
   * Page token for pagination. Omit for first page.
   */
  cursor?: string | undefined;
  /**
   * Maximum number of calendars to return. Default: 100.
   */
  maxResults?: number | undefined;
};

export interface ActionOutput_google_listcalendarlist {
  calendars: ({  id: string;
  summary: string;
  description?: string | undefined;
  location?: string | undefined;
  timeZone?: string | undefined;
  accessRole?: string | undefined;
  primary?: boolean | undefined;
  selected?: boolean | undefined;
  backgroundColor?: string | undefined;
  foregroundColor?: string | undefined;
  hidden?: boolean | undefined;
  deleted?: boolean | undefined;})[];
  nextPageToken?: string | undefined;
};

export interface ActionInput_google_listevents {
  /**
   * Calendar identifier. Use "primary" for the primary calendar or a calendar ID from calendarList.list.
   */
  calendarId?: string | undefined;
  /**
   * Pagination cursor (nextPageToken from previous response). Omit for first page.
   */
  cursor?: string | undefined;
  /**
   * Maximum number of events to return per page (1-2500, default 250).
   */
  maxResults?: number | undefined;
  /**
   * Lower bound (exclusive) for an event's end time filter (RFC3339 timestamp).
   */
  timeMin?: string | undefined;
  /**
   * Upper bound (exclusive) for an event's start time filter (RFC3339 timestamp).
   */
  timeMax?: string | undefined;
  /**
   * Free text search terms to find matching events.
   */
  q?: string | undefined;
  /**
   * Whether to expand recurring events into single instances.
   */
  singleEvents?: boolean | undefined;
  /**
   * Whether to include cancelled/deleted events.
   */
  showDeleted?: boolean | undefined;
};

export interface ActionOutput_google_listevents {
  events: ({  id: string;
  summary?: string | undefined;
  description?: string | undefined;
  location?: string | undefined;
  start?: {  date: string;} | {  dateTime: string;
  timeZone?: string | undefined;};
  end?: {  date: string;} | {  dateTime: string;
  timeZone?: string | undefined;};
  status?: string | undefined;
  created?: string | undefined;
  updated?: string | undefined;
  organizer?: {  email?: string | undefined;
  displayName?: string | undefined;};
  attendees?: ({  email?: string | undefined;
  displayName?: string | undefined;
  responseStatus?: string | undefined;})[];
  recurringEventId?: string | undefined;
  transparency?: string | undefined;
  visibility?: string | undefined;})[];
  /**
   * Pagination cursor for next page. Omitted if no more pages.
   */
  nextPageToken?: string | undefined;
};

export interface ActionInput_google_listupcomingevents {
  /**
   * Calendar ID. Use "primary" for the main calendar or a specific calendar ID. Example: "primary"
   */
  calendarId?: string | undefined;
  /**
   * Pagination token from previous response. Omit for first page.
   */
  cursor?: string | undefined;
  /**
   * Maximum number of events to return per page (1-2500). Default: 250
   */
  limit?: number | undefined;
  /**
   * RFC3339 timestamp to fetch events from (e.g., "2026-03-12T00:00:00Z"). Defaults to current time if not provided.
   */
  timeMin?: string | undefined;
};

export interface ActionOutput_google_listupcomingevents {
  /**
   * List of upcoming events
   */
  events: ({  id: string;
  /**
   * Event title
   */
  summary?: string | undefined;
  /**
   * Event description
   */
  description?: string | undefined;
  /**
   * Event location
   */
  location?: string | undefined;
  /**
   * Start time
   */
  start: {  dateTime?: string | undefined;
  date?: string | undefined;
  timeZone?: string | undefined;};
  /**
   * End time
   */
  end: {  dateTime?: string | undefined;
  date?: string | undefined;
  timeZone?: string | undefined;};
  /**
   * Event status (confirmed, tentative, cancelled)
   */
  status: string;
  /**
   * Link to event in Google Calendar
   */
  htmlLink?: string | undefined;
  /**
   * When the event was created
   */
  created?: string | undefined;
  /**
   * When the event was last updated
   */
  updated?: string | undefined;
  creator?: {  email?: string | undefined;
  displayName?: string | undefined;};
  organizer?: {  email?: string | undefined;
  displayName?: string | undefined;};
  attendees?: ({  email?: string | undefined;
  displayName?: string | undefined;
  responseStatus?: string | undefined;})[];})[];
  /**
   * Token for fetching the next page. Omitted if no more pages.
   */
  nextPageToken?: string | undefined;
};

export interface ActionInput_google_queryfreebusy {
  /**
   * The start of the interval for the query formatted as per RFC3339. Example: "2024-01-01T00:00:00Z"
   */
  timeMin: string;
  /**
   * The end of the interval for the query formatted as per RFC3339. Example: "2024-01-02T00:00:00Z"
   */
  timeMax: string;
  /**
   * Time zone used in the response. The default is UTC. Example: "UTC"
   */
  timeZone?: string | undefined;
  /**
   * Maximal number of calendar identifiers to be provided for a single group. Maximum value is 100.
   */
  groupExpansionMax?: number | undefined;
  /**
   * Maximal number of calendars for which FreeBusy information is to be provided. Maximum value is 50.
   */
  calendarExpansionMax?: number | undefined;
  /**
   * List of calendars and/or groups to query
   */
  items: ({  /**
   * The identifier of a calendar or a group
   */
  id: string;})[];
};

export interface ActionOutput_google_queryfreebusy {
  kind: string;
  timeMin: string;
  timeMax: string;
  groups?: {  [key: string]: {  errors?: ({  domain: string;
  reason: string;})[] | undefined;
  calendars: string[];};};
  calendars: {  [key: string]: {  errors?: ({  domain: string;
  reason: string;})[] | undefined;
  busy: ({  start: string;
  end: string;})[];};};
};

export interface ActionInput_google_quickaddevent {
  /**
   * Calendar identifier. Use "primary" for the primary calendar. Example: "primary"
   */
  calendarId?: string | undefined;
  /**
   * The text describing the event to be created. Example: "Meeting with John tomorrow at 2pm"
   */
  text: string;
  /**
   * Guests who should receive notifications about the creation of the new event. Acceptable values: "all", "externalOnly", "none".
   */
  sendUpdates?: 'all' | 'externalOnly' | 'none' | undefined;
};

export interface ActionOutput_google_quickaddevent {
  /**
   * The unique ID of the event.
   */
  id: string;
  /**
   * The title of the event.
   */
  summary?: string | undefined;
  /**
   * The description of the event.
   */
  description?: string | undefined;
  /**
   * The start time of the event.
   */
  start: {  dateTime?: string | undefined;
  date?: string | undefined;
  timeZone?: string | undefined;};
  /**
   * The end time of the event.
   */
  end: {  dateTime?: string | undefined;
  date?: string | undefined;
  timeZone?: string | undefined;};
  /**
   * A link to the event in Google Calendar.
   */
  htmlLink?: string | undefined;
  /**
   * The creation time of the event.
   */
  created?: string | undefined;
  /**
   * The last modification time of the event.
   */
  updated?: string | undefined;
  /**
   * The status of the event.
   */
  status?: string | undefined;
  /**
   * The creator of the event.
   */
  creator?: {  email?: string | undefined;
  displayName?: string | undefined;};
  /**
   * The organizer of the event.
   */
  organizer?: {  email?: string | undefined;
  displayName?: string | undefined;};
};

export interface ActionInput_google_removeattendee {
  /**
   * Calendar identifier. Use "primary" for the primary calendar of the currently logged in user.
   */
  calendarId: string;
  /**
   * Event identifier.
   */
  eventId: string;
  /**
   * Email address of the attendee to remove from the event.
   */
  attendeeEmail: string;
};

export interface ActionOutput_google_removeattendee {
  id: string;
  summary?: string | undefined;
  attendees: ({  email: string;
  displayName?: string | undefined;
  organizer?: boolean | undefined;
  self?: boolean | undefined;
  resource?: boolean | undefined;
  optional?: boolean | undefined;
  responseStatus?: string | undefined;
  comment?: string | undefined;
  additionalGuests?: number | undefined;})[];
  removedAttendee?: {  email: string;
  displayName?: string | undefined;
  organizer?: boolean | undefined;
  self?: boolean | undefined;
  resource?: boolean | undefined;
  optional?: boolean | undefined;
  responseStatus?: string | undefined;
  comment?: string | undefined;
  additionalGuests?: number | undefined;};
  success: boolean;
};

export interface ActionInput_google_updateevent {
  /**
   * Calendar identifier. Use "primary" for the main calendar
   */
  calendarId: string;
  /**
   * Event identifier
   */
  eventId: string;
  /**
   * Title of the event
   */
  summary?: string | undefined;
  /**
   * Description of the event
   */
  description?: string | undefined;
  /**
   * Geographic location of the event
   */
  location?: string | undefined;
  /**
   * Start time of the event
   */
  start?: {  /**
   * Date in yyyy-mm-dd format for all-day events
   */
  date?: string | undefined;
  /**
   * DateTime in RFC3339 format for timed events
   */
  dateTime?: string | undefined;
  /**
   * Time zone (IANA format, e.g., "Europe/Zurich")
   */
  timeZone?: string | undefined;};
  /**
   * End time of the event
   */
  end?: {  /**
   * Date in yyyy-mm-dd format for all-day events
   */
  date?: string | undefined;
  /**
   * DateTime in RFC3339 format for timed events
   */
  dateTime?: string | undefined;
  /**
   * Time zone (IANA format, e.g., "Europe/Zurich")
   */
  timeZone?: string | undefined;};
  /**
   * Attendees of the event
   */
  attendees?: ({  id?: string | undefined;
  email?: string | undefined;
  displayName?: string | undefined;
  organizer?: boolean | undefined;
  self?: boolean | undefined;
  resource?: boolean | undefined;
  optional?: boolean | undefined;
  responseStatus?: 'needsAction' | 'declined' | 'tentative' | 'accepted' | undefined;
  comment?: string | undefined;
  additionalGuests?: number | undefined;})[];
  /**
   * Status of the event
   */
  status?: 'confirmed' | 'tentative' | 'cancelled' | undefined;
  /**
   * Visibility of the event
   */
  visibility?: 'default' | 'public' | 'private' | 'confidential' | undefined;
  /**
   * Color ID of the event
   */
  colorId?: string | undefined;
  /**
   * Reminders for the event
   */
  reminders?: {  useDefault?: boolean | undefined;
  overrides?: ({  method: 'email' | 'popup';
  minutes: number;})[] | undefined;};
  /**
   * Who should receive notifications about the event update
   */
  sendUpdates?: 'all' | 'externalOnly' | 'none' | undefined;
};

export interface ActionOutput_google_updateevent {
  id: string;
  summary?: string | undefined;
  description?: string | undefined;
  location?: string | undefined;
  start?: {  /**
   * Date in yyyy-mm-dd format for all-day events
   */
  date?: string | undefined;
  /**
   * DateTime in RFC3339 format for timed events
   */
  dateTime?: string | undefined;
  /**
   * Time zone (IANA format, e.g., "Europe/Zurich")
   */
  timeZone?: string | undefined;};
  end?: {  /**
   * Date in yyyy-mm-dd format for all-day events
   */
  date?: string | undefined;
  /**
   * DateTime in RFC3339 format for timed events
   */
  dateTime?: string | undefined;
  /**
   * Time zone (IANA format, e.g., "Europe/Zurich")
   */
  timeZone?: string | undefined;};
  status?: string | undefined;
  visibility?: string | undefined;
  htmlLink?: string | undefined;
  created?: string | undefined;
  updated?: string | undefined;
  organizer?: {  id?: string | undefined;
  email?: string | undefined;
  displayName?: string | undefined;
  self?: boolean | undefined;};
  attendees?: ({  id?: string | undefined;
  email?: string | undefined;
  displayName?: string | undefined;
  organizer?: boolean | undefined;
  self?: boolean | undefined;
  resource?: boolean | undefined;
  optional?: boolean | undefined;
  responseStatus?: 'needsAction' | 'declined' | 'tentative' | 'accepted' | undefined;
  comment?: string | undefined;
  additionalGuests?: number | undefined;})[];
};

export interface ActionInput_google_findfile {
  /**
   * Search query string. Uses Google Drive search query syntax. Example: "name contains 'report'" or "mimeType = 'application/pdf'". If not provided, returns all files.
   */
  query?: string | undefined;
  /**
   * Pagination cursor (nextPageToken) from previous response. Omit for first page.
   */
  cursor?: string | undefined;
  /**
   * Maximum number of files to return per page. Default is 100.
   */
  pageSize?: number | undefined;
};

export interface ActionOutput_google_findfile {
  files: ({  id: string;
  name: string;
  mimeType: string;
  modifiedTime?: string | undefined;
  size?: string | undefined;
  webViewLink?: string | undefined;})[];
  /**
   * Pagination cursor for the next page. Omitted if no more results.
   */
  nextPageToken?: string | undefined;
  /**
   * Total number of files returned in this page
   */
  totalResults?: number | undefined;
};

export interface ActionInput_google_findfolder {
  /**
   * Folder name or search query to find folders by name. Example: "Test Folder Alpha"
   */
  name: string;
};

export interface ActionOutput_google_findfolder {
  folders: ({  id: string;
  name: string;
  createdTime?: string | undefined;})[];
  totalCount: number;
};

export interface ActionInput_google_createfolder {
  /**
   * The name of the new folder. Example: "My New Folder"
   */
  name: string;
  /**
   * The ID of the parent folder where the new folder will be created. If omitted, the folder is created in the root of the drive. Example: "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgvE2upms"
   */
  parentId?: string | undefined;
};

export interface ActionOutput_google_createfolder {
  /**
   * The unique identifier of the created folder.
   */
  id: string;
  /**
   * The name of the created folder.
   */
  name: string;
  /**
   * The MIME type of the folder (always application/vnd.google-apps.folder).
   */
  mimeType: string;
  /**
   * The timestamp when the folder was created.
   */
  createdTime: string;
  /**
   * Array of parent folder IDs.
   */
  parentIds: string[];
};

export interface ActionInput_google_uploaddocument {
  /**
   * The name of the file to create. Example: "document.txt"
   */
  name: string;
  /**
   * The file content as plain text or base64 encoded string
   */
  content: string;
  /**
   * The MIME type of the file. Example: "text/plain", "application/pdf"
   */
  mimeType: string;
  /**
   * Whether the content is base64 encoded. Defaults to false
   */
  isBase64?: boolean | undefined;
  /**
   * The ID of the folder to upload the file into. If not provided, defaults to root. Example: "1a2b3c4d5e6f7g8h"
   */
  folderId?: string | undefined;
  /**
   * A description of the file
   */
  description?: string | undefined;
};

export interface ActionOutput_google_uploaddocument {
  /**
   * The ID of the created file
   */
  id: string;
  /**
   * The name of the created file
   */
  name: string;
  /**
   * The MIME type of the file
   */
  mimeType: string;
  /**
   * A link for opening the file in a relevant Google editor or viewer
   */
  webViewLink?: string | undefined;
  /**
   * A link for downloading the content of the file in a browser
   */
  webContentLink?: string | undefined;
};

export interface ActionInput_google_copyfile {
  /**
   * The ID of the file to copy. Example: "123abc"
   */
  fileId: string;
  /**
   * The new name for the copied file. If not provided, the original name is used.
   */
  name?: string | undefined;
  /**
   * The ID of the folder where the copy should be placed. If not provided, the copy is placed in the same folder as the original.
   */
  destinationFolderId?: string | undefined;
};

export interface ActionOutput_google_copyfile {
  /**
   * The ID of the copied file
   */
  id: string;
  /**
   * The name of the copied file
   */
  name: string;
  /**
   * The MIME type of the copied file
   */
  mimeType: string;
  /**
   * The creation time of the copied file (RFC 3339)
   */
  createdTime?: string | undefined;
};

export interface ActionInput_google_movefile {
  /**
   * The ID of the file to move. Example: "1mD3ukEAmRqo8u0RF_Cr6IJl9f_uWTYH03vesDhB5Svw"
   */
  fileId: string;
  /**
   * The ID of the current parent folder. Example: "1SpnQKJHqNDh-qhbj_zGD2aIm-G-RKC_k"
   */
  fromFolderId: string;
  /**
   * The ID of the destination folder. Example: "1Bl1rB7hkBbdzmKUka3zSj0bhAK3pGypD"
   */
  toFolderId: string;
};

export interface ActionOutput_google_movefile {
  id: string;
  name?: string | undefined;
  mimeType?: string | undefined;
  parents: string[];
};

export interface ActionInput_google_deletefile {
  /**
   * The ID of the file or folder to delete. Example: "1aBcDeFgHiJkLmNoPqRsTuVwXyZ123456"
   */
  fileId: string;
};

export interface ActionOutput_google_deletefile {
  /**
   * Whether the file was successfully deleted
   */
  success: boolean;
  /**
   * The ID of the deleted file
   */
  fileId: string;
};

export interface ActionInput_google_listfilesnonunified {
  /**
   * Folder ID to list contents. Omit for root folder.
   */
  folderId?: string | undefined;
  /**
   * Pagination cursor (pageToken) from previous response. Omit for first page.
   */
  cursor?: string | undefined;
  /**
   * Maximum number of files to return. Default: 100.
   */
  limit?: number | undefined;
  /**
   * Include items from shared drives. Default: false.
   */
  includeSharedDrives?: boolean | undefined;
};

export interface ActionOutput_google_listfilesnonunified {
  files: ({  id: string;
  name: string;
  mimeType: string;
  isFolder: boolean;
  parentId?: string | undefined;
  createdTime?: string | undefined;
  modifiedTime?: string | undefined;
  size?: number | undefined;
  webViewLink?: string | undefined;
  thumbnailLink?: string | undefined;})[];
  /**
   * Cursor for next page. Omitted if no more pages.
   */
  nextPageToken?: string | undefined;
  /**
   * Total number of files in this page.
   */
  totalCount: number;
};

export interface ActionInput_google_sendemail {
  /**
   * Sender email address
   */
  from: string;
  /**
   * Recipient email address
   */
  to: string;
  /**
   * Email subject line
   */
  subject: string;
  /**
   * Email body (plain text)
   */
  body: string;
  /**
   * Optional additional email headers (e.g. Cc, Bcc, Reply-To)
   */
  headers?: {  [key: string]: string;} | undefined;
};

export interface ActionOutput_google_sendemail {
  id: string;
  threadId: string;
};

export interface ActionInput_google_fetchattachment {
  /**
   * The ID of the message containing the attachment
   */
  messageId: string;
  /**
   * The ID of the attachment to fetch
   */
  attachmentId: string;
};

export interface ActionOutput_google_fetchattachment {
  /**
   * Base64-encoded attachment content
   */
  data: string;
  /**
   * Attachment size in bytes
   */
  size?: number | undefined;
};
