import type { TemplateCapability } from '@contracts/template-composition'

export const WEB3_CAPABILITIES = {
  priceRead: 'web3.price.read',
  tokenRiskRead: 'web3.token.risk.read',
  tokenHoldersRead: 'web3.token.holders.read',
  tokenLiquidityRead: 'web3.token.liquidity.read',
  trendingRead: 'web3.trending.read',
  walletBalanceRead: 'web3.wallet.balance.read',
  walletHistoryRead: 'web3.wallet.history.read',
  portfolioRead: 'web3.portfolio.read',
  predictionRead: 'web3.prediction.read',
  predictionAutomationManage: 'web3.prediction.automation.manage',
  predictionTradeExecute: 'web3.prediction.trade.execute',
  swapExecute: 'web3.swap.execute',
  transferExecute: 'web3.transfer.execute',
  perpsExecute: 'web3.perps.execute',
} as const

export type Web3CapabilityKey = typeof WEB3_CAPABILITIES[keyof typeof WEB3_CAPABILITIES]

export const WEB3_CAPABILITY_DEFINITIONS: Record<Web3CapabilityKey, TemplateCapability> = {
  [WEB3_CAPABILITIES.priceRead]: {
    key: WEB3_CAPABILITIES.priceRead,
    kind: 'web3_read',
    name: 'Read token prices',
    description: 'Fetch live token price and quote data.',
    scope: 'project',
    risk: 'read_only',
    progress: { phase: 'fetching', label: 'Checking live prices' },
  },
  [WEB3_CAPABILITIES.tokenRiskRead]: {
    key: WEB3_CAPABILITIES.tokenRiskRead,
    kind: 'web3_read',
    name: 'Read token risk',
    description: 'Inspect token contracts, liquidity, and common risk signals.',
    scope: 'project',
    risk: 'read_only',
    progress: { phase: 'fetching', label: 'Checking token risk' },
  },
  [WEB3_CAPABILITIES.tokenHoldersRead]: {
    key: WEB3_CAPABILITIES.tokenHoldersRead,
    kind: 'web3_read',
    name: 'Read token holders',
    description: 'Read holder concentration and wallet distribution signals.',
    scope: 'project',
    risk: 'read_only',
    progress: { phase: 'fetching', label: 'Checking token holders' },
  },
  [WEB3_CAPABILITIES.tokenLiquidityRead]: {
    key: WEB3_CAPABILITIES.tokenLiquidityRead,
    kind: 'web3_read',
    name: 'Read token liquidity',
    description: 'Read pool liquidity and market depth for a token.',
    scope: 'project',
    risk: 'read_only',
    progress: { phase: 'fetching', label: 'Checking token liquidity' },
  },
  [WEB3_CAPABILITIES.trendingRead]: {
    key: WEB3_CAPABILITIES.trendingRead,
    kind: 'web3_read',
    name: 'Read trending tokens',
    description: 'Fetch trending tokens and current market attention.',
    scope: 'project',
    risk: 'read_only',
    progress: { phase: 'fetching', label: 'Checking trending tokens' },
  },
  [WEB3_CAPABILITIES.walletBalanceRead]: {
    key: WEB3_CAPABILITIES.walletBalanceRead,
    kind: 'web3_read',
    name: 'Read wallet balances',
    description: 'Fetch balances and holdings for tracked wallets.',
    scope: 'project',
    risk: 'read_only',
    progress: { phase: 'fetching', label: 'Checking wallet balances' },
  },
  [WEB3_CAPABILITIES.walletHistoryRead]: {
    key: WEB3_CAPABILITIES.walletHistoryRead,
    kind: 'web3_read',
    name: 'Read wallet history',
    description: 'Fetch wallet activity, transfers, and transaction history.',
    scope: 'project',
    risk: 'read_only',
    progress: { phase: 'fetching', label: 'Checking wallet activity' },
  },
  [WEB3_CAPABILITIES.portfolioRead]: {
    key: WEB3_CAPABILITIES.portfolioRead,
    kind: 'web3_read',
    name: 'Read portfolio risk',
    description: 'Analyze portfolio exposure, risk, and PnL.',
    scope: 'project',
    risk: 'read_only',
    progress: { phase: 'fetching', label: 'Reading portfolio exposure' },
  },
  [WEB3_CAPABILITIES.predictionRead]: {
    key: WEB3_CAPABILITIES.predictionRead,
    kind: 'web3_read',
    name: 'Read prediction markets',
    description: 'Fetch prediction-market questions, odds, and liquidity.',
    scope: 'project',
    risk: 'read_only',
    progress: { phase: 'fetching', label: 'Reading prediction markets' },
  },
  [WEB3_CAPABILITIES.predictionAutomationManage]: {
    key: WEB3_CAPABILITIES.predictionAutomationManage,
    kind: 'web3_trade',
    name: 'Manage prediction-market automation',
    description: 'Create or update monitored prediction-market automation.',
    scope: 'agent',
    risk: 'medium',
    progress: { phase: 'tool_running', label: 'Checking prediction automation' },
  },
  [WEB3_CAPABILITIES.predictionTradeExecute]: {
    key: WEB3_CAPABILITIES.predictionTradeExecute,
    kind: 'web3_trade',
    name: 'Execute prediction-market trades',
    description: 'Prepare and execute prediction-market trades behind policy gates.',
    scope: 'agent',
    risk: 'high',
    progress: { phase: 'approval_waiting', label: 'Preparing prediction-market trade' },
  },
  [WEB3_CAPABILITIES.swapExecute]: {
    key: WEB3_CAPABILITIES.swapExecute,
    kind: 'web3_trade',
    name: 'Execute token swaps',
    description: 'Prepare token swaps behind policy and approval gates.',
    scope: 'agent',
    risk: 'high',
    progress: { phase: 'approval_waiting', label: 'Preparing swap' },
  },
  [WEB3_CAPABILITIES.transferExecute]: {
    key: WEB3_CAPABILITIES.transferExecute,
    kind: 'web3_trade',
    name: 'Execute wallet transfers',
    description: 'Prepare transfers or bridges behind policy and approval gates.',
    scope: 'agent',
    risk: 'high',
    progress: { phase: 'approval_waiting', label: 'Preparing transfer' },
  },
  [WEB3_CAPABILITIES.perpsExecute]: {
    key: WEB3_CAPABILITIES.perpsExecute,
    kind: 'web3_trade',
    name: 'Execute perpetual orders',
    description: 'Prepare perpetual orders behind trading policy and approval gates.',
    scope: 'agent',
    risk: 'high',
    progress: { phase: 'approval_waiting', label: 'Preparing perps order' },
  },
}

export function web3Capability(key: Web3CapabilityKey): TemplateCapability {
  return WEB3_CAPABILITY_DEFINITIONS[key]
}
