import os

path = os.path.join(r'c:\docs', 'docs', 'TRANSFORMATION_PLAN.md')
os.makedirs(os.path.dirname(path), exist_ok=True)

content = r"""# Lucid Documentation — Full Transformation Plan

> Transform `C:\docs` from Mintlify starter kit → production Lucid documentation

## Executive Summary

The `raijinlabs/docs` repo currently contains the **default Mintlify starter kit**. This plan transforms it into the official **LucidLayer API** documentation site, powered by the real OpenAPI spec from `raijin-labs-lucid-ai` SDK.

**API Surface**: 65+ endpoints across 9 groups (Passports, Match, Run, Receipts, Epochs, Payouts, Compute, Health, Agents)
**SDK**: `raijin-labs-lucid-ai` (TypeScript, generated by Speakeasy)
**Base URL**: `https://api.lucid.foundation`

---

## Phase 0: Branding & Config (30 min)

### 0.1 Update `docs.json`

Replace the entire Mintlify starter config with Lucid-specific navigation:

- **Name**: "Lucid Documentation"
- **Colors**: Indigo theme (`#6366F1` primary, `#818CF8` light, `#4F46E5` dark)
- **Navigation tabs**: Guides + API Reference
- **Guides tab groups**: Getting Started, Core Concepts, Guides, SDKs, AI Tools
- **API Reference tab groups**: Overview, Passports, Inference, Receipts, Epochs, Payouts, Compute, Agents, Health
- **Navbar**: Dashboard link → `https://app.lucid.foundation`
- **Footer**: Raijin Labs socials
- **OpenAPI**: Point to `api-reference/openapi.json`

### 0.2 Replace Logos
- Replace `logo/light.svg` and `logo/dark.svg` with Lucid/Raijin Labs logos
- Replace `favicon.svg` with Lucid favicon

### 0.3 Convert OpenAPI YAML → JSON
- Convert downloaded `openapi-spec.yaml` to `api-reference/openapi.json`
- Mintlify auto-generates all API reference pages from this spec
- Code samples are embedded in spec via `x-codeSamples`

---

## Phase 1: Core Pages — Guides Tab (2-3 hours)

### 1.1 Homepage (`index.mdx`)

Replace starter kit with Lucid product overview:
- What is LucidLayer? (verifiable AI inference protocol)
- Feature cards: Passports, Inference, Receipts, Epochs, Payouts, Agents
- Links to quickstart and API reference

### 1.2 Quickstart (`quickstart.mdx`)

2-minute quickstart:
1. Install SDK (`npm install raijin-labs-lucid-ai`)
2. List passports
3. Run chat completion
4. Explain what happened (routing, receipt, anchoring)

### 1.3 Authentication (`authentication.mdx`)
- API key management
- `X-Owner-Address` header for passport ownership
- SDK authentication setup

### 1.4 SDK Installation (`sdk-installation.mdx`)
- TypeScript SDK setup (`raijin-labs-lucid-ai`)
- REST API direct usage (curl examples)
- Future: Python SDK

### 1.5 Concept Pages (`concepts/` directory)

| File | Content |
|------|---------|
| `concepts/passports.mdx` | Identity types (model/compute/tool/dataset/agent), lifecycle (active/deprecated/revoked), metadata, tags, ownership |
| `concepts/inference.mdx` | Chat completions, policy-based routing, match/explain, fallback logic, streaming |
| `concepts/receipts.mdx` | Cryptographic receipts, MMR (Merkle Mountain Range), hash verification, signature verification, inclusion proofs |
| `concepts/epochs.mdx` | Epoch lifecycle (open→anchoring→anchored), Solana anchoring, batch verification, stats |
| `concepts/agents.mdx` | Agent init, epoch tracking, planning, accomplish/execute, orchestrator architecture |

### 1.6 Guide Pages (`guides/` directory)

| File | Content |
|------|---------|
| `guides/first-inference.mdx` | Step-by-step: create passport → run inference → verify receipt |
| `guides/passport-management.mdx` | CRUD operations, filtering, tagging, stats |
| `guides/verifiable-receipts.mdx` | Create receipt → get proof → verify on-chain |
| `guides/agent-orchestration.mdx` | Init agent → plan → accomplish → verify |
| `guides/compute-providers.mdx` | Register compute node → heartbeat → health monitoring |

### 1.7 SDK Pages (`sdks/` directory)

| File | Content |
|------|---------|
| `sdks/typescript.mdx` | Full TypeScript SDK reference with all method groups |
| `sdks/python.mdx` | Placeholder ("Coming soon") |
| `sdks/rest.mdx` | Raw REST API usage with curl examples |

---

## Phase 2: API Reference — Auto-Generated (1 hour)

### 2.1 Convert and Place OpenAPI Spec

1. Convert `openapi-spec.yaml` → `api-reference/openapi.json`
2. Mintlify auto-generates interactive endpoint pages
3. Each endpoint gets: description, parameters, request/response schemas, code samples

### 2.2 API Introduction Page (`api-reference/introduction.mdx`)

Content:
- Base URL: `https://api.lucid.foundation`
- Authentication: Bearer token
- API groups table (9 groups, 65+ endpoints)
- SDK installation
- Rate limits table

### 2.3 Custom Endpoint Pages (Optional Overrides)

For key endpoints, create custom MDX with richer examples:

| Custom Page | Why |
|------------|-----|
| `api-reference/inference/chat-completions.mdx` | Core product feature |
| `api-reference/passports/create.mdx` | Most common first action |
| `api-reference/receipts/verify.mdx` | Key differentiator |
| `api-reference/agents/accomplish.mdx` | Agent orchestration entry point |

---

## Phase 3: Delete Starter Kit Content (15 min)

### Files to Delete

```
essentials/code.mdx
essentials/images.mdx
essentials/markdown.mdx
essentials/navigation.mdx
essentials/reusable-snippets.mdx
essentials/settings.mdx
snippets/snippet-intro.mdx
images/hero-dark.png
images/hero-light.png
images/checks-passed.png
development.mdx
```

### Files to Keep/Update

```
ai-tools/cursor.mdx           ← Update with Lucid MCP server config
ai-tools/claude-code.mdx      ← Update with Lucid-specific usage
ai-tools/windsurf.mdx         ← Update with Lucid-specific integration
```

---

## Phase 4: Target Directory Structure

```
c:\docs/
├── docs.json                          # Updated config
├── index.mdx                          # Lucid homepage
├── quickstart.mdx                     # 2-minute quickstart
├── authentication.mdx                 # Auth guide
├── sdk-installation.mdx               # SDK setup
│
├── concepts/                          # Core concepts
│   ├── passports.mdx
│   ├── inference.mdx
│   ├── receipts.mdx
│   ├── epochs.mdx
│   └── agents.mdx
│
├── guides/                            # How-to guides
│   ├── first-inference.mdx
│   ├── passport-management.mdx
│   ├── verifiable-receipts.mdx
│   ├── agent-orchestration.mdx
│   └── compute-providers.mdx
│
├── sdks/                              # SDK references
│   ├── typescript.mdx
│   ├── python.mdx
│   └── rest.mdx
│
├── ai-tools/                          # AI tool integration (keep)
│   ├── cursor.mdx
│   ├── claude-code.mdx
│   └── windsurf.mdx
│
├── api-reference/                     # API docs
│   ├── introduction.mdx               # API overview
│   ├── openapi.json                   # Converted from YAML spec
│   └── (auto-generated endpoint pages)
│
├── logo/                              # Brand logos
├── images/                            # Documentation images
├── favicon.svg
├── memory-bank/                       # AI context (keep)
├── .clinerules/                       # Cline rules (keep)
└── docs/                              # Deep-dive docs
```

---

## Phase 5: Implementation Sprints

### Sprint 1 — MVP (P0, ~4 hours)
1. `docs.json` — Full config update
2. `api-reference/openapi.json` — Convert YAML → JSON
3. `index.mdx` — New homepage
4. `quickstart.mdx` — 2-minute quickstart
5. `authentication.mdx` — Auth guide
6. `api-reference/introduction.mdx` — API overview
7. `concepts/passports.mdx` — Core concept
8. `concepts/inference.mdx` — Core concept
9. `sdks/typescript.mdx` — SDK reference
10. `guides/first-inference.mdx` — Tutorial
11. Delete `essentials/` and `snippets/` directories

**Result**: Functional docs site with quickstart, core concepts, API reference, and SDK guide.

### Sprint 2 — Complete Guides (P1, ~3 hours)
12. `sdk-installation.mdx`
13. `concepts/receipts.mdx`
14. `concepts/epochs.mdx`
15. `concepts/agents.mdx`
16. `guides/passport-management.mdx`
17. `guides/verifiable-receipts.mdx`
18. `sdks/rest.mdx`
19. Update AI tools pages

### Sprint 3 — Polish (P2-P3, ~2 hours)
20. `guides/agent-orchestration.mdx`
21. `guides/compute-providers.mdx`
22. Custom endpoint override pages
23. `sdks/python.mdx` (placeholder)
24. Add architecture diagrams
25. Update memory bank

---

## API Endpoint Summary (from OpenAPI spec)

### Passports (8 endpoints)
| Method | Path | Operation |
|--------|------|-----------|
| POST | `/v1/passports` | Create passport |
| GET | `/v1/passports` | List passports |
| GET | `/v1/passports/{id}` | Get passport |
| PATCH | `/v1/passports/{id}` | Update passport |
| DELETE | `/v1/passports/{id}` | Delete (soft) |
| POST | `/v1/passports/{id}/sync` | Trigger sync |
| GET | `/v1/passports/pending-sync` | List pending syncs |
| GET | `/v1/passports/stats` | Passport stats |

### Inference (5 endpoints)
| Method | Path | Operation |
|--------|------|-----------|
| POST | `/v1/chat/completions` | Chat completions (OpenAI-compatible) |
| POST | `/v1/run/inference` | Run inference |
| POST | `/v1/match` | Match model to request |
| POST | `/v1/match/explain` | Match with explanation |
| POST | `/v1/route` | Route request |

### Convenience Aliases (5 endpoints)
| Method | Path | Operation |
|--------|------|-----------|
| GET | `/v1/models` | List model passports |
| GET | `/v1/compute` | List compute passports |
| GET | `/v1/tools` | List tool passports |
| GET | `/v1/datasets` | List dataset passports |
| GET | `/v1/agents` | List agent passports |

### Receipts (9 endpoints)
| Method | Path | Operation |
|--------|------|-----------|
| POST | `/v1/receipts` | Create receipt |
| GET | `/v1/receipts/{id}` | Get receipt |
| POST | `/v1/receipts/{id}/verify` | Verify receipt |
| GET | `/v1/receipts/{id}/proof` | Get Merkle proof |
| GET | `/v1/verify/{hash}` | Verify by hash |
| GET | `/v1/mmr/root` | Get MMR root |
| GET | `/v1/signer/pubkey` | Get signer public key |
| POST | `/v1/receipts/commit-root` | Commit MMR root |
| POST | `/v1/receipts/commit-roots-batch` | Batch commit |

### Epochs (8 endpoints)
| Method | Path | Operation |
|--------|------|-----------|
| GET | `/v1/epochs/current` | Current epoch |
| GET | `/v1/epochs` | List epochs |
| GET | `/v1/epochs/{id}` | Get epoch |
| POST | `/v1/epochs/{id}/retry` | Retry anchoring |
| POST | `/v1/epochs/{id}/verify` | Verify epoch |
| GET | `/v1/epochs/{id}/transaction` | Get anchor tx |
| GET | `/v1/epochs/ready` | Epochs ready to anchor |
| GET | `/v1/epochs/stats` | Epoch statistics |

### Payouts (4 endpoints)
| Method | Path | Operation |
|--------|------|-----------|
| POST | `/v1/payouts/calculate` | Calculate payout splits |
| POST | `/v1/payouts/from-receipt` | Calculate from receipt |
| GET | `/v1/payouts/{run_id}` | Get payout |
| GET | `/v1/payouts/{run_id}/verify` | Verify payout |

### Compute (2 endpoints)
| Method | Path | Operation |
|--------|------|-----------|
| POST | `/v1/compute/nodes/heartbeat` | Node heartbeat |
| GET | `/v1/compute/nodes/{id}/health` | Node health |

### Health (7 endpoints)
| Method | Path | Operation |
|--------|------|-----------|
| GET | `/health` | System health |
| GET | `/health/live` | Liveness probe |
| GET | `/health/ready` | Readiness probe |
| GET | `/health/database` | Database health |
| GET | `/health/redis` | Redis health |
| GET | `/health/nango` | Nango health |
| GET | `/health/detailed` | Detailed health |

### Agents (14+ endpoints)
| Method | Path | Operation |
|--------|------|-----------|
| POST | `/api/agents/init` | Initialize agent MMR |
| POST | `/api/agents/epoch` | Submit agent epoch |
| POST | `/api/agents/batch-epochs` | Batch submit epochs |
| POST | `/api/agents/proof` | Generate agent proof |
| GET | `/api/agents/{id}/stats` | Agent stats |
| GET | `/api/agents/{id}/history` | Agent history |
| GET | `/api/agents/{id}/root` | Agent MMR root |
| POST | `/api/agents/{id}/verify` | Verify agent |
| GET | `/api/agents` | List agents |
| POST | `/api/agents/plan` | Plan agent goal |
| POST | `/api/agents/accomplish` | Accomplish goal |
| GET | `/api/agents/accomplish/preview` | Preview |
| POST | `/api/agents/execute` | Execute plan |
| POST | `/api/agents/validate` | Validate execution |
| + more | orchestrator health, planner info, executor | |

---

## Key References

- **OpenAPI spec source**: `https://raw.githubusercontent.com/raijinlabs/lucid-ai-sdk/main/openapi-with-code-samples.yaml`
- **Local copy**: `c:\docs\openapi-spec.yaml`
- **SDK package**: `raijin-labs-lucid-ai` (TypeScript, Speakeasy-generated)
- **Production API**: `https://api.lucid.foundation`
- **Code samples**: Embedded in OpenAPI spec via `x-codeSamples`
- **Mintlify auto-renders** code samples from the spec
"""

with open(path, 'w', encoding='utf-8') as f:
    f.write(content)

print(f'Created: {path}')
print(f'Size: {len(content)} bytes')