import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import {
  AGENT_OPS_CAPABILITY_SOURCE_VERSION,
  listAgentOpsBuiltinSkillSources,
  listAgentOpsCapabilityNamespaces,
  listAgentOpsChannelCapabilities,
  listAgentOpsProductCapabilities,
  listAgentOpsRuntimeProfiles,
} from '../src/lib/agent-ops/capability-source'
import {
  buildAgentOpsExternalHostInstallerManifest,
  buildAgentOpsExternalHostPackManifest,
  listAgentOpsExternalHostPacks,
  renderAgentOpsExternalHostInstructions,
} from '../src/lib/agent-ops/external-host-packs'

const root = process.cwd()
const checkOnly = process.argv.includes('--check')
const integrationSkillRoot = join(root, 'worker/src/agent/skills/integrations')

function table(headers: string[], rows: string[][]): string {
  const header = `| ${headers.join(' | ')} |`
  const separator = `| ${headers.map(() => '---').join(' | ')} |`
  return [header, separator, ...rows.map((row) => `| ${row.map(escapeCell).join(' | ')} |`)].join('\n')
}

function escapeCell(value: string): string {
  return value.replace(/\|/g, '\\|').replace(/\n/g, '<br>')
}

function generatedHeader(title: string): string {
  return [
    '<!-- generated by scripts/generate-agent-ops-capability-docs.ts; do not edit by hand -->',
    `# ${title}`,
    '',
    `Source version: \`${AGENT_OPS_CAPABILITY_SOURCE_VERSION}\``,
    '',
  ].join('\n')
}

function integrationProviders(): string[] {
  if (!existsSync(integrationSkillRoot)) {
    return []
  }

  return readdirSync(integrationSkillRoot, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort((a, b) => a.localeCompare(b))
}

function renderSkillSource(sourceRef: string): string {
  if (sourceRef === 'agent-skills:builtin-skills') {
    return 'worker/src/agent/skills/builtin-skills.ts'
  }

  return sourceRef
}

function buildCapabilityMatrixDoc(): string {
  const runtimeRows = listAgentOpsRuntimeProfiles().map((profile) => [
    profile.label,
    profile.deploymentModel,
    profile.supportedEngines.join(', '),
    profile.pulseContract,
    profile.channelOwnership.join(', '),
    profile.browserQa,
    profile.memory,
    profile.projectLearnings,
    profile.notes,
  ])

  const channelRows = listAgentOpsChannelCapabilities().map((channel) => [
    channel.label,
    channel.hosted,
    channel.managedOutbound,
    channel.runtimeNative,
    channel.agentSwitching,
    channel.aliasesAndDefaults,
    channel.streamingUx,
    channel.mediaAndVoice,
    channel.notes,
  ])

  const capabilityRows = listAgentOpsProductCapabilities().map((capability) => [
    capability.id,
    capability.label,
    capability.source,
    capability.description,
  ])

  const namespaceRows = listAgentOpsCapabilityNamespaces().map((namespace) => [
    namespace.prefix,
    namespace.label,
    namespace.owner,
    namespace.description,
  ])

  return [
    generatedHeader('Agent Ops Capability Matrix'),
    'This file is generated from `src/lib/agent-ops/capability-source.ts` so runtime, channel, workflow, docs, and UI claims stay aligned.',
    '',
    '## Runtime Profiles',
    '',
    table(
      ['Runtime', 'Model', 'Engines', 'Pulse contract', 'Channel ownership', 'Browser Operator', 'Memory', 'Project learnings', 'Notes'],
      runtimeRows,
    ),
    '',
    '## Channel Capabilities',
    '',
    table(
      ['Channel', 'Hosted', 'Managed outbound', 'Runtime native', 'Agent switching', 'Aliases/defaults', 'Streaming UX', 'Media/voice', 'Notes'],
      channelRows,
    ),
    '',
    '## Agent Ops Product Capabilities',
    '',
    table(['Capability', 'Label', 'Source', 'Description'], capabilityRows),
    '',
    '## Capability Namespaces',
    '',
    table(['Prefix', 'Label', 'Owner', 'Description'], namespaceRows),
    '',
  ].join('\n')
}

function buildSkillManifestDoc(): string {
  const providers = integrationProviders()
  const builtinRows = listAgentOpsBuiltinSkillSources().map((skill) => [
    skill.slug,
    skill.name,
    skill.loadPolicy,
    skill.engineSupport.join(', '),
    skill.runtimeProfiles.join(', '),
    skill.purpose,
    renderSkillSource(skill.sourceRef),
  ])

  const providerRows = providers.map((provider) => [
    provider,
    `worker/src/agent/skills/integrations/${provider}/SKILL.md`,
  ])

  return [
    generatedHeader('Agent Ops Skill Manifest'),
    'This file is generated from the Agent Ops capability source plus the filesystem-backed integration skill packages.',
    '',
    '## Built-In Skill Sources',
    '',
    table(['Slug', 'Name', 'Load policy', 'Engines', 'Runtime profiles', 'Purpose', 'Source'], builtinRows),
    '',
    '## Integration Skill Packages',
    '',
    `Provider count: ${providers.length}`,
    '',
    table(['Provider', 'Source'], providerRows),
    '',
  ].join('\n')
}

function buildExternalHostPacksDoc(): string {
  const manifest = buildAgentOpsExternalHostPackManifest()
  const packRows = listAgentOpsExternalHostPacks().map((pack) => [
    pack.label,
    pack.id,
    pack.installTarget,
    pack.format,
    pack.supportedEngines.join(', '),
    pack.runtimeProfiles.join(', '),
    pack.description,
  ])

  return [
    generatedHeader('Agent Ops External Host Packs'),
    'This file is generated from the Agent Ops external host pack registry. Host packs are install/package UX only; Lucid Cloud and Mission Control remain the system of record.',
    '',
    `Pack version: \`${manifest.version}\``,
    `Source of truth: \`${manifest.sourceOfTruth}\``,
    '',
    '## Host Packs',
    '',
    table(['Host', 'ID', 'Install target', 'Format', 'Engines', 'Runtime profiles', 'Description'], packRows),
    '',
    '## Generated Install Artifacts',
    '',
    ...listAgentOpsExternalHostPacks().map((pack) => `- \`docs/generated/host-packs/${pack.id}/${pack.fileName}\` -> \`${pack.installTarget}\``),
    '',
    '## Distribution API',
    '',
    '- `GET /api/agent-ops/external-host-packs` lists the authenticated host-pack manifest.',
    '- `GET /api/agent-ops/external-host-packs/[hostId]` returns the JSON export and rendered instructions.',
    '- `GET /api/agent-ops/external-host-packs/[hostId]?format=raw` returns install-ready Markdown/rule content for installer clients.',
    '- `docs/generated/agent-ops-external-host-installer-manifest.json` is the generated installer manifest shape for non-API consumers.',
    '- `npm run agent-ops:host-pack:check -- --host codex --root .` verifies whether an installed pack is current without writing files.',
    '- `npm run agent-ops:host-pack:check -- --host all --root .` verifies the full host-pack matrix for CI.',
    '- `npm run agent-ops:host-pack:install -- --host codex --root . --write` installs a generated pack locally after manifest hash verification.',
    '',
    '## Rule',
    '',
    'External host packs must not become the runtime source of Agent Ops behavior. They mirror the operating contract so external agents can collect evidence and hand work back to Lucid Cloud.',
    '',
  ].join('\n')
}

function writeOrCheck(relativePath: string, content: string): string | null {
  const absolutePath = join(root, relativePath)

  if (checkOnly) {
    const existing = existsSync(absolutePath) ? readFileSync(absolutePath, 'utf8') : ''
    return existing === content ? null : relativePath
  }

  mkdirSync(dirname(absolutePath), { recursive: true })
  writeFileSync(absolutePath, content, 'utf8')
  return null
}

const stale = [
  writeOrCheck('docs/generated/agent-ops-capability-matrix.md', buildCapabilityMatrixDoc()),
  writeOrCheck('docs/generated/agent-ops-skill-manifest.md', buildSkillManifestDoc()),
  writeOrCheck('docs/generated/agent-ops-external-host-packs.md', buildExternalHostPacksDoc()),
  writeOrCheck(
    'docs/generated/agent-ops-external-host-installer-manifest.json',
    `${JSON.stringify(buildAgentOpsExternalHostInstallerManifest(), null, 2)}\n`,
  ),
  ...listAgentOpsExternalHostPacks().map((pack) => writeOrCheck(
    `docs/generated/host-packs/${pack.id}/${pack.fileName}`,
    renderAgentOpsExternalHostInstructions({ hostId: pack.id }),
  )),
].filter((path): path is string => Boolean(path))

if (stale.length > 0) {
  console.error(`Agent Ops generated docs are stale:\n${stale.map((path) => `- ${path}`).join('\n')}`)
  console.error('Run `npm run agent-ops:capability-docs` and commit the regenerated files.')
  process.exit(1)
}

if (!checkOnly) {
  console.log('Generated Agent Ops capability docs.')
}
