#!/usr/bin/env python3
"""Initialize memory-bank for the c:/docs repo with the same structure as LucidMerged."""
import os

DOCS_MB = "c:/docs/memory-bank"
os.makedirs(DOCS_MB, exist_ok=True)

files = {
    "projectbrief.md": """# Project Brief — LucidLayer Documentation

## Overview
LucidLayer Docs is the public-facing developer documentation site for the LucidLayer platform — a verifiable AI inference network built on Solana. The docs are hosted on Mintlify and sourced from the `raijinlabs/docs` GitHub repo.

## Core Goals
- **Developer onboarding** — Get developers from zero to first API call in < 5 minutes
- **API reference** — Complete, auto-generated from OpenAPI spec (Speakeasy)
- **SDK documentation** — TypeScript SDK (primary), Python SDK (planned), REST reference
- **Platform guides** — Billing, API keys, metering, quotas, organizations
- **Conceptual docs** — Passports, inference, receipts, epochs, agents, MMR, Solana programs

## Target Audience
- Web3/AI developers integrating LucidLayer into their apps
- AI tool developers (MCP server integrations for Cursor, Claude Code, Windsurf)
- Platform users managing billing, API keys, and organizations

## Key Metrics
- 66 documentation pages across 6 tabs
- Auto-synced SDK docs from Speakeasy-generated sources
- OpenAPI-powered API reference

## Repository
- **Repo:** `raijinlabs/docs` on GitHub
- **Hosting:** Mintlify (auto-deploys on push to `main`)
- **Config:** `docs.json` (Mintlify configuration)
""",

    "productContext.md": """# Product Context — LucidLayer Documentation

## Why This Project Exists
LucidLayer is a complex platform combining AI inference, blockchain verification, and multi-tenant billing. Developers need clear, well-organized documentation to:
1. Understand core concepts (verifiable inference, passports, receipts, epochs)
2. Integrate the SDK into their applications
3. Use the API for programmatic access
4. Manage their platform account (billing, keys, quotas)

## Problems It Solves
- **Fragmented knowledge** — Centralizes all LucidLayer documentation in one place
- **SDK discoverability** — Auto-synced from Speakeasy so docs are always current
- **Developer friction** — Quickstart guides reduce time-to-first-call
- **MCP integration** — AI tool users (Cursor, Claude Code, Windsurf) can set up LucidLayer via MCP

## How It Should Work
- Mintlify renders the docs site from MDX files in this repo
- The OpenAPI spec is fetched from the SDK repo for API reference
- SDK pages are auto-rebuilt every 6 hours (or instantly via cross-repo dispatch)
- Navigation is organized into 6 tabs: Overview, Guides, API Reference, SDKs & Tools, Platform, Resources

## User Experience Goals
- Clean, searchable, fast-loading docs
- Dark/light mode with LucidLayer branding (emerald green theme)
- Code samples in TypeScript (primary) and cURL
- Clear progression: Getting Started → Concepts → Guides → API Reference
""",

    "systemPatterns.md": """# System Patterns — LucidLayer Documentation

## Architecture
```
raijinlabs/docs (GitHub)
    ├── docs.json              # Mintlify configuration (nav, theme, logo)
    ├── index.mdx              # Landing page
    ├── quickstart.mdx         # Getting started
    ├── authentication.mdx     # Auth guide
    ├── sdk-installation.mdx   # SDK setup
    ├── concepts/              # Core concept pages (passports, inference, etc.)
    ├── guides/                # Tutorial pages (beginner → advanced)
    ├── api-reference/         # API docs (OpenAPI-powered)
    ├── sdks/                  # SDK reference pages (auto-synced from Speakeasy)
    ├── ai-tools/              # MCP integration guides (Cursor, Claude Code, Windsurf)
    ├── platform/              # Platform management (billing, keys, quotas)
    ├── security/              # Security & compliance docs
    ├── changelog/             # Release notes
    ├── logo/                  # Brand assets (dark.svg, light.svg, lucid_w.png)
    ├── images/                # Documentation images
    ├── snippets/              # Reusable MDX snippets
    ├── scripts/               # Build/sync scripts
    └── .github/workflows/     # CI: auto-sync SDK docs
```

## Key Technical Decisions
1. **Mintlify** — Chosen for its MDX support, search, dark mode, API playground, and auto-deploy from GitHub
2. **Speakeasy SDK docs** — SDK pages are auto-generated by Speakeasy and synced via GitHub Actions
3. **OpenAPI reference** — API endpoints rendered from `openapi-with-code-samples.yaml` in the SDK repo
4. **SVG logos** — Using dark.svg/light.svg for logo (PNG had S3 403 issues)
5. **Tabbed navigation** — 6 tabs organizing 66 pages into logical groups

## CI/CD Pipeline
- **Docs repo workflow** (`.github/workflows/sync-sdk-docs.yml`):
  - Runs every 6 hours (cron) or on `repository_dispatch` from SDK repo
  - Fetches Speakeasy-generated content from `lucid-ai-sdk/typescript/docs/`
  - Rebuilds MDX pages in `sdks/` directory
  - Auto-commits changes
- **SDK repo trigger** (`.github/workflows/trigger-docs-sync.yml`):
  - Fires when `typescript/docs/**` changes in SDK repo
  - Uses `DOCS_SYNC_PAT` secret for cross-repo dispatch

## Design Patterns
- **MDX pages** — Frontmatter (title, description, icon) + markdown content
- **Snippets** — Reusable content blocks in `snippets/` directory
- **OpenAPI integration** — `\"openapi\"` key in docs.json navigation auto-generates endpoint pages
- **Tab-based nav** — Each tab has groups of pages for hierarchical organization
""",

    "techContext.md": """# Tech Context — LucidLayer Documentation

## Technologies Used
- **Mintlify** — Documentation platform (renders MDX, hosts site, provides search)
- **MDX** — Markdown with JSX components for rich documentation
- **GitHub Actions** — CI/CD for auto-syncing SDK docs
- **Speakeasy** — SDK generation tool (generates TypeScript SDK + docs from OpenAPI)
- **OpenAPI 3.x** — API specification format for auto-generated API reference
- **Python scripts** — Build/sync automation (rebuild-sdk-docs.py, etc.)

## Development Setup
```bash
# Clone the repo
git clone https://github.com/raijinlabs/docs.git
cd docs

# Install Mintlify CLI (optional, for local preview)
npm install -g mintlify

# Start local dev server
mintlify dev

# Rebuild SDK docs manually
python scripts/rebuild-sdk-docs.py
```

## Key Configuration Files
| File | Purpose |
|------|---------|
| `docs.json` | Mintlify config: navigation, theme, colors, logo, OpenAPI source |
| `.github/workflows/sync-sdk-docs.yml` | CI workflow for auto-syncing SDK docs |
| `scripts/rebuild-sdk-docs.py` | Python script to fetch + build SDK MDX pages |

## Dependencies
- **External:** Mintlify hosting, GitHub, Speakeasy (via lucid-ai-sdk repo)
- **Internal:** `raijinlabs/lucid-ai-sdk` (OpenAPI spec + Speakeasy docs source)

## Technical Constraints
- Mintlify has specific MDX component support (not all JSX works)
- OpenAPI spec must be publicly accessible URL for API playground
- Logo/images must be in repo (Mintlify serves from its S3, but relative paths work best)
- Maximum ~200 pages before navigation becomes unwieldy

## Repo Secrets
| Secret | Repo | Purpose |
|--------|------|---------|
| `DOCS_SYNC_PAT` | `lucid-ai-sdk` | Cross-repo dispatch to trigger docs rebuild |
""",

    "activeContext.md": """# Active Context — LucidLayer Documentation

## Current Work Focus
- Documentation site is live and operational on Mintlify
- Auto-sync pipeline for SDK docs is fully deployed
- Logo switched from PNG to SVG to fix Mintlify S3 403 error

## Recent Changes (Feb 2026)
1. **Sprint 1:** Created initial docs structure (index, quickstart, authentication, SDK installation)
2. **Sprint 2-4:** Added 40+ pages (guides, concepts, platform, API ref, changelog)
3. **SDK docs rebuild:** Rebuilt 8 SDK pages from Speakeasy-generated sources
4. **CI/CD:** Set up GitHub Actions for auto-syncing SDK docs (6h schedule + instant dispatch)
5. **Logo fix:** Switched to SVG logos (dark.svg/light.svg) to fix S3 403 error

## Active Decisions
- **AI Tools pages** — Created as MCP integration guides for Cursor, Claude Code, and Windsurf. These show developers how to configure `@lucidlayer/mcp-server` in their AI tools. Source: created by `scripts/build-docs-sprint2-4.py`.
- **SDK auto-sync** — Every 6 hours, docs repo polls SDK repo for Speakeasy changes. Can also be triggered instantly via `DOCS_SYNC_PAT` cross-repo dispatch.

## Next Steps
- [ ] Verify Mintlify deployment with new SVG logos
- [ ] Add more detailed content to AI tools pages (currently minimal)
- [ ] Add Python SDK documentation when Python SDK is ready
- [ ] Add webhook integration guides content
- [ ] Expand API reference with more code samples
- [ ] Add interactive examples/playground

## Important Notes
- The `@lucidlayer/mcp-server` npm package referenced in AI tools pages needs to be published
- OpenAPI spec URL in docs.json points to: `https://raw.githubusercontent.com/raijinlabs/lucid-ai-sdk/main/openapi-with-code-samples.yaml`
""",

    "progress.md": """# Progress — LucidLayer Documentation

## What Works ✅
- **Mintlify site:** Live, rendering 66 pages across 6 tabs
- **Navigation:** Overview, Guides, API Reference, SDKs & Tools, Platform, Resources
- **API Reference:** Auto-generated from OpenAPI spec in SDK repo
- **SDK docs:** 8 pages rebuilt from Speakeasy sources (typescript, passports, inference, receipts, agents, python, rest, mcp-server)
- **CI/CD:** GitHub Actions auto-sync SDK docs every 6 hours + instant dispatch
- **Logo:** SVG logos (dark/light) with PNG favicon
- **Theme:** Emerald green (#10B981) with dark mode support
- **AI Tools section:** MCP integration guides for Cursor, Claude Code, Windsurf

## What's Left to Build 🔨
- [ ] Flesh out AI tools page content (currently minimal setup instructions)
- [ ] Python SDK documentation (when SDK is ready)
- [ ] Webhook integration guide content
- [ ] More code samples in API reference
- [ ] Interactive playground/examples
- [ ] Custom domain setup (if not already done)
- [ ] Search optimization/custom snippets
- [ ] Video tutorials/walkthroughs
- [ ] Community/forum integration

## Current Status
- **Phase:** Post-launch, content enrichment
- **Pages:** 66 total MDX/MD files
- **Auto-sync:** Operational (6h schedule + instant cross-repo dispatch)
- **Last major update:** Feb 19, 2026 (Sprint 2-4, SDK rebuild, CI/CD, logo fix)

## Known Issues
- ~~Logo PNG returning 403 on Mintlify S3~~ → Fixed: switched to SVG logos
- AI tools pages reference `@lucidlayer/mcp-server` which may not be published yet
- Some guide pages may have placeholder content from batch generation

## Evolution of Decisions
1. **Initial setup** — Started with basic Mintlify template + docs.json
2. **Sprint 1** — Core pages (quickstart, auth, SDK installation)
3. **Sprint 2-4** — Bulk page generation (40+ pages via Python scripts)
4. **SDK rebuild** — Switched from template SDK pages to Speakeasy-sourced content
5. **CI/CD** — Added auto-sync pipeline for continuous SDK doc freshness
6. **Logo fix** — PNG → SVG to avoid Mintlify S3 access issues
""",
}

for filename, content in files.items():
    filepath = os.path.join(DOCS_MB, filename)
    with open(filepath, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")
    print(f"Created: memory-bank/{filename}")

print(f"\n✅ Memory bank initialized with {len(files)} files at {DOCS_MB}")