/**
 * Mock seed data for marketplace
 * Used when ASSETS_API_BASE is unset or returns non-200
 */

import { ApiAsset } from './types';

export const mockAssets: ApiAsset[] = [
  {
    external_id: 'mdl_mistral_7b',
    slug: 'mistral-7b',
    kind: 'MODEL',
    name: 'Mistral 7B Instruct',
    version: 'v0.2',
    summary: 'Fast, small LLM for chat & tools',
    tags: ['chat', 'tools', 'llm'],
    p95_ms: 620,
    cost_per_tok: 0.000002,
    eu_only: true,
    cc_on: true,
    owner_org_slug: 'mistral-ai',
    license: 'Apache 2.0',
  },
  {
    external_id: 'mdl_llama3_8b',
    slug: 'llama-3-8b',
    kind: 'MODEL',
    name: 'Llama 3 8B',
    version: 'v1.1',
    summary: 'General LLM 8B, fine-tunable',
    tags: ['general', 'finetune', 'llm'],
    p95_ms: 780,
    cost_per_tok: 0.0000018,
    eu_only: false,
    cc_on: false,
    owner_org_slug: 'meta',
    license: 'Llama 3 Community',
  },
  {
    external_id: 'ds_stackoverflow_2024',
    slug: 'stackoverflow-2024',
    kind: 'DATASET',
    name: 'StackOverflow 2024 QA',
    version: '2024-09',
    summary: 'Cleaned Q/A pairs for RAG',
    tags: ['code', 'rag', 'qa'],
    p95_ms: undefined,
    cost_per_tok: undefined,
    eu_only: false,
    cc_on: false,
    owner_org_slug: 'community',
    license: 'CC BY-SA 4.0',
  },
  {
    external_id: 'agt_support_helper',
    slug: 'support-helper',
    kind: 'AGENT',
    name: 'Support Helper',
    version: 'v0.7',
    summary: 'Ticket triage + canned replies',
    tags: ['support', 'triage', 'automation'],
    p95_ms: 540,
    cost_per_tok: 0.0000025,
    eu_only: true,
    cc_on: true,
    owner_org_slug: 'acme-inc',
    license: 'Commercial',
  },
  {
    external_id: 'cmp_h100_ccon_fr',
    slug: 'h100-ccon-fr',
    kind: 'COMPUTE',
    name: 'H100 CC-On (Paris)',
    version: 'nvidia-24.09',
    summary: 'Attested confidential compute in EU',
    tags: ['gpu', 'secure', 'nvidia'],
    p95_ms: 410,
    cost_per_tok: undefined,
    eu_only: true,
    cc_on: true,
    owner_org_slug: 'europe-cloud',
    license: 'On-Demand',
  },
  {
    external_id: 'mdl_gpt4_vision',
    slug: 'gpt4-vision',
    kind: 'MODEL',
    name: 'GPT-4 Vision',
    version: 'v1.0',
    summary: 'Multimodal LLM with image understanding',
    tags: ['vision', 'multimodal', 'gpt'],
    p95_ms: 1200,
    cost_per_tok: 0.00001,
    eu_only: false,
    cc_on: false,
    owner_org_slug: 'openai',
    license: 'Proprietary',
  },
  {
    external_id: 'ds_imagenet_full',
    slug: 'imagenet-full',
    kind: 'DATASET',
    name: 'ImageNet Full',
    version: '2024',
    summary: '14M images, 21K categories',
    tags: ['vision', 'classification', 'benchmark'],
    p95_ms: undefined,
    cost_per_tok: undefined,
    eu_only: false,
    cc_on: false,
    owner_org_slug: 'stanford',
    license: 'ImageNet License',
  },
  {
    external_id: 'agt_code_reviewer',
    slug: 'code-reviewer',
    kind: 'AGENT',
    name: 'Code Reviewer Pro',
    version: 'v2.1',
    summary: 'Automated PR review with security checks',
    tags: ['code', 'security', 'devops'],
    p95_ms: 890,
    cost_per_tok: 0.000003,
    eu_only: false,
    cc_on: true,
    owner_org_slug: 'github',
    license: 'MIT',
  },
  {
    external_id: 'mdl_whisper_large',
    slug: 'whisper-large-v3',
    kind: 'MODEL',
    name: 'Whisper Large v3',
    version: 'v3.0',
    summary: 'Speech-to-text in 99 languages',
    tags: ['audio', 'stt', 'multilingual'],
    p95_ms: 2100,
    cost_per_tok: 0.000006,
    eu_only: false,
    cc_on: false,
    owner_org_slug: 'openai',
    license: 'MIT',
  },
  {
    external_id: 'cmp_a100_depin',
    slug: 'a100-depin-network',
    kind: 'COMPUTE',
    name: 'A100 DePIN Network',
    version: 'v1.5',
    summary: 'Decentralized GPU compute mesh',
    tags: ['depin', 'gpu', 'distributed'],
    p95_ms: 650,
    cost_per_tok: undefined,
    eu_only: false,
    cc_on: false,
    owner_org_slug: 'render-network',
    license: 'Utility Token',
  },
  {
    external_id: 'agt_eval_harness',
    slug: 'eval-harness',
    kind: 'AGENT',
    name: 'Eval Harness Suite',
    version: 'v1.3',
    summary: 'Automated LLM benchmarking',
    tags: ['eval', 'benchmark', 'testing'],
    p95_ms: 1500,
    cost_per_tok: 0.000004,
    eu_only: false,
    cc_on: false,
    owner_org_slug: 'eleutherai',
    license: 'Apache 2.0',
  },
  {
    external_id: 'ds_common_crawl',
    slug: 'common-crawl-2024',
    kind: 'DATASET',
    name: 'Common Crawl 2024',
    version: '2024-10',
    summary: '250B tokens of web text',
    tags: ['web', 'pretraining', 'corpus'],
    p95_ms: undefined,
    cost_per_tok: undefined,
    eu_only: false,
    cc_on: false,
    owner_org_slug: 'common-crawl',
    license: 'Public Domain',
  },
];
