import 'server-only'

export const APP_BLUEPRINT_SELECT = [
  'id',
  'template_id',
  'org_id',
  'project_id',
  'slug',
  'name',
  'description',
  'category',
  'source',
  'status',
  'visibility',
  'version',
  'spec',
  'frontend_brief',
  'upgrade_metadata',
  'discovery_metadata',
  'tags',
  'install_count',
  'created_by',
  'created_at',
  'updated_at',
].join(', ')

export const APP_DEPLOYMENT_SELECT = [
  'id',
  'org_id',
  'project_id',
  'environment_id',
  'template_id',
  'blueprint_id',
  'generation_run_id',
  'name',
  'slug',
  'status',
  'visibility',
  'frontend_strategy',
  'frontend_manifest',
  'public_url',
  'preview_url',
  'custom_domain',
  'assistant_ids',
  'crew_id',
  'dag_ids',
  'template_deployment_ids',
  'runtime_id',
  'deployment_target',
  'latest_artifact_id',
  'created_by',
  'created_at',
  'updated_at',
  'deployed_at',
].join(', ')

export const APP_GENERATION_RUN_SELECT = [
  'id',
  'org_id',
  'project_id',
  'environment_id',
  'created_by',
  'prompt',
  'status',
  'stage',
  'progress',
  'input',
  'generated_spec',
  'selected_blueprint_id',
  'app_deployment_id',
  'idempotency_key',
  'provider_refs',
  'token_usage',
  'estimated_cost_cents',
  'error_code',
  'error_message',
  'created_at',
  'updated_at',
].join(', ')

export const APP_ARTIFACT_SELECT = [
  'id',
  'app_deployment_id',
  'generation_run_id',
  'kind',
  'version',
  'storage_url',
  'checksum',
  'metadata',
  'created_at',
].join(', ')

export const APP_DEPLOYMENT_EVENT_SELECT = [
  'id',
  'app_deployment_id',
  'generation_run_id',
  'event_type',
  'severity',
  'message',
  'provider',
  'external_id',
  'payload',
  'created_at',
].join(', ')

export const APP_BLUEPRINT_UPGRADE_RUN_SELECT = [
  'id',
  'app_deployment_id',
  'org_id',
  'project_id',
  'from_blueprint_id',
  'to_blueprint_id',
  'target_blueprint_slug',
  'from_version',
  'to_version',
  'status',
  'plan',
  'created_by',
  'applied_by',
  'created_at',
  'applied_at',
].join(', ')

export const APP_FRONTEND_GENERATION_SELECT = [
  'id',
  'generation_run_id',
  'app_deployment_id',
  'provider',
  'status',
  'provider_project_id',
  'provider_chat_id',
  'provider_version_id',
  'provider_deployment_id',
  'prompt_hash',
  'brief',
  'result',
  'preview_url',
  'web_url',
  'error_code',
  'error_message',
  'created_at',
  'updated_at',
].join(', ')

export const APP_EXTERNAL_DEPLOYMENT_SELECT = [
  'id',
  'app_deployment_id',
  'provider',
  'external_project_id',
  'external_deployment_id',
  'external_url',
  'status',
  'metadata',
  'created_at',
  'updated_at',
].join(', ')

export const APP_PUBLIC_USAGE_BUCKET_SELECT = [
  'id',
  'app_deployment_id',
  'org_id',
  'project_id',
  'bucket_kind',
  'metric',
  'bucket_start',
  'count_value',
  'created_at',
  'updated_at',
].join(', ')
