-- Migration: Seed Tier 2 Nango integrations into plugin_catalog
-- 14 providers: Discord, Trello, Reddit, PayPal, Typeform, Bitly, Instagram,
--               Facebook, TikTok, Canva, Lemlist, HeyGen, Whoop, Amazon

INSERT INTO plugin_catalog (
  slug, name, description, version, category,
  tool_manifest, source, risk_level, verified, max_tools, is_published,
  kind, transport, trust_level, execution_mode, auth_type, auth_provider
) VALUES

('discord', 'Discord', 'Discord integration for guild management and messaging.',
 '1.0.0', 'communication',
 '[{"name":"list_guilds","description":"List guilds the authenticated user belongs to","parameters":{"type":"object","properties":{"limit":{"type":"number","minimum":1,"maximum":200,"description":"Max guilds to return (1-200, default 200)"},"before":{"type":"string","description":"Get guilds before this guild ID"},"after":{"type":"string","description":"Get guilds after this guild ID"}},"additionalProperties":false}},{"name":"list_channels","description":"List channels in a guild","parameters":{"type":"object","properties":{"guild_id":{"type":"string","description":"Guild ID (required)"}},"required":["guild_id"],"additionalProperties":false}},{"name":"get_guild_info","description":"Get detailed information about a guild","parameters":{"type":"object","properties":{"guild_id":{"type":"string","description":"Guild ID (required)"},"with_counts":{"type":"boolean","description":"Include approximate member and presence counts"}},"required":["guild_id"],"additionalProperties":false}},{"name":"list_members","description":"List members of a guild with pagination","parameters":{"type":"object","properties":{"guild_id":{"type":"string","description":"Guild ID (required)"},"limit":{"type":"number","minimum":1,"maximum":1000,"description":"Max members to return (1-1000, default 1)"},"after":{"type":"string","description":"Get members after this user ID"}},"required":["guild_id"],"additionalProperties":false}},{"name":"send_message","description":"Send a message to a channel","parameters":{"type":"object","properties":{"channel_id":{"type":"string","description":"Channel ID (required)"},"content":{"type":"string","description":"Message content (required, max 2000 chars)"}},"required":["channel_id","content"],"additionalProperties":false}}]'::jsonb,
 'first-party', 'write', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'discord'),

('trello', 'Trello', 'Manage boards, lists, and cards in Trello.',
 '1.0.0', 'productivity',
 '[{"name":"list_boards","description":"List boards the authenticated user has access to","parameters":{"type":"object","properties":{"filter":{"type":"string","enum":["all","closed","members","open","organization","public","starred"],"description":"Filter boards (default: all)"},"fields":{"type":"string","description":"Comma-separated board fields to return"}},"additionalProperties":false}},{"name":"list_cards","description":"List cards in a Trello list","parameters":{"type":"object","properties":{"list_id":{"type":"string","description":"List ID (required)"},"filter":{"type":"string","enum":["all","closed","none","open","visible"],"description":"Filter cards (default: visible)"}},"required":["list_id"],"additionalProperties":false}},{"name":"list_lists","description":"List all lists on a board","parameters":{"type":"object","properties":{"board_id":{"type":"string","description":"Board ID (required)"},"filter":{"type":"string","enum":["all","closed","none","open"],"description":"Filter lists (default: all)"}},"required":["board_id"],"additionalProperties":false}},{"name":"create_card","description":"Create a new card on a Trello list","parameters":{"type":"object","properties":{"name":{"type":"string","description":"Card name (required)"},"idList":{"type":"string","description":"List ID to create the card in (required)"},"desc":{"type":"string","description":"Card description"},"pos":{"type":"string","description":"Position: top, bottom, or a positive float"},"due":{"type":"string","description":"Due date in ISO 8601 format"},"idLabels":{"type":"string","description":"Comma-separated label IDs"},"idMembers":{"type":"string","description":"Comma-separated member IDs"}},"required":["name","idList"],"additionalProperties":false}},{"name":"update_card","description":"Update an existing Trello card","parameters":{"type":"object","properties":{"card_id":{"type":"string","description":"Card ID (required)"},"name":{"type":"string","description":"Updated card name"},"desc":{"type":"string","description":"Updated description"},"closed":{"type":"boolean","description":"Whether the card is archived"},"idList":{"type":"string","description":"Move card to this list ID"},"due":{"type":"string","description":"Due date in ISO 8601 format"},"dueComplete":{"type":"boolean","description":"Whether the due date is complete"}},"required":["card_id"],"additionalProperties":false}}]'::jsonb,
 'first-party', 'write', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'trello'),

('reddit', 'Reddit', 'Browse subreddits and posts on Reddit.',
 '1.0.0', 'communication',
 '[{"name":"get_subreddit","description":"Get information about a subreddit","parameters":{"type":"object","properties":{"subreddit":{"type":"string","description":"Subreddit name without r/ prefix (required)"}},"required":["subreddit"],"additionalProperties":false}},{"name":"list_posts","description":"List hot posts from a subreddit","parameters":{"type":"object","properties":{"subreddit":{"type":"string","description":"Subreddit name without r/ prefix (required)"},"limit":{"type":"number","minimum":1,"maximum":100,"description":"Number of posts to return (1-100, default 25)"}},"required":["subreddit"],"additionalProperties":false}},{"name":"get_user_info","description":"Get information about the authenticated Reddit user","parameters":{"type":"object","properties":{},"additionalProperties":false}},{"name":"create_post","description":"Create a new post in a subreddit","parameters":{"type":"object","properties":{"sr":{"type":"string","description":"Subreddit name without r/ prefix (required)"},"title":{"type":"string","description":"Post title (required)"},"kind":{"type":"string","enum":["self","link"],"description":"Post type: self (text) or link (required)"},"text":{"type":"string","description":"Post body text (for self posts)"},"url":{"type":"string","description":"URL to link to (for link posts)"},"nsfw":{"type":"boolean","description":"Mark as NSFW"},"spoiler":{"type":"boolean","description":"Mark as spoiler"}},"required":["sr","title","kind"],"additionalProperties":false}}]'::jsonb,
 'first-party', 'write', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'reddit'),

('paypal', 'PayPal', 'Check balances, list transactions, and manage invoices via PayPal.',
 '1.0.0', 'finance',
 '[{"name":"get_balance","description":"Get the balance for all currencies in the PayPal account","parameters":{"type":"object","properties":{},"additionalProperties":false}},{"name":"list_transactions","description":"List transactions for the PayPal account within a date range","parameters":{"type":"object","properties":{"start_date":{"type":"string","description":"Start date in ISO 8601 format (required)"},"end_date":{"type":"string","description":"End date in ISO 8601 format (required)"},"page_size":{"type":"number","minimum":1,"maximum":500,"description":"Results per page (1-500, default 100)"},"page":{"type":"number","minimum":1,"description":"Page number (default 1)"},"transaction_status":{"type":"string","description":"Filter by status"}},"required":["start_date","end_date"],"additionalProperties":false}},{"name":"create_invoice","description":"Create a draft invoice in PayPal","parameters":{"type":"object","properties":{"detail":{"type":"object","description":"Invoice detail object"},"primary_recipients":{"type":"array","items":{"type":"object"},"description":"Array of recipient objects"},"items":{"type":"array","items":{"type":"object"},"description":"Array of item objects"}},"required":["detail","items"],"additionalProperties":false}},{"name":"send_invoice","description":"Send an existing draft invoice to the recipient","parameters":{"type":"object","properties":{"invoice_id":{"type":"string","description":"Invoice ID (required)"},"send_to_invoicer":{"type":"boolean","description":"Send a copy to the invoicer"},"send_to_recipient":{"type":"boolean","description":"Send to the recipient (default true)"}},"required":["invoice_id"],"additionalProperties":false}}]'::jsonb,
 'first-party', 'write', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'paypal'),

('typeform', 'Typeform', 'List forms and retrieve responses from Typeform.',
 '1.0.0', 'productivity',
 '[{"name":"list_forms","description":"List forms in the authenticated Typeform account","parameters":{"type":"object","properties":{"page":{"type":"number","minimum":1,"description":"Page number (default 1)"},"page_size":{"type":"number","minimum":1,"maximum":200,"description":"Results per page (1-200, default 10)"},"search":{"type":"string","description":"Search by form title"},"workspace_id":{"type":"string","description":"Filter by workspace ID"}},"additionalProperties":false}},{"name":"get_form_responses","description":"Get responses for a specific form","parameters":{"type":"object","properties":{"form_id":{"type":"string","description":"Form ID (required)"},"page_size":{"type":"number","minimum":1,"maximum":1000,"description":"Responses per page (1-1000, default 25)"},"since":{"type":"string","description":"Responses after this date (ISO 8601)"},"until":{"type":"string","description":"Responses before this date (ISO 8601)"},"after":{"type":"string","description":"Pagination cursor"},"completed":{"type":"boolean","description":"Filter by completion status"}},"required":["form_id"],"additionalProperties":false}},{"name":"get_form","description":"Get details of a specific form including fields and settings","parameters":{"type":"object","properties":{"form_id":{"type":"string","description":"Form ID (required)"}},"required":["form_id"],"additionalProperties":false}}]'::jsonb,
 'first-party', 'read', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'typeform'),

('bitly', 'Bitly', 'Create and manage shortened links with Bitly.',
 '1.0.0', 'marketing',
 '[{"name":"create_link","description":"Create a shortened Bitly link","parameters":{"type":"object","properties":{"long_url":{"type":"string","description":"The long URL to shorten (required)"},"domain":{"type":"string","description":"Custom domain (default: bit.ly)"},"title":{"type":"string","description":"Title for the link"},"group_guid":{"type":"string","description":"Group GUID"},"tags":{"type":"array","items":{"type":"string"},"description":"Tags to apply"}},"required":["long_url"],"additionalProperties":false}},{"name":"list_links","description":"List shortened links for the default group","parameters":{"type":"object","properties":{"group_guid":{"type":"string","description":"Group GUID (required)"},"size":{"type":"number","minimum":1,"maximum":100,"description":"Number of links to return (default 50)"},"page":{"type":"number","minimum":1,"description":"Page number"},"keyword":{"type":"string","description":"Filter by keyword in long URL"}},"required":["group_guid"],"additionalProperties":false}},{"name":"get_link_clicks","description":"Get click metrics for a specific bitlink","parameters":{"type":"object","properties":{"bitlink":{"type":"string","description":"Bitlink ID (e.g. bit.ly/abc123) (required)"},"unit":{"type":"string","enum":["minute","hour","day","week","month"],"description":"Time unit for aggregation (default: day)"},"units":{"type":"number","description":"Number of time units to query (-1 for all, default 30)"}},"required":["bitlink"],"additionalProperties":false}}]'::jsonb,
 'first-party', 'write', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'bitly'),

('instagram', 'Instagram', 'View profile, media, and engagement insights on Instagram.',
 '1.0.0', 'communication',
 '[{"name":"get_profile","description":"Get the authenticated Instagram user profile","parameters":{"type":"object","properties":{"fields":{"type":"string","description":"Comma-separated fields to return"}},"additionalProperties":false}},{"name":"list_media","description":"List recent media posts for the authenticated user","parameters":{"type":"object","properties":{"fields":{"type":"string","description":"Comma-separated fields"},"limit":{"type":"number","minimum":1,"maximum":100,"description":"Number of media items to return (default 25)"},"after":{"type":"string","description":"Pagination cursor"}},"additionalProperties":false}},{"name":"get_media_insights","description":"Get insights for a specific media post","parameters":{"type":"object","properties":{"media_id":{"type":"string","description":"Media ID (required)"},"metric":{"type":"string","description":"Comma-separated metrics"}},"required":["media_id"],"additionalProperties":false}}]'::jsonb,
 'first-party', 'read', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'instagram'),

('facebook', 'Facebook', 'Manage Facebook Pages, create posts, and view insights.',
 '1.0.0', 'communication',
 '[{"name":"list_pages","description":"List Facebook Pages managed by the authenticated user","parameters":{"type":"object","properties":{"fields":{"type":"string","description":"Comma-separated fields"},"limit":{"type":"number","minimum":1,"maximum":100,"description":"Number of pages to return (default 25)"}},"additionalProperties":false}},{"name":"create_post","description":"Create a post on a Facebook Page","parameters":{"type":"object","properties":{"page_id":{"type":"string","description":"Page ID (required)"},"message":{"type":"string","description":"Post text content"},"link":{"type":"string","description":"URL to share"},"published":{"type":"boolean","description":"Publish immediately (default true)"}},"required":["page_id"],"additionalProperties":false}},{"name":"get_page_insights","description":"Get insights for a Facebook Page","parameters":{"type":"object","properties":{"page_id":{"type":"string","description":"Page ID (required)"},"metric":{"type":"string","description":"Comma-separated metrics"},"period":{"type":"string","enum":["day","week","days_28"],"description":"Aggregation period (default: day)"},"since":{"type":"string","description":"Start date"},"until":{"type":"string","description":"End date"}},"required":["page_id"],"additionalProperties":false}}]'::jsonb,
 'first-party', 'write', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'facebook'),

('tiktok', 'TikTok', 'View TikTok profile and video analytics.',
 '1.0.0', 'communication',
 '[{"name":"get_user_info","description":"Get the authenticated TikTok user profile information","parameters":{"type":"object","properties":{"fields":{"type":"string","description":"Comma-separated fields"}},"additionalProperties":false}},{"name":"list_videos","description":"List videos posted by the authenticated user","parameters":{"type":"object","properties":{"max_count":{"type":"number","minimum":1,"maximum":20,"description":"Number of videos to return (1-20, default 10)"},"cursor":{"type":"number","description":"Pagination cursor"},"fields":{"type":"string","description":"Comma-separated fields"}},"additionalProperties":false}}]'::jsonb,
 'first-party', 'read', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'tiktok'),

('canva', 'Canva', 'List, view, and create designs in Canva.',
 '1.0.0', 'design',
 '[{"name":"list_designs","description":"List designs in the authenticated Canva account","parameters":{"type":"object","properties":{"query":{"type":"string","description":"Search query to filter designs"},"continuation":{"type":"string","description":"Pagination cursor"},"ownership":{"type":"string","enum":["owned","shared","any"],"description":"Filter by ownership (default: owned)"}},"additionalProperties":false}},{"name":"get_design","description":"Get details of a specific Canva design","parameters":{"type":"object","properties":{"design_id":{"type":"string","description":"Design ID (required)"}},"required":["design_id"],"additionalProperties":false}},{"name":"create_design","description":"Create a new design in Canva","parameters":{"type":"object","properties":{"design_type":{"type":"object","properties":{"type":{"type":"string","description":"Design type"}},"description":"Design type specification"},"title":{"type":"string","description":"Design title"},"asset_id":{"type":"string","description":"Template asset ID to start from"}},"additionalProperties":false}}]'::jsonb,
 'first-party', 'write', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'canva'),

('lemlist', 'Lemlist', 'Manage outbound email campaigns and leads in Lemlist.',
 '1.0.0', 'marketing',
 '[{"name":"list_campaigns","description":"List all campaigns in the Lemlist account","parameters":{"type":"object","properties":{"offset":{"type":"number","description":"Number of campaigns to skip"},"limit":{"type":"number","minimum":1,"maximum":100,"description":"Number of campaigns to return (default 100)"}},"additionalProperties":false}},{"name":"list_leads","description":"List leads in a specific campaign","parameters":{"type":"object","properties":{"campaign_id":{"type":"string","description":"Campaign ID (required)"},"offset":{"type":"number","description":"Number of leads to skip"},"limit":{"type":"number","minimum":1,"maximum":100,"description":"Number of leads to return (default 100)"}},"required":["campaign_id"],"additionalProperties":false}},{"name":"create_lead","description":"Add a lead to a campaign","parameters":{"type":"object","properties":{"campaign_id":{"type":"string","description":"Campaign ID (required)"},"email":{"type":"string","description":"Lead email address (required)"},"firstName":{"type":"string","description":"First name"},"lastName":{"type":"string","description":"Last name"},"companyName":{"type":"string","description":"Company name"},"phone":{"type":"string","description":"Phone number"}},"required":["campaign_id","email"],"additionalProperties":false}}]'::jsonb,
 'first-party', 'write', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'lemlist'),

('heygen', 'HeyGen', 'Generate AI avatar videos with HeyGen.',
 '1.0.0', 'media',
 '[{"name":"list_avatars","description":"List available avatars for video generation","parameters":{"type":"object","properties":{},"additionalProperties":false}},{"name":"create_video","description":"Create a new video with an avatar and script","parameters":{"type":"object","properties":{"video_inputs":{"type":"array","items":{"type":"object"},"description":"Array of video input objects (required)"},"dimension":{"type":"object","properties":{"width":{"type":"number"},"height":{"type":"number"}},"description":"Video dimensions"},"title":{"type":"string","description":"Video title"}},"required":["video_inputs"],"additionalProperties":false}},{"name":"get_video_status","description":"Get the status and details of a generated video","parameters":{"type":"object","properties":{"video_id":{"type":"string","description":"Video ID (required)"}},"required":["video_id"],"additionalProperties":false}}]'::jsonb,
 'first-party', 'write', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'heygen'),

('whoop', 'Whoop', 'Access Whoop health and fitness data including recovery, sleep, and workouts.',
 '1.0.0', 'health',
 '[{"name":"get_profile","description":"Get the authenticated Whoop user profile","parameters":{"type":"object","properties":{},"additionalProperties":false}},{"name":"get_recovery","description":"Get recovery data for the authenticated user","parameters":{"type":"object","properties":{"start":{"type":"string","description":"Start date in ISO 8601 format"},"end":{"type":"string","description":"End date in ISO 8601 format"},"limit":{"type":"number","minimum":1,"maximum":25,"description":"Number of records to return (default 10)"},"nextToken":{"type":"string","description":"Pagination token"}},"additionalProperties":false}},{"name":"get_sleep","description":"Get sleep data for the authenticated user","parameters":{"type":"object","properties":{"start":{"type":"string","description":"Start date in ISO 8601 format"},"end":{"type":"string","description":"End date in ISO 8601 format"},"limit":{"type":"number","minimum":1,"maximum":25,"description":"Number of records to return (default 10)"},"nextToken":{"type":"string","description":"Pagination token"}},"additionalProperties":false}},{"name":"get_workout","description":"Get workout data for the authenticated user","parameters":{"type":"object","properties":{"start":{"type":"string","description":"Start date in ISO 8601 format"},"end":{"type":"string","description":"End date in ISO 8601 format"},"limit":{"type":"number","minimum":1,"maximum":25,"description":"Number of records to return (default 10)"},"nextToken":{"type":"string","description":"Pagination token"}},"additionalProperties":false}}]'::jsonb,
 'first-party', 'read', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'whoop'),

('amazon', 'Amazon SES', 'Send emails and manage templates via Amazon SES.',
 '1.0.0', 'communication',
 '[{"name":"send_email","description":"Send an email via Amazon SES","parameters":{"type":"object","properties":{"FromEmailAddress":{"type":"string","description":"Sender email address (required)"},"Destination":{"type":"object","properties":{"ToAddresses":{"type":"array","items":{"type":"string"},"description":"Recipient email addresses"},"CcAddresses":{"type":"array","items":{"type":"string"},"description":"CC email addresses"},"BccAddresses":{"type":"array","items":{"type":"string"},"description":"BCC email addresses"}},"description":"Email destination (required)"},"Content":{"type":"object","properties":{"Simple":{"type":"object","properties":{"Subject":{"type":"object","properties":{"Data":{"type":"string"}},"description":"Email subject"},"Body":{"type":"object","properties":{"Text":{"type":"object","properties":{"Data":{"type":"string"}},"description":"Plain text body"},"Html":{"type":"object","properties":{"Data":{"type":"string"}},"description":"HTML body"}}}}}},"description":"Email content (required)"}},"required":["FromEmailAddress","Destination","Content"],"additionalProperties":false}},{"name":"list_email_templates","description":"List email templates in Amazon SES","parameters":{"type":"object","properties":{"PageSize":{"type":"number","minimum":1,"maximum":100,"description":"Number of templates to return (default 10)"},"NextToken":{"type":"string","description":"Pagination token"}},"additionalProperties":false}}]'::jsonb,
 'first-party', 'write', true, 10, true,
 'integration', 'nango', 'verified', 'in_process', 'oauth2', 'amazon')

ON CONFLICT (slug) DO UPDATE SET
  tool_manifest = EXCLUDED.tool_manifest,
  description = EXCLUDED.description,
  kind = EXCLUDED.kind,
  transport = EXCLUDED.transport,
  trust_level = EXCLUDED.trust_level,
  execution_mode = EXCLUDED.execution_mode,
  auth_type = EXCLUDED.auth_type,
  auth_provider = EXCLUDED.auth_provider,
  updated_at = now();
